### ISSUE TITLE
CPP2 generated code does not have field setters

### ISSUE THREAD

**Issue by kishorenc** [facebook/fbthrift#101]
I don't see any field setter methods when I generate using the cpp2 compiler. In Apache Thrift, there will be setters like this:

` obj.__set_field_name(some_value);`

It looks like in fbthrift, I have to manually set the bools in the `__isset` struct for each field during assignment... Am I missing something?

**Comment by alandau** [comment]
Yeah, for now you have to set __isset for every field... We'll add an option soon to generate optional fields with folly::Optional instead. https://github.com/facebook/folly/blob/master/folly/Optional.h
