### ISSUE TITLE
configure.ac conflates cpp runtime with compiler build

### ISSUE THREAD

**Issue by jesboat** [facebook/fbthrift#102]
https://github.com/facebook/fbthrift/blob/b5635e3675023979c87d8b16182402c1ffba32a4/thrift/configure.ac#L143 lines 143-207 have logic roughly:
1. Parse `--with-cpp` on configure command line to $with_cpp
2. Set have_cpp=yes
   If `with_cpp=yes`:
     3a. check existence of some libraries necessary to build compiler
     3b. do AX_BOOST_PYTHON (for thrift/compiler/py)
     3c. check existence of a bunch of libraries to build cpp runtime
3. set WITH_CPP to $have_cpp (i.e. set WITH_CPP=true unconditionally)

The effect is that (a) the `--with-cpp` option controls whether configure checks for libraries and does AX_BOOST_PYTHON (b) the cpp runtime, contrary with `--with-cpp`'s documentation, is always built. Both of these are problems when building on platforms where the cpp runtime is impossible (e.g. OSX which lacks libnuma): it's impossible to get thrift/compiler/py to build without non-trivial mods to configure.ac to get AX_BOOST_PYTHON to work, and it's impossible to skip thrift/lib/cpp\* without modifying configure.ac or Makefile.am.

Probably the easiest way to fix this would be to move 3a and 3b out of the if, and remove 2 and 4 entirely. (I think that's sufficient; note though that the thrift/compiler/py build has other problems, e.g. https://github.com/facebook/fbthrift/issues/62 and https://github.com/facebook/fbthrift/issues/50 (which is caused when AX_BOOST_PYTHON fails to detect the right BOOST_PYTHON_LIB) and https://github.com/facebook/fbthrift/issues/21). It looks like configure.ac could use an overhaul in general, though, since it still includes a bunch of stuff for thrift/lib/blah runtimes which have been removed from the build.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
