### ISSUE TITLE
folly related problem during make

### ISSUE THREAD

**Issue by yusufziyaisik** [facebook/fbthrift#103]
I got the below error during make 

"g++ -DHAVE_CONFIG_H   -fPIC -I../../..  -pthread -I/usr/include  -I../cpp -I../../../../gperftools-2.0.99/src -I/usr/local/include   -std=gnu++0x -MT gen-cpp2/libsaslstubs_a-SaslAuthService.o -MD -MP -MF gen-cpp2/.deps/libsaslstubs_a-SaslAuthService.Tpo -c -o gen-cpp2/libsaslstubs_a-SaslAuthService.o `test -f 'gen-cpp2/SaslAuthService.cpp' || echo './'`gen-cpp2/SaslAuthService.cpp
In file included from ../../../thrift/lib/cpp2/ServiceIncludes.h:5:0,
                 from gen-cpp2/SaslAuthService.h:9,
                 from gen-cpp2/SaslAuthService.cpp:7:
../../../thrift/lib/cpp2/async/AsyncProcessor.h:33:38: fatal error: folly/wangle/rx/Observer.h: No such file or directory
#include \<folly/wangle/rx/Observer.h\>"

When I look at the folly subdirectory in /usr/local/include, I see that Observer.h is now in subfolder folly/wangle/deprecated/rx/

How can I fix this issue? Is fbthrift compatible with the latest version of folly?

Yusuf

**Comment by djwatson** [comment]
version mismatch.  Should be fixed in newer versions
