### ISSUE TITLE
Folly dependencies are broken 

### ISSUE THREAD

**Issue by pedropgusmao** [facebook/fbthrift#104]
Hi, 
the folly library is getting many updates lately and I think it has broken some of your dependecies...
When I try to compile fbthrist I get:
```../../../thrift/lib/cpp2/async/FutureRequest.h:98:33:   required from here
/usr/local/include/folly/futures/detail/Core.h:77:3: error: static assertion failed: void futures are not supported. Use Unit instead.
   static_assert(!std::is_void<T>::value,```

Are there planes for code alignment? 

Thanks,

Pedro

**Comment by andrewcox** [comment]
fbthrift builds against a specific revision of folly. Did you try running the deps.sh script in fbthrift?

**Comment by pedropgusmao** [comment]
Hi, 
Thanks for your reply and sorry, no I didn't. I did it manually...
Sorry for wrong issue.
