### ISSUE TITLE
Fbthrift cpp2 code generation error when parsing thrift file with included enum 

### ISSUE THREAD

**Issue by azgo14** [facebook/fbthrift#105]
There seems to be an error when generating cpp2 code from the following thrift files:
**a.thrift**
enum TEST {
  A = 0
}

**b.thrift**
include "a.thrift"
const a.TEST test = a.TEST.A

**Running the following**
fbthrift --gen cpp2  ~/code/schemas/b.thrift 

**Output**
[WARNING] Constant strings should be quoted: a.TEST.A
[FAILURE] type error: const "test" was declared as enum

I have checked that both apache thrift and scrooge thrift can compile this scenario just fine.

**Comment by andrewcox** [comment]
Coincidentally, we are working on bringing this patch into our tree (the one to parse qualified enum values), but it isn't there yet.

**Comment by azgo14** [comment]
awesome! Is there a timeline on when you expect the patch to make it in?

**Comment by iceboundflame** [comment]
Just hit this as well. Please fix!

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
