### ISSUE TITLE
Using custom protocols with fbthrift.

### ISSUE THREAD

**Issue by jaaju** [facebook/fbthrift#119]
Hi,

I want to use a custom protocol to encode messages. This was possible in apache thrift by extending TVirtualProtocol. fbthrift, however, seems to have a fixed enumeration of protocols (https://github.com/facebook/fbthrift/blob/master/thrift/lib/cpp/protocol/TProtocolTypes.h#L22). Is it possible to do something similar with fbthrift?

Meanwhile, to understand how fbthrift works I generated code using '--gen cpp2:json' argument to the thrift compiler. Both client and server code generated by this only handle Compact and Binary protocols, and have explicit code that rejects/ignores all other cases. Is there any example where I can see T_SIMPLE_JSON_PROTOCOL in action?

Appreciate your help.
Thanks,
jay

**Comment by jaaju** [comment]
Is this the right place to get help regarding fbthrift? Past threads also suggest not much seems to be happening here!

**Comment by djwatson** [comment]
There is cpp2/protocol/VirtualProtocol, but I don't think we use it internally. 

Adding your custom protocol to the list in the generator should be enough to get it working though.

Unfortunately I don't think there are any explicit json examples
