### ISSUE TITLE
Error with Cpp2Worker.h when make fbthrift

### ISSUE THREAD

**Issue by hoanganhbui** [facebook/fbthrift#120]
While trying to build and understand about facebook's Wedge, I tried to make fbthrift with instructions in README, but when I run make in thrift directory, it get this error in make[5]. I'm not good at Cpp so  Please help me solve this!!! Thank you!

In file included from ../../../thrift/lib/cpp2/server/Cpp2Connection.h:29:0,
                 from server/Cpp2Connection.cpp:17:
../../../thrift/lib/cpp2/server/Cpp2Worker.h:110:8: error: 'void apache::thrift::Cpp2Worker::onNewConnection(folly::AsyncSocket::UniquePtr, const folly::SocketAddress*, consterride, but does not override
   void onNewConnection(folly::AsyncSocket::UniquePtr,
            ^

**Comment by azgo14** [comment]
Also have this problem after upgrading

**Comment by djwatson** [comment]
Looks like a version mismatch between wangle and fbthrift.  Should be fixed after upgrade

**Comment by BestSonny** [comment]
Also get stuck in here. Is there anybody to give a detail on solving it?
