### ISSUE TITLE
fbthrift doesn't build on OSX for several reasons

### ISSUE THREAD

**Issue by umanwizard** [facebook/fbthrift#122]
(1) numa.h is required - doesn't exist on OSX.
(2) wangle doesn't build right now - see https://github.com/facebook/wangle/issues/6
(3) The "timed" family of pthread functions, which don't exist on OSX, are used in thrift/lib/cpp/concurrency/Mutex-impl.h . These include: pthread_mutex_timedlock, pthread_rwlock_timedwrlock, pthread_rwlock_timedrdlock
(4) In various Makefile.ac files, we use "-lboost_thread" literally instead of $(BOOST_THREAD_LIB). This breaks on OSX, where -lboost_thread doesn't exist and BOOST_THREAD_LIB is set to -lboost_thread-mt instead

Edit: Looks like someone has sent a patch fixing (3) to Apache. I haven't looked at it so IDK if it works. https://issues.apache.org/jira/browse/THRIFT-736

**Comment by umanwizard** [comment]
BTW, there could be other reasons. These are just the ones I found before I gave up on trying.

**Comment by ryanrhee** [comment]
Update: 1 and 2 are fixed, apparently.
Still need to fix 3 and 4, and who knows what else.

**Comment by adamist521** [comment]
+1!

**Comment by adamist521** [comment]
Is (1) fixed?
Still can't find libnuma on homebrew...

**Comment by djwatson** [comment]
The hard dependency for numa has been removed, I think the Makefiles might still need updating to make it optional though

**Comment by ppLorins** [comment]
@djwatson   Does the numa optional  dependency become available now ?   I encounter the same problem on macosx, stucked here . I ever try to compile nume by hand , found it was even impossible for too much reasons

**Comment by elbamos** [comment]
I'm hitting the same issue, libnuma.  Can anyone provide guidance on dealing with this?

**Comment by elbamos** [comment]
After taking numa out of the makefiles, there's a type error thrown by THeader.cpp at line 149, which is easy to fix.  

That leaves (3) from the list above. The patch at Apache-thrift-736 does not work.  There are now three functions that need to be dealt with, pthread_mutex_timedlock, pthread_rwlock_timedrdlock, and pthread_rwlock_timedrdlock.  

pthread_mutex_timedlock is pretty easy to just implement, but I haven't solved the other two.

**Comment by umanwizard** [comment]
Is this still the state of the world?

**Comment by ryanrhee** [comment]
@elbamos:

> pthread_mutex_timedlock, pthread_rwlock_timedrdlock, and pthread_rwlock_timedrdlock

Uhh, you wrote pthread_rwlock_timedrdlock twice. I'm curious, what's the third function that needs to be dealt with?

**Comment by elbamos** [comment]
I ended up switching to Ubuntu so I could use this library. I have a vague recollection that there were two functions with the same name but different signatures, but I haven't looked at this in months.

**Comment by ryanrhee** [comment]
Unless @djwatson did some work, I'm guessing this is still the state of the world @umanwizard. :/

**Comment by seanfarley** [comment]
This can *finally* be closed!

**Comment by elbamos** [comment]
Seriously?

**Comment by seanfarley** [comment]
> Seriously?

Yep. You can even do `port install fbthrift`.

**Comment by elbamos** [comment]
Very cool!!!
