### ISSUE TITLE
why fbthrift needs wangle

### ISSUE THREAD

**Issue by joan2015** [facebook/fbthrift#123]
when excute "autoreconf -if && ./configure && make" ,stop with "configure: error: Please install the wangle library from https://github.com/facebook/wangle"

**Comment by roticv** [comment]
You can think of wangle as providing the basis for fbthrift. For example, ThriftServer uses wangle's ServerBootstrap.

**Comment by joan2015** [comment]
ok,but why the dep*.sh do not contain it?

**Comment by lixiangnlp** [comment]
@joan2015 I can not compile wangle successfully. The error is 

/usr/bin/ld: warning: libboost_thread.so.1.59.0, needed by /usr/local/lib/../lib/libfolly.so, may conflict with libboost_thread.so.1.54.0
/usr/bin/ld: warning: libboost_system.so.1.59.0, needed by /usr/local/lib/../lib/libfolly.so, may conflict with libboost_system.so.1.54.0
/usr/bin/ld: ../gmock/src/gmock-build/libgmock.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [bin/AcceptorTest] error 1
make[1]: *** [CMakeFiles/AcceptorTest.dir/all] error 2
make: *** [all] error 2

Do you know how to install fbthrift and wangle on ubuntu 14.04? Thanks.

**Comment by djwatson** [comment]
gmock wangle issue should be fixed
