### ISSUE TITLE
Build artefacts not properly ignored

### ISSUE THREAD

**Issue by LinusU** [facebook/fbthrift#125]
Building this projects leaves build artefacts that aren't ignored by `.gitignored`.

Untracked files:
- thrift/compiler/py/dist/
- thrift/compiler/py/thrift_py.egg-info/

Modified files:
- thrift/lib/cpp/thrift_config.h

The modified file is actually created when running `./configure` and I don't think that it should be checked in at all.

Pull request will follow shortly.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
