### ISSUE TITLE
Synchronization between fbthrift and Apache Thrift?

### ISSUE THREAD

**Issue by daixtrose** [facebook/fbthrift#132]
I am a little bit concerned about the fact that Thrift [was handed over to Apache.org](https://thrift.apache.org/) and now this fork here tends to get out of sync with the Apache version. I cannot see the long term benefit of this.

Also it seems that fbthrift supports float, but Apache Thrift does not (see [THRIFT-2457](https://issues.apache.org/jira/browse/THRIFT-2457)). Anyone who could merge that change into the Apache Thrift version?

**Comment by djwatson** [comment]
There was a tracking task for merging things back - 
https://issues.apache.org/jira/browse/THRIFT-2422

floats were one of the few things remaining.  

Facebook needed greater control over the source / push process.  We're not pushing this as a replacement for Apache, and still trying to merge things back as time allows.
