### ISSUE TITLE
Current version doesn't compile.

### ISSUE THREAD

**Issue by williford** [facebook/fbthrift#140]
There is a little typo (async spelled as asybc) that prevents the current version from being able to be compiled. Please merge one of these two PRs or otherwise fix the typo:
https://github.com/facebook/fbthrift/pull/137
https://github.com/facebook/fbthrift/pull/139

I noticed that there was already a PR after I fixed the issue. Since it is just a single character change, the PRs are identical.

**Comment by ckwalsh** [comment]
Fixed in https://github.com/facebook/fbthrift/pull/139
