### ISSUE TITLE
Python asyncio problems

### ISSUE THREAD

**Issue by vmarkovtsev** [facebook/fbthrift#145]
1) There is no `thrift_asyncio.tutorial` for `thrift/tutorial/py.asyncio/PythonClient.py`
2) Upon successful connection, every yield from / await command hangs. Tested on HBase (https://raw.githubusercontent.com/apache/hbase/b8e2e4a1e7c275752177baf64d6bf01e0da8228c/hbase-thrift/src/main/resources/org/apache/hadoop/hbase/thrift/Hbase.thrift) + `thrift1 --gen py:asyncio`

**Comment by snarkmaster** [comment]
Can you try `--gen py-asyncio` instead of `--gen py:asyncio`? @ambv or @haijunz might also know what's going on here.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
