### ISSUE TITLE
build on centos  compile  error : cannot find -l-L/usr/local/python-2.7.11/lib  

### ISSUE THREAD

**Issue by yuzzjj** [facebook/fbthrift#149]
/bin/sh ../../libtool  --tag=CXX   --mode=link /usr/local/gcc-4.9.3/bin/g++  -std=gnu++1y -module -avoid-version -no-undefined -l -L/usr/local/python-2.7.11/lib -lpython2.7 -L/usr/local/lib -o frontend.la -rpath /usr/local/lib frontend_la-compiler.lo ../libparse.la ../libthriftcompilerbase.la -lssl -lcrypto -lrt -lpthread -lsasl2 -lwangle -lnuma -lsnappy -lgflags -lglog

libtool: link: /usr/local/gcc-4.9.3/bin/g++ -shared -nostdlib /usr/lib/../lib64/crti.o /usr/local/gcc-4.9.3/lib/gcc/x86_64-redhat-linux/4.9.3/crtbeginS.o  .libs/frontend_la-compiler.o  -Wl,--whole-archive ../.libs/libparse.a ../.libs/libthriftcompilerbase.a -Wl,--no-whole-archive  -Wl,-rpath -Wl,/usr/local/gcc-4.9.3/lib/../lib64 -Wl,-rpath -Wl,/usr/local/gcc-4.9.3/lib/../lib64 -l -L/usr/local/python-2.7.11/lib -lpython2.7 -L/usr/local/lib -lssl -lcrypto -lrt /usr/local/lib/libsasl2.so -ldl -lresolv -lwangle -lnuma /usr/local/lib/libsnappy.so -lgflags /usr/local/lib/libglog.so -L/usr/local/gcc-4.9.3/lib/../lib64 -lpthread -L/usr/local/gcc-4.9.3/lib/gcc/x86_64-redhat-linux/4.9.3 -L/usr/local/gcc-4.9.3/lib/gcc/x86_64-redhat-linux/4.9.3/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/local/gcc-4.9.3/lib/gcc/x86_64-redhat-linux/4.9.3/../../.. /usr/local/gcc-4.9.3/lib/../lib64/libstdc++.so -lm -lc -lgcc_s /usr/local/gcc-4.9.3/lib/gcc/x86_64-redhat-linux/4.9.3/crtendS.o /usr/lib/../lib64/crtn.o    -Wl,-soname -Wl,frontend.so -o .libs/frontend.so
/usr/bin/ld: cannot find -l-L/usr/local/python-2.7.11/lib
collect2: error: ld returned 1 exit status

**Comment by snarkmaster** [comment]
There is not enough context to reproduce this -- no OS version, none of the commands you ran to get here, and no git hash of your checkout. Could you please reopen or resubmit with enough detail that somebody could reproduce this? :)
