### ISSUE TITLE
run the example in tutorial/php failed

### ISSUE THREAD

**Issue by joan2015** [facebook/fbthrift#151]
I tried the singlethreaded_server.php and 
I got an error like this :   PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in  fbthrift-0.20.0/thrift/lib/php/src/Thrift.php on line 403. why ?

**Comment by alandau** [comment]
Please try the latest version - 0.20 is more than a year old. From looking at the code, this specific issue should've been fixed.
