### ISSUE TITLE
RHEL 7 build fbthrift fail "gen-cpp2/Sasl_types.h error: expected ‘)’ before ‘<’ token"

### ISSUE THREAD

**Issue by binlijin** [facebook/fbthrift#152]
What wrong with the fail?

```
g++ -DHAVE_CONFIG_H   -fPIC -I../../..  -pthread -I/usr/include  -I../cpp -I../../../../gperftools-2.0.99/src -I/usr/local/include   -std=gnu++0x -MT gen-cpp2/libsaslstubs_a-Sasl_constants.o -MD -MP -MF gen-cpp2/.deps/libsaslstubs_a-Sasl_constants.Tpo -c -o gen-cpp2/libsaslstubs_a-Sasl_constants.o `test -f 'gen-cpp2/Sasl_constants.cpp' || echo './'`gen-cpp2/Sasl_constants.cpp
In file included from gen-cpp2/Sasl_constants.h:9:0,
                 from gen-cpp2/Sasl_constants.cpp:7:
gen-cpp2/Sasl_types.h:40:57: error: expected ‘)’ before ‘<’ token
   SaslOutcome(::apache::thrift::detail::argument_wrapper<1, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                         ^
In file included from gen-cpp2/Sasl_constants.h:9:0,
                 from gen-cpp2/Sasl_constants.cpp:7:
gen-cpp2/Sasl_types.h:47:57: error: expected ‘)’ before ‘<’ token
   SaslOutcome(::apache::thrift::detail::argument_wrapper<2, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                         ^
gen-cpp2/Sasl_types.h:162:57: error: expected ‘)’ before ‘<’ token
   SaslRequest(::apache::thrift::detail::argument_wrapper<1, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                         ^
gen-cpp2/Sasl_types.h:169:57: error: expected ‘)’ before ‘<’ token
   SaslRequest(::apache::thrift::detail::argument_wrapper<2, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                         ^
gen-cpp2/Sasl_types.h:290:55: error: expected ‘)’ before ‘<’ token
   SaslReply(::apache::thrift::detail::argument_wrapper<1, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                       ^
gen-cpp2/Sasl_types.h:297:55: error: expected ‘)’ before ‘<’ token
   SaslReply(::apache::thrift::detail::argument_wrapper<2, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                       ^
gen-cpp2/Sasl_types.h:304:55: error: expected ‘)’ before ‘<’ token
   SaslReply(::apache::thrift::detail::argument_wrapper<3, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                       ^
gen-cpp2/Sasl_types.h:434:55: error: expected ‘)’ before ‘<’ token
   SaslStart(::apache::thrift::detail::argument_wrapper<1, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                       ^
gen-cpp2/Sasl_types.h:441:55: error: expected ‘)’ before ‘<’ token
   SaslStart(::apache::thrift::detail::argument_wrapper<2, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                       ^
gen-cpp2/Sasl_types.h:448:55: error: expected ‘)’ before ‘<’ token
   SaslStart(::apache::thrift::detail::argument_wrapper<3, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
```

**Comment by binlijin** [comment]
gcc version 4.8.5

**Comment by snarkmaster** [comment]
Does the build make more progress if you manually insert "typename " after the "("? I.e.

```
   SaslStart(typename ::apache::thrift::detail::argument_wrapper<1, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
```

Either way, I'm surprised this fails, since I think I've seen fbthrift build successfully with gcc 4.8.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.

**Comment by cuong21951** [comment]
> Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.

Can you show me the document cause i've just met this issue

**Comment by yfeldblum** [comment]
`Sasl.thrift` no longer exists.

**Comment by cuong21951** [comment]
> `Sasl.thrift` no longer exists.

/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:45:58: error: expected ')' before '<' token
   NodeAddrInfo(::apache::thrift::detail::argument_wrapper<1, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                          ^
In file included from /home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../base/config.h:13:0,
                 from /home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/config.cc:1:
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:52:58: error: expected ')' before '<' token
   NodeAddrInfo(::apache::thrift::detail::argument_wrapper<2, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                          ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:150:32: error: expected initializer before '<' token
 template <> inline void Cpp2Ops< ::seqsvr::NodeAddrInfo>::clear( ::seqsvr::NodeAddrInfo* obj) {
                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:154:69: error: expected initializer before '<' token
 template <> inline constexpr apache::thrift::protocol::TType Cpp2Ops< ::seqsvr::NodeAddrInfo>::thriftType() {
                                                                     ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:158:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::NodeAddrInfo>::write(Protocol* proto,  ::seqsvr::NodeAddrInfo const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:162:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::NodeAddrInfo>::read(Protocol* proto,  ::seqsvr::NodeAddrInfo* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:166:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::NodeAddrInfo>::serializedSize(Protocol const* proto,  ::seqsvr::NodeAddrInfo const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:170:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::NodeAddrInfo>::serializedSizeZC(Protocol const* proto,  ::seqsvr::NodeAddrInfo const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:192:53: error: expected ')' before '<' token
   RangeID(::apache::thrift::detail::argument_wrapper<1, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                     ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:199:53: error: expected ')' before '<' token
   RangeID(::apache::thrift::detail::argument_wrapper<2, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                     ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:292:32: error: expected initializer before '<' token
 template <> inline void Cpp2Ops< ::seqsvr::RangeID>::clear( ::seqsvr::RangeID* obj) {
                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:296:69: error: expected initializer before '<' token
 template <> inline constexpr apache::thrift::protocol::TType Cpp2Ops< ::seqsvr::RangeID>::thriftType() {
                                                                     ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:300:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::RangeID>::write(Protocol* proto,  ::seqsvr::RangeID const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:304:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::RangeID>::read(Protocol* proto,  ::seqsvr::RangeID* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:308:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::RangeID>::serializedSize(Protocol const* proto,  ::seqsvr::RangeID const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:312:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::RangeID>::serializedSizeZC(Protocol const* proto,  ::seqsvr::RangeID const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:332:56: error: expected ')' before '<' token
   RouterNode(::apache::thrift::detail::argument_wrapper<1, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                        ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:339:56: error: expected ')' before '<' token
   RouterNode(::apache::thrift::detail::argument_wrapper<2, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                        ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:430:32: error: expected initializer before '<' token
 template <> inline void Cpp2Ops< ::seqsvr::RouterNode>::clear( ::seqsvr::RouterNode* obj) {
                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:434:69: error: expected initializer before '<' token
 template <> inline constexpr apache::thrift::protocol::TType Cpp2Ops< ::seqsvr::RouterNode>::thriftType() {
                                                                     ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:438:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::RouterNode>::write(Protocol* proto,  ::seqsvr::RouterNode const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:442:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::RouterNode>::read(Protocol* proto,  ::seqsvr::RouterNode* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:446:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::RouterNode>::serializedSize(Protocol const* proto,  ::seqsvr::RouterNode const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:450:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::RouterNode>::serializedSizeZC(Protocol const* proto,  ::seqsvr::RouterNode const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:471:52: error: expected ')' before '<' token
   Router(::apache::thrift::detail::argument_wrapper<1, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                    ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:478:52: error: expected ')' before '<' token
   Router(::apache::thrift::detail::argument_wrapper<2, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                    ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:570:32: error: expected initializer before '<' token
 template <> inline void Cpp2Ops< ::seqsvr::Router>::clear( ::seqsvr::Router* obj) {
                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:574:69: error: expected initializer before '<' token
 template <> inline constexpr apache::thrift::protocol::TType Cpp2Ops< ::seqsvr::Router>::thriftType() {
                                                                     ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:578:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::Router>::write(Protocol* proto,  ::seqsvr::Router const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:582:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::Router>::read(Protocol* proto,  ::seqsvr::Router* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:586:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::Router>::serializedSize(Protocol const* proto,  ::seqsvr::Router const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:590:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::Router>::serializedSizeZC(Protocol const* proto,  ::seqsvr::Router const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:610:57: error: expected ')' before '<' token
   SetNodeInfo(::apache::thrift::detail::argument_wrapper<1, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                         ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:617:57: error: expected ')' before '<' token
   SetNodeInfo(::apache::thrift::detail::argument_wrapper<2, T__ThriftWrappedArgument__Ctor> arg, Args__ThriftWrappedArgument__Ctor&&... args):
                                                         ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:708:32: error: expected initializer before '<' token
 template <> inline void Cpp2Ops< ::seqsvr::SetNodeInfo>::clear( ::seqsvr::SetNodeInfo* obj) {
                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:712:69: error: expected initializer before '<' token
 template <> inline constexpr apache::thrift::protocol::TType Cpp2Ops< ::seqsvr::SetNodeInfo>::thriftType() {
                                                                     ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:716:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::SetNodeInfo>::write(Protocol* proto,  ::seqsvr::SetNodeInfo const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:720:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::SetNodeInfo>::read(Protocol* proto,  ::seqsvr::SetNodeInfo* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:724:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::SetNodeInfo>::serializedSize(Protocol const* proto,  ::seqsvr::SetNodeInfo const* obj) {
                                                ^
/home/cuong/Desktop/seqsvr/seqsvr/seqsvr/base/../proto/gen-cpp2/seqsvr_types.h:728:48: error: too many template-parameter-lists
 template <> template <class Protocol> uint32_t Cpp2Ops< ::seqsvr::SetNodeInfo>::serializedSizeZC(Protocol const* proto,  ::seqsvr::SetNodeInfo const* obj) {

I've just met this

**Comment by yfeldblum** [comment]
Which compiler and compiler version and with which language version is it invoked?
