### ISSUE TITLE
Lua Async?

### ISSUE THREAD

**Issue by k0105** [facebook/fbthrift#156]
Hi,

since there is support for async in C++ - is there any way to get the same functionality for Lua? [And in the best case Java and Python as well.] Can sth. like LuaNode help similar to how asyncio is used in the Python tutorial?

Any hints would be highly appreciated. Thank you very much in advance.

Best wishes,
Joe

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
