### ISSUE TITLE
cpp1    cob client  core down    

### ISSUE THREAD

**Issue by yuzzjj** [facebook/fbthrift#157]
(gdb) bt
#0  0x0000003441232925 in raise () from /lib64/libc.so.6
#1  0x0000003441234105 in abort () from /lib64/libc.so.6
#2  0x00007f0e30f0be60 in apache::thrift::async::TStreamAsyncChannel<apache::thrift::async::detail::TUnframedACWriteRequest, apache::thrift::async::detail::TUnframedACReadState<apache::thrift::async::detail::THeaderACProtocolTraits> >::invokeReadCallback(std::function<void ()>, char const*) () from /export/servers/impala/lib_C/libthrift.so.32
#3  0x00007f0e30f0bbf7 in apache::thrift::async::TStreamAsyncChannel<apache::thrift::async::detail::TUnframedACWriteRequest, apache::thrift::async::detail::TUnframedACReadState<apache::thrift::async::detail::THeaderACProtocolTraits> >::processReadEOF() () from /export/servers/impala/lib_C/libthrift.so.32
#4  0x00007f0e30f0b0ce in apache::thrift::async::TStreamAsyncChannel<apache::thrift::async::detail::TUnframedACWriteRequest, apache::thrift::async::detail::TUnframedACReadState<apache::thrift::async::detail::THeaderACProtocolTraits> >::readEOF() () from /export/servers/impala/lib_C/libthrift.so.32
#5  0x00007f0e316a6988 in folly::AsyncSocket::handleRead (this=0x7f0bfdd87988) at io/async/AsyncSocket.cpp:1398
#6  0x00007f0e316a30fa in folly::AsyncSocket::ioReady (this=0x7f0bfdd87988, events=2) at io/async/AsyncSocket.cpp:1235
#7  0x00007f0e2f6fc6e6 in event_persist_closure (ev=<optimized out>, base=0x7f0bfdd87700) at event.c:1319
#8  event_process_active_single_queue (activeq=0x7f0bfd587af0, base=0x7f0bfdd87700) at event.c:1363
#9  event_process_active (base=<optimized out>) at event.c:1438
#10 event_base_loop (base=0x7f0bfdd87700, flags=1) at event.c:1639
#11 0x00007f0e316b6b60 in folly::EventBase::loopBody (this=0x7f0bfdae3600, flags=<optimized out>) at io/async/EventBase.cpp:342
#12 0x0000000001f2bcb5 in impala::AsyncClientConnectionimpala::ImpalaBackendClient::DoAsyncRpc<void (impala::AsyncImpalaInternalServiceCobClient::*)(std::function<void (impala::AsyncImpalaInternalServiceCobClient*)>, impala::TTransmitDataParams const&), impala::TTransmitDataParams, impala::SyncTransmitDataRpcStats, impala::TTransmitDataResult>(void (impala::AsyncImpalaInternalServiceCobClient::\* const&)(std::function<void (impala::AsyncImpalaInternalServiceCobClient*)>, impala::TTransmitDataParams const&), impala::TTransmitDataParams const&, impala::SyncTransmitDataRpcStats_, impala::TTransmitDataResult_) (

```
this=0x7f0c9dcb06f0, f=@0x7f0c9dcb0790: &virtual table offset 40, request=..., callback_obj=0x7f0c9dcb06d0, result=0x9efac40) at /export/ldb/Impala-cdh5.7-fbthrift/be/src/runtime/async-client-cache.h:244
```

function like this :   which running sometime  core down 

243      (client_->*f)(std::bind(
          &AsyncCallbackWrap::callback,callback_obj, std::placeholders::_1), request);
244      client_->GetEventBase()->loop();  
 245     *result = std::move(callback_obj->GetPromise()->get_future().get());

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.

**Comment by jhonsbro** [comment]
Ya facebook has outages issue as i looked and confirmed at https://webdownstatus.com/outages/facebook
