### ISSUE TITLE
build py compiler faild

### ISSUE THREAD

**Issue by linhuifj** [facebook/fbthrift#159]
[linhui@localhost thrift]$ make  -j 32
make  all-recursive
make[1]: Entering directory `/reserve/linhui/thpp/thpp/deps/fbthrift/thrift'
Making all in compiler
make[2]: Entering directory `/reserve/linhui/thpp/thpp/deps/fbthrift/thrift/compiler'
make  all-recursive
make[3]: Entering directory `/reserve/linhui/thpp/thpp/deps/fbthrift/thrift/compiler'
Making all in .
make[4]: Entering directory `/reserve/linhui/thpp/thpp/deps/fbthrift/thrift/compiler'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/reserve/linhui/thpp/thpp/deps/fbthrift/thrift/compiler'
Making all in py
make[4]: Entering directory `/reserve/linhui/thpp/thpp/deps/fbthrift/thrift/compiler/py'
/usr/bin/python setup.py build
running build
running build_py
copying ./frontend.so -> build/lib/thrift_compiler
mkdir -p ../../.python-local/lib/python
PYTHONPATH=../../.python-local/lib/python /usr/bin/python setup.py install --home=../../.python-local
running install
running bdist_egg
running egg_info
writing thrift_py.egg-info/PKG-INFO
writing top-level names to thrift_py.egg-info/top_level.txt
writing dependency_links to thrift_py.egg-info/dependency_links.txt
reading manifest file 'thrift_py.egg-info/SOURCES.txt'
writing manifest file 'thrift_py.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/thrift_compiler
copying build/lib/thrift_compiler/__init__.py -> build/bdist.linux-x86_64/egg/thrift_compiler
copying build/lib/thrift_compiler/main.py -> build/bdist.linux-x86_64/egg/thrift_compiler
copying build/lib/thrift_compiler/frontend.so -> build/bdist.linux-x86_64/egg/thrift_compiler
creating build/bdist.linux-x86_64/egg/thrift_compiler/generate
copying build/lib/thrift_compiler/generate/t_cpp_context.py -> build/bdist.linux-x86_64/egg/thrift_compiler/generate
copying build/lib/thrift_compiler/generate/t_cpp_generator.py -> build/bdist.linux-x86_64/egg/thrift_compiler/generate
copying build/lib/thrift_compiler/generate/t_output.py -> build/bdist.linux-x86_64/egg/thrift_compiler/generate
copying build/lib/thrift_compiler/generate/__init__.py -> build/bdist.linux-x86_64/egg/thrift_compiler/generate
copying build/lib/thrift_compiler/generate/t_output_aggregator.py -> build/bdist.linux-x86_64/egg/thrift_compiler/generate
copying build/lib/thrift_compiler/generate/t_generator.py -> build/bdist.linux-x86_64/egg/thrift_compiler/generate
byte-compiling build/bdist.linux-x86_64/egg/thrift_compiler/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/thrift_compiler/main.py to main.pyc
byte-compiling build/bdist.linux-x86_64/egg/thrift_compiler/generate/t_cpp_context.py to t_cpp_context.pyc
byte-compiling build/bdist.linux-x86_64/egg/thrift_compiler/generate/t_cpp_generator.py to t_cpp_generator.pyc
byte-compiling build/bdist.linux-x86_64/egg/thrift_compiler/generate/t_output.py to t_output.pyc
byte-compiling build/bdist.linux-x86_64/egg/thrift_compiler/generate/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/thrift_compiler/generate/t_output_aggregator.py to t_output_aggregator.pyc
byte-compiling build/bdist.linux-x86_64/egg/thrift_compiler/generate/t_generator.py to t_generator.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying thrift_py.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thrift_py.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thrift_py.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thrift_py.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thrift_py.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/thrift_py-0.9.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing thrift_py-0.9.0-py2.7.egg
removing '/reserve/linhui/thpp/thpp/deps/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg' (and everything under it)
creating /reserve/linhui/thpp/thpp/deps/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg
Extracting thrift_py-0.9.0-py2.7.egg to /reserve/linhui/thpp/thpp/deps/fbthrift/thrift/.python-local/lib/python
thrift-py 0.9.0 is already the active version in easy-install.pth

Installed /reserve/linhui/thpp/thpp/deps/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    run_setup()
  File "setup.py", line 36, in run_setup
    zip_safe = False,
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 701, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)
make[4]: *** [all-local] Error 1
make[4]: Leaving directory `/reserve/linhui/thpp/thpp/deps/fbthrift/thrift/compiler/py'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/reserve/linhui/thpp/thpp/deps/fbthrift/thrift/compiler'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/reserve/linhui/thpp/thpp/deps/fbthrift/thrift/compiler'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/reserve/linhui/thpp/thpp/deps/fbthrift/thrift'
make: *** [all] Error 2

**Comment by alandau** [comment]
What distribution and version are you running?
What's the version of gcc? (gcc -v)

**Comment by linhuifj** [comment]
I finally fixed this problem. My gcc version is 4.8, it's not anything about gcc. It's something wrong from python (from centos yum). When I downloaded python 2.7 and compile/installed it, things become OK.
