### ISSUE TITLE
Unable to install fbthrift due to folly in Ubuntu 14.04 (32 bit)

### ISSUE THREAD

**Issue by prakharnigam** [facebook/fbthrift#162]
make  all-recursive
make[1]: Entering directory `fbthrift/thrift/build/deps/folly/folly'
Making all in .
make[2]: Entering directory `fbthrift/thrift/build/deps/folly/folly'
depbase=`echo Bits.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT Bits.lo -MD -MP -MF $depbase.Tpo -c -o Bits.lo Bits.cpp &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT Bits.lo -MD -MP -MF .deps/Bits.Tpo -c Bits.cpp  -fPIC -DPIC -o .libs/Bits.o
In file included from Bits.cpp:19:0:
./../folly/CpuId.h: In function 'int (* {anonymous}::folly_popcount_ifunc())(unsigned int)':
./../folly/CpuId.h:49:62: error: PIC register clobbered by 'ebx' in 'asm'
     __asm__("cpuid" : "=a"(n) : "a"(0) : "ebx", "edx", "ecx");
                                                              ^
./../folly/CpuId.h:51:65: error: PIC register clobbered by 'ebx' in 'asm'
       __asm__("cpuid" : "=c"(f1c_), "=d"(f1d_) : "a"(1) : "ebx");
                                                                 ^
./../folly/CpuId.h: In function 'int (* {anonymous}::folly_popcountll_ifunc())(long long unsigned int)':
./../folly/CpuId.h:49:62: error: PIC register clobbered by 'ebx' in 'asm'
     __asm__("cpuid" : "=a"(n) : "a"(0) : "ebx", "edx", "ecx");
                                                              ^
./../folly/CpuId.h:51:65: error: PIC register clobbered by 'ebx' in 'asm'
       __asm__("cpuid" : "=c"(f1c_), "=d"(f1d_) : "a"(1) : "ebx");
                                                                 ^
make[2]: *** [Bits.lo] Error 1
make[2]: Leaving directory `fbthrift/thrift/build/deps/folly/folly'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/fbthrift/thrift/build/deps/folly/folly'
make: *** [all] Error 2

**Comment by alandau** [comment]
This is a compile error in a dependency (https://github.com/facebook/folly), you might want to ask there for help. However, as far as I know, folly only supports 64-bit systems.
