### ISSUE TITLE
localhost resolution error in Calculator tutorial

### ISSUE THREAD

**Issue by cauthu** [facebook/fbthrift#165]
Hi,
I'm using the cpp2 version of the Calculator tutorial at commit 2cd96470544a823878f357c8f1a18ab3b9e1260d and getting this error when starting the client:

```
me@utu1404vm ~/fbthrift/thrift/tutorial/cpp/basic > ./client 
terminate called after throwing an instance of 'std::system_error'
  what():  Failed to resolve address for "localhost": Name or service not known (error=-2): Unknown error -2
Aborted (core dumped)
me@utu1404vm ~/fbthrift/thrift/tutorial/cpp/basic >
```

After I change `CppClient.cpp` to use `"127.0.0.1`" instead of `"localhost"`, then it works:

```
me@utu1404vm ~/fbthrift/thrift/tutorial/cpp/basic > ./client 
ping()
1+1=2
.
.
.
```

I am running inside an Ubuntu 14.04 VM if that makes a difference.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
