### ISSUE TITLE
About the gen-cpp folder?

### ISSUE THREAD

**Issue by huahang** [facebook/fbthrift#17]
In the previous versions of the thrift compiler, there are options to control if a gen-\* folder will be created or not for the generated files. 

  -o dir      Set the output directory for gen-\* packages
               (default: current directory)
  -out dir    Set the ouput location for generated files.
               (no gen-\* folder will be created)

But it seems that this fbthrift compiler doesn't support the '-out dir' (no gen-\* folder) option?

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
