### ISSUE TITLE
fatal error: thrift/lib/cpp2/util/MapCopy.h: No such file or directory

### ISSUE THREAD

**Issue by byronwwang** [facebook/fbthrift#170]
When I compile fblualib, I got the error. So, I manually copy MapCopy.h to there. But I got new errors, like this
![qq 20160825123942](https://cloud.githubusercontent.com/assets/6510742/17957076/1b6d310a-6ac1-11e6-8ea2-ee46268da3da.png)

**Comment by lukenels** [comment]
Thanks for reporting this. I'm working on reproducing the error now and will try and see what's wrong.

**Comment by juchem** [comment]
I think this was caused by https://github.com/facebook/fbthrift/commit/e168ff6e4ed0653592de5bc2a48ad35e1a1dd61b

Probably missing from some Makefile

**Comment by juchem** [comment]
diffing out the fix...
