### ISSUE TITLE
Make failed in cpp2 (gen-cpp2/Sasl_types.h: Sasl.thrift)

### ISSUE THREAD

**Issue by windancer055** [facebook/fbthrift#178]
Making all in cpp2
PYTHONPATH=../../.python-local/lib/python $HOME/anaconda3/envs/py27/bin/python -mthrift_compiler.main --gen cpp2 Sasl.thrift
$HOME/anaconda3/envs/py27/bin/python: dlopen(/misc/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg/thrift_compiler/frontend.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /misc/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg/thrift_compiler/frontend.so
  Reason: image not found

Tried to add DYLD_LIBRARY_PATH and got a different error:

DYLD_LIBRARY_PATH=$HOME/anaconda3/envs/py27/lib PYTHONPATH=../../.python-local/lib/python $HOME/anaconda3/envs/py27/bin/python -mthrift_compiler.main --gen cpp2 Sasl.thrift
Double registration of singletons of the same underlying type; check for multiple definitions of type folly::Singleton<N5folly21ThreadWheelTimekeeperE>

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
