### ISSUE TITLE
Implement fbtrift as a thrift plugin

### ISSUE THREAD

**Issue by anatol** [facebook/fbthrift#187]
Code duplication is considered as a bad thing as it increases maintenance burden, makes harder to keep features implementation in coherence between 2 projects, adds headache on bug fixes cherry-picking.

Upstream thift project recently added possibility to have compiler extensions [1]. Using these extensions is a great possibility to avoid the code duplication between thrift and fbthrift.

Please implement fbtrift as a thrift compiler extension.

[1] https://github.com/apache/thrift/commit/11da87e6f30c237869a09e28ab44fe4a59db270e

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.

**Comment by anatol** [comment]
:(

**Comment by Orvid** [comment]
With this particular request, it's unlikely to happen as we've made a _lot_ of changes to internal APIs that simply don't work with upstream, so a compiler plugin alone isn't nearly enough to resolve the duplication :(
