### ISSUE TITLE
Which thread manager to use?

### ISSUE THREAD

**Issue by hrjaco** [facebook/fbthrift#188]
Hi, I am implementing a server using fbthrift. The server needs to do some CPU intensive work and I want to use the same thread pool for both the server and other work in our handler implementation.

From https://github.com/facebook/fbthrift/blob/master/thrift/lib/cpp/concurrency/ThreadManager.h, it seems I can either use newSimpleThreadManager() or use ThreadManagerExecutorAdapter() with https://github.com/facebook/wangle/blob/master/wangle/concurrent/CPUThreadPoolExecutor.h. From https://github.com/facebook/folly/blob/master/folly/futures/README.md#executor-implementations-, it seems to recommend the latter. Has anyone done any performance tests between these two?

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
