### ISSUE TITLE
lib/cpp2 compile error due to missing include "<gflags/gflags>" 

### ISSUE THREAD

**Issue by zlqhem** [facebook/fbthrift#189]
environment: ubuntu 14.04, GCC 4.8.4
source version: v0.24.0

reproduce steps: following instructions for [install Folly, fbthrift, thpp and fblualib](https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-folly-fbthrift-thpp-and-fblualib) 

1.  `curl -sk https://raw.githubusercontent.com/soumith/fblualib/master/install_all.sh | bash -e`
  Build fails. It seems to be the same issue with #146. 
2. So applied the changes from #147 manually after cloning fbthrift.
```
git clone -b v0.24.0 --depth 1 https://github.com/facebook/fbthrift
cd fbthrift/thrift/
// modify Krb5CredentialsCacheManager.cpp, KrbUtil.cpp, BinaryProtocol.h like #147
autoreconf -if && ./configure && make
```
The same compile error message appeared in #146 occurs in another file CompactProtocol.h

Below is the error message:
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I../../.. -pthread -I/usr/include -I../cpp -I../../../../gperftools-2.0.99/src -I/usr/local/include -std=gnu++0x -MT async/libthriftcpp2_la-HeaderServerChannel.lo -MD -MP -MF async/.deps/libthriftcpp2_la-HeaderServerChannel.Tpo -c async/HeaderServerChannel.cpp  -fPIC -DPIC -o async/.libs/libthriftcpp2_la-HeaderServerChannel.o
In file included from ../../../thrift/lib/cpp2/protocol/Serializer.h:24:0,
                 from async/HeaderServerChannel.cpp:21:
../../../thrift/lib/cpp2/protocol/CompactProtocol.h:28:14: error: expected constructor, destructor, or type conversion before '(' token
 DECLARE_int32(thrift_cpp2_protocol_reader_string_limit);
```

After inserting #include <gflags/gflags> in CompactProtocol.h, it works.

**Comment by juchem** [comment]
can you provide a pull request with your fix?

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
