### ISSUE TITLE
gdb unable to load debug symbols from the default generated build

### ISSUE THREAD

**Issue by eklavya1983** [facebook/fbthrift#190]
I compiled fbthrift with g++
g++ (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4

When I tried to load the resultant libthriftcpp2.so in gdb I am getting the following in gdb
"Reading symbols from libthriftcpp2.so...(no debugging symbols found)...done."

As a result whenever I have a backtrace in thrift code I am not getting line information.

My gdb version is
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1

I tried to running configure again as follows
./configure CXXFLAGS='-g -O2'

The resulting make VERBOSE=1 didn't show -g and -O2 as flags in the g++ command

libtool: compile:  g++ -DHAVE_CONFIG_H -I../../.. -pthread -I/usr/include -I/usr/local/include -Wall -std=gnu++1y -MT async/TEventTask.lo -MD -MP -MF async/.deps/TEventTask.Tpo -c async/TEventTask.cpp  -fPIC -DPIC -o async/.libs/TEventTask.o

My questions
1.  Why did setting  CXXFLAGS='-g -O2' didn't have any impact.  Am I doing something wrong?
2.  In thrift documentation at https://github.com/facebook/fbthrift/tree/master/thrift says by default debug symbols are included.  Is that not the case?

Any help is appreciated in resolving this matter.  Thanks.

**Comment by juchem** [comment]
I believe you have to prefix configure with the environment variables:

CXXFLAGS='-g -O2' ./configure

**Comment by eklavya1983** [comment]
Thanks for the response @juchem.  I tried providing it as env variable.  I am still seeing the same thing.  One of many from the make output
/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I../../..  -pthread -I/usr/include  -I../cpp -I../../../../gperftools-2.0.99/src -I/usr/local/include   -std=gnu++1y -MT server
/libthriftcpp2_la-BaseThriftServer.lo -MD -MP -MF server/.deps/libthriftcpp2_la-BaseThriftServer.Tpo -c -o server/libthriftcpp2_la-BaseThriftServer.lo `test -f 'server/BaseThriftServer.cpp' || echo './'
`server/BaseThriftServer.cpp

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
