### ISSUE TITLE
python path setting

### ISSUE THREAD

**Issue by maomaodog** [facebook/fbthrift#193]
Can't find out where cause this, python path lost the first '/'. I have try many ways to fix this but failed. Is there anyone have same problem ?
 
    You are attempting to install a package to a directory that is not
    on PYTHONPATH and which Python does not read ".pth" files from.  The
    installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:

          usr/local/lib/python2.7/dist-packages/

**Comment by chadparry** [comment]
Can you please show what your `configure` command arguments looked like? According to the error message, it's possible that the `install-dir` on the command-line wasn't valid.

**Comment by dragon28** [comment]
Have the same problem:

Installed /home/dragon/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg
Processing dependencies for thrift-py==0.9.0
Finished processing dependencies for thrift-py==0.9.0
make[4]: Entering directory '/home/dragon/fbthrift/thrift/compiler/py'
test -z "" || mkdir -p /lib/python
test -z "" || mkdir -p 
/usr/bin/python setup.py install --root= 
running install
Checking .pth file support in usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST FAILED: usr/local/lib/python2.7/dist-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    usr/local/lib/python2.7/dist-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
Makefile:762: recipe for target 'install-exec-am' failed
make[4]: *** [install-exec-am] Error 1
make[4]: Leaving directory '/home/dragon/fbthrift/thrift/compiler/py'
Makefile:642: recipe for target 'install-am' failed
make[3]: *** [install-am] Error 2
make[3]: Leaving directory '/home/dragon/fbthrift/thrift/compiler/py'
Makefile:952: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/dragon/fbthrift/thrift/compiler'
Makefile:1109: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/dragon/fbthrift/thrift/compiler'
Makefile:498: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

I have attached the log file for debugging purpose

Linux Version: Ubuntu 64Bits 16.0.4.1
Kernel Version: 4.4.0-53-generic
Python version: Python 2.7.12
PIP version: 9.0.1

[make_log.txt](https://github.com/facebook/fbthrift/files/659276/make_log.txt)

**Comment by ch0p1n** [comment]
temporary dirty workaround: add extra slash to PY_PREFIX e.g. `./configure PY_PREFIX=//usr/local `
There is a missing slash somewhere in build script as error indicates: 
`usr/local/lib/python2.7/dist-packages/`

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
