### ISSUE TITLE
thrift/lib/cpp/async/TAsyncSSLSocket.h:133:65: error: no matching function for call to ‘apache::thrift::async::TAsyncSSLSocket::sslConn(apache::thrift::async::TAsyncSSLSocket::HandshakeCallback*&, std::chrono::milliseconds, const folly::SSLContext::SSLVerifyPeerEnum&)’

### ISSUE THREAD

**Issue by dragon28** [facebook/fbthrift#195]
Hello People,

I found this error when I tried to make the fbthrif:

libtool: compile:  g++ -DHAVE_CONFIG_H -I../../.. -pthread -I/usr/include -I/usr/local/include -Wall -std=gnu++1y -MT async/TAsyncSSLSocketFactory.lo -MD -MP -MF async/.deps/TAsyncSSLSocketFactory.Tpo -c async/TAsyncSSLSocketFactory.cpp  -fPIC -DPIC -o async/.libs/TAsyncSSLSocketFactory.o
In file included from async/TAsyncSSLSocketFactory.cpp:19:0:
../../../thrift/lib/cpp/async/TAsyncSSLSocket.h: In member function ‘virtual void apache::thrift::async::TAsyncSSLSocket::sslConnect(apache::thrift::async::TAsyncSSLSocket::HandshakeCallback*, uint64_t, const folly::SSLContext::SSLVerifyPeerEnum&)’:
../../../thrift/lib/cpp/async/TAsyncSSLSocket.h:133:65: error: no matching function for call to ‘apache::thrift::async::TAsyncSSLSocket::sslConn(apache::thrift::async::TAsyncSSLSocket::HandshakeCallback*&, std::chrono::milliseconds, const folly::SSLContext::SSLVerifyPeerEnum&)’
         callback, std::chrono::milliseconds(timeout), verifyPeer);
                                                                 ^
In file included from ../../../thrift/lib/cpp/async/TAsyncSSLSocket.h:19:0,
                 from async/TAsyncSSLSocketFactory.cpp:19:
/usr/local/include/folly/io/async/AsyncSSLSocket.h:335:16: note: candidate: virtual void folly::AsyncSSLSocket::sslConn(folly::AsyncSSLSocket::HandshakeCB*, uint64_t, const folly::SSLContext::SSLVerifyPeerEnum&)
   virtual void sslConn(HandshakeCB *callback, uint64_t timeout = 0,
                ^
/usr/local/include/folly/io/async/AsyncSSLSocket.h:335:16: note:   no known conversion for argument 2 from ‘std::chrono::milliseconds {aka std::chrono::duration<long int, std::ratio<1l, 1000l> >}’ to ‘uint64_t {aka long unsigned int}’
Makefile:1014: recipe for target 'async/TAsyncSSLSocketFactory.lo' failed
make[4]: *** [async/TAsyncSSLSocketFactory.lo] Error 1
make[4]: Leaving directory '/home/dragon/fbthrift/thrift/lib/cpp'
Makefile:1286: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/dragon/fbthrift/thrift/lib/cpp'
Makefile:416: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/dragon/fbthrift/thrift/lib'
Makefile:498: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/dragon/fbthrift/thrift'
Makefile:430: recipe for target 'all' failed
make: *** [all] Error 2

Linux: Ubuntu 64 Bits 16.04.1
G++: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
make: GNU Make 4.1
pkg-config                                  0.29.1-0ubuntu1
autoconf                                    2.69-9
autotools-dev                               20150820.1
libssl-dev:amd64                            1.0.2g-1ubuntu4.5
libssl1.0.0:amd64                           1.0.2g-1ubuntu4.5

Thanks

**Comment by guoxiao** [comment]
I met the same problem, but it's gone after I upgrade `folly` to latest version (facebook/folly@e1a15f9).

**Comment by dragon28** [comment]
@guoxiao 

Thank man :+1:

**Comment by pansk** [comment]
I have the latest folly version, and it didn't help.
BTW, Travis CI is failing with the same error.

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I../../.. -pthread -I/usr/include -I/usr/local/include -Wall -std=gnu++1y -MT async/TAsyncSSLSocketFactory.lo -MD -MP -MF async/.deps/TAsyncSSLSocketFactory.Tpo -c async/TAsyncSSLSocketFactory.cpp  -fPIC -DPIC -o async/.libs/TAsyncSSLSocketFactory.o
In file included from async/TAsyncSSLSocketFactory.cpp:19:0:
../../../thrift/lib/cpp/async/TAsyncSSLSocket.h: In member function ‘virtual void apache::thrift::async::TAsyncSSLSocket::sslConnect(apache::thrift::async::TAsyncSSLSocket::HandshakeCallback*, uint64_t, const folly::SSLContext::SSLVerifyPeerEnum&)’:
../../../thrift/lib/cpp/async/TAsyncSSLSocket.h:133:65: error: no matching function for call to ‘apache::thrift::async::TAsyncSSLSocket::sslConn(apache::thrift::async::TAsyncSSLSocket::HandshakeCallback*&, std::chrono::milliseconds, const folly::SSLContext::SSLVerifyPeerEnum&)’
         callback, std::chrono::milliseconds(timeout), verifyPeer);
                                                                 ^
../../../thrift/lib/cpp/async/TAsyncSSLSocket.h:133:65: note: candidate is:
In file included from ../../../thrift/lib/cpp/async/TAsyncSSLSocket.h:19:0,
                 from async/TAsyncSSLSocketFactory.cpp:19:
/usr/local/include/folly/io/async/AsyncSSLSocket.h:335:16: note: virtual void folly::AsyncSSLSocket::sslConn(folly::AsyncSSLSocket::HandshakeCB*, uint64_t, const folly::SSLContext::SSLVerifyPeerEnum&)
   virtual void sslConn(HandshakeCB *callback, uint64_t timeout = 0,
                ^
/usr/local/include/folly/io/async/AsyncSSLSocket.h:335:16: note:   no known conversion for argument 2 from ‘std::chrono::milliseconds {aka std::chrono::duration<long int, std::ratio<1l, 1000l> >}’ to ‘uint64_t {aka long unsigned int}’
make[3]: *** [async/TAsyncSSLSocketFactory.lo] Error 1
make[3]: Leaving directory `/home/travis/build/facebook/fbthrift/thrift/lib/cpp'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/home/travis/build/facebook/fbthrift/thrift/lib/cpp'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/facebook/fbthrift/thrift/lib'
make: *** [install-recursive] Error 1
```

**Comment by eecrazy** [comment]
@pansk Have you found the solution?  I met the same error.

**Comment by pansk** [comment]
I found the solution, but didn't manage to reduce it to the minimum (took me about 10 hours of work to get through the whole process of having fb-caffe-exts working, for which compiling fbthrift was just one of the steps).
If I remember correctly, the solution was the same as @guoxiao: Upgrading folly (and recompiling all the other libraries that I compiled before arriving here) did the job.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
