### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by shimen** [facebook/fbthrift#196]
I am trying to install the fblualib, with the provided install_all.sh.
When the fbthrift is installed I get this error:
The same is here: https://travis-ci.org/facebook/fbthrift

libtool: compile:  g++ -DHAVE_CONFIG_H -I../../.. -pthread -I/usr/include -I/usr/local/include -Wall -std=gnu++1y -MT transport/TBufferTransports.lo -MD -MP -MF transport/.deps/TBufferTransports.Tpo -c transport/TBufferTransports.cpp -o transport/TBufferTransports.o >/dev/null 2>&1
depbase=`echo transport/THeader.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I../../..  -pthread -I/usr/include -I/usr/local/include  -Wall -std=gnu++1y -MT transport/THeader.lo -MD -MP -MF $depbase.Tpo -c -o transport/THeader.lo transport/THeader.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I../../.. -pthread -I/usr/include -I/usr/local/include -Wall -std=gnu++1y -MT transport/THeader.lo -MD -MP -MF transport/.deps/THeader.Tpo -c transport/THeader.cpp  -fPIC -DPIC -o transport/.libs/THeader.o
transport/THeader.cpp:38:18: fatal error: zstd.h: No such file or directory
compilation terminated.
Makefile:1014: recipe for target 'transport/THeader.lo' failed
make[4]: *** [transport/THeader.lo] Error 1
make[4]: Leaving directory '/tmp/fblualib/fbthrift/thrift/lib/cpp'
Makefile:1286: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/tmp/fblualib/fbthrift/thrift/lib/cpp'
Makefile:416: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/fblualib/fbthrift/thrift/lib'
Makefile:498: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/fblualib/fbthrift/thrift'
Makefile:430: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yaserkl** [comment]
same here, any updates?

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
