### ISSUE TITLE
can not generate golang codes

### ISSUE THREAD

**Issue by lygn128** [facebook/fbthrift#198]
if i run    "python -mthrift_compiler.main --gen cpp2 pred_service.thrift"  can generate the cpp codes
if i run     "thrift1 --gen py pred_service.thrift"   can generate the python codes;
if i run    "thrift1 --gen go pred_service.thrift"      generate nothing.

cant you help me solve the problem, thank you very much.

**Comment by eduardo-elizondo** [comment]
This should fix it. Please let me know if it's still failing to generate code.
