### ISSUE TITLE
how to reuse AsyncClient in fbthrift

### ISSUE THREAD

**Issue by 3in** [facebook/fbthrift#199]
`
EventBase eb;

auto channel = HeaderClientChannel::newChannel(async::TAsyncSocket::newSocket(
          &eb, {"127.0.0.1", 9090}));
auto client = std::make_shared\<CalculatorAsyncClient\>(std::move(channel));
try {
client->sync_add(1,1);
} catch(TException &tx) {
...
}
`

when sync_add timeout，we can catch exceptions，but how can I reuse client object in the next rpc call？The client can connect & close in each call?

in apache thrift，we just call transport.open()  before client.add(1,1) to  reuse client object， call transport.close() to close the socket.

how to realize the goal in fbthrift async client?
thank you.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
