### ISSUE TITLE
NumaThreadManager.h not inside the include header folder

### ISSUE THREAD

**Issue by hrjaco** [facebook/fbthrift#200]
I was trying to use NumaThreadManager but noticed NumaThreadManager.h is not inside the include header folder. Any specific reason why NumaThreadManager is not included here https://github.com/facebook/fbthrift/blob/master/thrift/lib/cpp/Makefile.am?

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
