### ISSUE TITLE
configure error:   checking whether compiling and linking against folly works... no

### ISSUE THREAD

**Issue by eecrazy** [facebook/fbthrift#201]
please help!

my configure command:     

./configure --prefix=/users1/zyli/.local --with-folly=/users1/zyli/.local/folly  --with-openssl=/users1/zyli/.local/openssl --with-libevent=--with-openssl=/users1/zyli/.local/

error content in config.log:  

configure:18958: checking for folly/folly-config.h in /users1/zyli/.local/folly
configure:18963: result: yes
configure:18974: checking whether compiling and linking against folly works
configure:19007: g++ -o conftest -std=gnu++1y -I/users1/zyli/.local/folly/include   -L/users1/zyli/.local/folly/lib conftest.cpp -lfolly -lssl -lcrypto  >&5
/usr/bin/ld: warning: libcrypto.so.10, needed by /users1/zyli/.local/lib/libevent-2.1.so.6, may conflict with libcrypto.so.1.1
/users1/zyli/.local/folly/lib/libfolly.so: undefined reference to `SSL_get_ex_new_index'
/users1/zyli/.local/folly/lib/libfolly.so: undefined reference to `SSLv23_method'
/users1/zyli/.local/folly/lib/libfolly.so: undefined reference to `SSL_load_error_strings'
/users1/zyli/.local/folly/lib/libfolly.so: undefined reference to `SSL_library_init'
/users1/zyli/.local/folly/lib/libfolly.so: undefined reference to `SSLv23_server_method'
collect2: error: ld returned 1 exit status
configure:19007: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "thrift"
| #define PACKAGE_TARNAME "thrift"
| #define PACKAGE_VERSION "32.0"
| #define PACKAGE_STRING "thrift 32.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "thrift"
| #define VERSION "32.0"
| #define HAVE_PYTHON "2.7"
| #define HAVE_STDCXX_0X /**/
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define YYTEXT_POINTER 1
| #define HAVE_BOOST /**/
| #define HAVE_BOOST_FILESYSTEM /**/
| #define HAVE_BOOST_PYTHON /**/
| #define HAVE_BOOST_SYSTEM /**/
| /* end confdefs.h.  */
| 
|                     #include <folly/String.h>
|                     #include <cerrno>
| 
| int
| main ()
| {
| 
|                     folly::errnoStr(ENOENT);
|                     return 0;
| 
|   ;
|   return 0;
| }
configure:19015: result: no
configure:19035: Unable to find the folly library.
configure:19037: error: Please install the folly library

**Comment by eecrazy** [comment]
I have add the  -lssl -lcrypto  flag, but still got   libfolly.so: undefined reference to SSL_get_ex_new_index'

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
