### ISSUE TITLE
[java] THeaderTransport write incorrect length for strings

### ISSUE THREAD

**Issue by dain** [facebook/fbthrift#202]
[THeaderTransport. writeString](https://github.com/facebook/fbthrift/blob/master/thrift/lib/java/thrift/src/main/java/com/facebook/thrift/transport/THeaderTransport.java#L383) has the following code:
```java
  private void writeString(ByteBuffer out, String str) {
    writeVarint(out, str.length());
    out.put(ByteBuffer.wrap(str.getBytes(Charset.forName("UTF-8"))));
  }
```
The problem is `str.length()` in Java returns the count of UTF-16 characters but the reader expect it to be the number of UTF-8 bytes.  Either this should be:
```
    private void writeString(ByteBuffer out, String string) {
        byte[] bytes = string.getBytes(StandardCharsets.UTF_8);
        writeVarint(out, bytes.length);
        out.put(bytes);
    }
```
or
```
    private void writeString(ByteBuffer out, String string) {
        checkArgument(CharMatcher.ASCII.matchesAllOf(string))
        byte[] bytes = string.getBytes(StandardCharsets.US_ASCII);
        writeVarint(out, bytes.length);
        out.put(bytes);
    }
```

Also this code should use `StandardCharsets` instead of `Charset.forName` and there is no need to call `ByteBuffer.wrap` since `ByteBuffer.put` takes a `byte[]` directly.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
