### ISSUE TITLE
link error: undefined reference to `_ZN5mstch6renderERKSsRKN5boost7variantINS2...

### ISSUE THREAD

**Issue by lebinhe** [facebook/fbthrift#205]
./configure success but when i make the fbthrift, I get this error: 

make  all-recursive
make[1]: Entering directory `/data/offline/anaconda2/3rd/fbthrift/thrift'
Making all in compiler
make[2]: Entering directory `/data/offline/anaconda2/3rd/fbthrift/thrift/compiler'
make  all-recursive
make[3]: Entering directory `/data/offline/anaconda2/3rd/fbthrift/thrift/compiler'
Making all in .
make[4]: Entering directory `/data/offline/anaconda2/3rd/fbthrift/thrift/compiler'
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -std=gnu++1y -lcrypto -lglog -lmstch -lboost_filesystem -lboost_system -L/data/offline/anaconda2/3rd/gflags/lib -L/data/offline/anaconda2/3rd/glog/lib -L/data/offline/anaconda2/3rd/double-conversion/double-conversion -L/data/offline/anaconda2/3rd/folly/lib -L/data/offline/anaconda2/3rd/mstch/lib -L/data/offline/anaconda2/3rd/snappy/lib -L/data/offline/anaconda2/3rd/wangle/lib -L/data/offline/anaconda2/3rd/folly/lib -o thrift1 main.o generate/common.o generate/t_generator.o generate/t_concat_generator.o generate/t_mstch_generator.o generate/t_android_lite_generator.o generate/t_cocoa_generator.o generate/t_cpp_generator.o generate/t_csharp_generator.o generate/t_d_generator.o generate/t_erl_generator.o generate/t_go_generator.o generate/t_hack_generator.o generate/t_hs_generator.o generate/t_html_generator.o generate/t_java_generator.o generate/t_js_generator.o generate/t_mstch_py3_generator.o generate/t_mstch_swift_generator.o generate/t_ocaml_generator.o generate/t_perl_generator.o generate/t_php_generator.o generate/t_py_generator.o generate/t_rb_generator.o generate/t_st_generator.o generate/t_xsd_generator.o -lfl libparse.la libthriftcompilerbase.la 
libtool: link: g++ -std=gnu++1y -o thrift1 main.o generate/common.o generate/t_generator.o generate/t_concat_generator.o generate/t_mstch_generator.o generate/t_android_lite_generator.o generate/t_cocoa_generator.o generate/t_cpp_generator.o generate/t_csharp_generator.o generate/t_d_generator.o generate/t_erl_generator.o generate/t_go_generator.o generate/t_hack_generator.o generate/t_hs_generator.o generate/t_html_generator.o generate/t_java_generator.o generate/t_js_generator.o generate/t_mstch_py3_generator.o generate/t_mstch_swift_generator.o generate/t_ocaml_generator.o generate/t_perl_generator.o generate/t_php_generator.o generate/t_py_generator.o generate/t_rb_generator.o generate/t_st_generator.o generate/t_xsd_generator.o  /data/offline/anaconda2/3rd/glog/lib/libglog.so -lpthread -lmstch -L/data/offline/anaconda2/3rd/gflags/lib -L/data/offline/anaconda2/3rd/glog/lib -L/data/offline/anaconda2/3rd/double-conversion/double-conversion -L/data/offline/anaconda2/3rd/folly/lib -L/data/offline/anaconda2/3rd/mstch/lib -L/data/offline/anaconda2/3rd/snappy/lib -L/data/offline/anaconda2/3rd/wangle/lib -lfl ./.libs/libparse.a -L/usr/lib64 ./.libs/libthriftcompilerbase.a -lcrypto -lboost_filesystem -lboost_system -Wl,-rpath -Wl,/data/offline/anaconda2/3rd/glog/lib -Wl,-rpath -Wl,/data/offline/anaconda2/3rd/glog/lib
generate/t_mstch_generator.o: In function `_ZNK17t_mstch_generator6renderERKSsRKN5boost7variantINS2_6detail7variant14recursive_flagIDnEESsidbN5mstch8internal8lambda_tINS2_18recursive_variant_EEESt10shared_ptrINSA_8object_tISC_EEESt3mapIS0_SC_St4lessIS0_ESaISt4pairIS0_SC_EEESt6vectorISC_SaISC_EENS5_5void_ESS_SS_SS_SS_SS_SS_SS_SS_SS_SS_EE':
/data/offline/anaconda2/3rd/fbthrift/thrift/compiler/generate/t_mstch_generator.cc:484: undefined reference to `_ZN5mstch6renderERKSsRKN5boost7variantINS2_6detail7variant14recursive_flagIDnEESsidbNS_8internal8lambda_tINS2_18recursive_variant_EEESt10shared_ptrINS9_8object_tISB_EEESt3mapIS0_SB_St4lessIS0_ESaISt4pairIS0_SB_EEESt6vectorISB_SaISB_EENS5_5void_ESR_SR_SR_SR_SR_SR_SR_SR_SR_SR_EERKSH_ISsSsSI_ISsESaISK_IS0_SsEEE'
collect2: error: ld returned 1 exit status
make[4]: *** [thrift1] Error 1
make[4]: Leaving directory `/data/offline/anaconda2/3rd/fbthrift/thrift/compiler'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/data/offline/anaconda2/3rd/fbthrift/thrift/compiler'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/data/offline/anaconda2/3rd/fbthrift/thrift/compiler'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/offline/anaconda2/3rd/fbthrift/thrift'
make: *** [all] Error 2

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
