### ISSUE TITLE
[fbthrift - cpp] Very high round-trip latency for requests

### ISSUE THREAD

**Issue by prasad-joshi** [facebook/fbthrift#207]
Although fbthrif is designed to give high performance we wanted to get preliminary validation of this claim before investing completely on this framework. To validate this we are pushing the framework to see what kind of latencies and throughputs it can deliver.

Our initial experiments with fbthrift gave very high latency (900 micro sec) for a simple roundtrip between two server. That is when we decided figure out what was going wrong and why we were getting such high latencies.

We did 3 additional experiments to measure latency (single threaded, 4k) to cross check against hardware and other frameworks.

- folly async sockets without any framework. If we get good numbers from this we know that the hardware and the OS stack is not the problem.

- wangle, without the thrift

- thrift:golang

We observed following latencies for 4k single threaded request/response

```
folly async sockets  50 usecs
thrift+golang        101 usecs
wangle               138 usecs
fbthrift             900 usecs
```

Benchmark code is committed here https://github.com/prasad-joshi/thrift-bench

We suspect something is wrong in the thrift part of fbthrift, the wangle part seems to be fine. Our suspicion is that it is either a compilation or tuneable which is set incorrectly. Please guide.

**Comment by prasad-joshi** [comment]
An update, if someone is reading :)

We tried running all the benchmarks on same machine, where client and server are just a different processes.

```
folly async sockets 21
wangle              100
fbthrift            368
apache thrift       31
```

Even in this benchmark latencies observed in fbthrift are much higher than expected. Simple Synchronous Apache Thrift server gives much better latencies.

**Comment by roticv** [comment]
Can you explain more about your set up for the different scenarios (Code will definitely be preferred)? It is because you might have test code that resulted in inefficiency (i.e. you are not using ThriftServer etc). Furthermore, it is important to note that fbthrift is not designed for low latency, but instead scalability and high throughput. From your description, it is difficult to pinpoint what is the exact issue at hand.

A example of features for scalability is async_tm* or future_* handlers are executed on worker threads instead of io threads so that we can accept the connections as soon as possible so that unaccepted connections will not queue. Another example is that the server has internal timeout to kill requests if it takes too long.

**Comment by prasad-joshi** [comment]
Thanks a lot for your response. All the code benchmarking code is committed here https://github.com/prasad-joshi/thrift-bench.

Here is explanation of setup in which we would like to use fbthrift. Client (either spark, mongo etc) sends ingest and/or query requests to DB server. The DB server might parse data and/or maintain indexes. DB server then forwards the request to DICTIONARY hashing server - which may modify data. DICT server forwards the request to LEAF server to store data on persistent storage. The DB, DICT, LEAF servers are written in C++. Therefore, we would definitely need something like thrift for communication between client and DB server. The DB, DICT, and LEAF servers can communication using either fbthrift or wangle. BTW, our usage is latency as well as throughput sensitive. Before committing to either fbthrift, thrift, or wangle. We would like to benchmark each of the framework.

Our benchmarking thrift file looks like this 
```
namespace cpp example
struct BenchmarkData {
	1: i64 request_id; /* ever increasing ID */
	/* latency calculations */
	2: i64 client_latency;
	3: i64 db_latency;
	4: i64 dict_latency;
	5: i64 leaf_latency;
	6: i64 io_latency;
	/* flags to bypass nodes */
	7:  bool bypass_dict;
	8:  bool bypass_cpu;
	9:  bool bypass_leaf;
	10: bool bypass_io;
	/* payload management */
	11: string data;
	12: i64    data_size;
	13: bool   empty_data_on_resp;
}
service Benchmark {
	BenchmarkData key_put(1: string key, 2: BenchmarkData bd);
	BenchmarkData key_get(1: string key, 2: BenchmarkData bd);
}
```

The DB server's main looks like this 
```
FILE: https://github.com/prasad-joshi/thrift-bench/blob/master/fbthrift/GaneshaDBServer.cpp
int main(int argc, char **argv) {
	folly::init(&argc, &argv, true);

	auto handler = make_shared<BenchmarkHandler>();
	auto server = make_shared<ThriftServer>();
	server->setInterface(handler);
	server->setPort(FLAGS_server_port);

	printf("Starting the server...\n");
	server->serve();
	printf("Done\n");

	return 0;
}
```
We tried synchronous as well as async version to handle requests. The code looks like this 

```
void async_tm_key_put(unique_ptr<HandlerCallback<unique_ptr<BenchmarkData>>> callback, unique_ptr<string> key, unique_ptr<BenchmarkData> bench) {
	auto s = std::chrono::high_resolution_clock::now();

	BenchmarkData _ret;
	copy_benchmark_data(_ret, bench);
	_ret.data.clear();
	_ret.data_size = 0;

	auto e = std::chrono::high_resolution_clock::now();
	auto l = std::chrono::duration_cast<std::chrono::nanoseconds>(e-s).count();
	_ret.set_db_latency(l);
	callback->result(_ret);
}
```

We tried synchronous as well as asyn client -- code available here FILE: https://github.com/prasad-joshi/thrift-bench/blob/master/fbthrift/client.cpp

When we run above client on server on same machine. Average latency reported is around 300 mirco seconds for each request. Readme.md here explains all the results https://github.com/prasad-joshi/thrift-bench

A very simple apache thrift synchronous client and server however, reports much much less latencies -- around 30 microseconds per request. The thrift benchmarking code is here https://github.com/prasad-joshi/thrift-bench/tree/master/thrift

Initially I thought fbthrift is compiled with symbol debugging on. Therefore, I wanted to compile fbthrift with debuggin turned off. However, neither `./configure CFLAGS='-O2' `nor `make CFLAGS='-O2'` works. fbthrift does not compile with `make CFLAGS='-O2'`.

I hope this gives enough context as to what we are trying to measure.

Thanks a lot for your time.

**Comment by eduardo-elizondo** [comment]
So is the issue about optimization flags? I just release a cmake build. You can try compiling with that and adding -O3.

**Comment by eduardo-elizondo** [comment]
Closing. Please reopen if this persists.
