### ISSUE TITLE
Installation error on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by nico00** [facebook/fbthrift#208]
Installing fbthrift on Ubuntu Server 16.04.2 I'm getting the following error:

In file included from async/HTTPClientChannel.cpp:17:0:
../../../thrift/lib/cpp2/async/HTTPClientChannel.h:27:45: fatal error: proxygen/lib/http/HTTPConnector.h: No such file or directory
compilation terminated.
Makefile:1326: recipe for target 'async/libthriftcpp2_la-HTTPClientChannel.lo' failed
make[5]: *** [async/libthriftcpp2_la-HTTPClientChannel.lo] Error 1
make[5]: Leaving directory '/tmp/fbthrift/thrift/lib/cpp2'
Makefile:1880: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/tmp/fbthrift/thrift/lib/cpp2'
Makefile:804: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/tmp/fbthrift/thrift/lib/cpp2'
Makefile:416: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/fbthrift/thrift/lib'
Makefile:498: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/fbthrift/thrift'
Makefile:430: recipe for target 'all' failed
make: *** [all] Error 2

Any idea?
Thanks
Nico

**Comment by kochie** [comment]
I'm getting the same thing, and it looks like the CI is failing as well [link](https://travis-ci.org/facebook/fbthrift/builds/213273776)

**Comment by nico00** [comment]
Good point. I've solved with `git checkout 314ae43 `

**Comment by eduardo-elizondo** [comment]
Thrift now supports cmake. Go to the main directory and read the CMakeLists.txt for dependencies. Docs will be coming soon. 
For now build by doing:
cmake .
make
If you are using MacOSX you need to specify:
cmake -DOPENSSL_ROOT_DIR=path/to/openssl .
make
