### ISSUE TITLE
thrift1 to thrift2 chaining doesn't work on OSS build

### ISSUE THREAD

**Issue by mehDsn** [facebook/fbthrift#21]
Hi

I was able to build fbthrift on centos. It added "thrift1" binary. Now when I try to generate cpp code for a simple service it does not generate async_ interface that I want. Is there any option that I need to give it?

**Comment by joan2015** [comment]
does thrift1 accepte -gen cpp2 option now? I can't find any tutorial or examples about cpp2

**Comment by senior7515** [comment]
@joan2015 the `python -m .. main..`  works. As far as the tutorials are concerned, i would just see the tests that it has. A lot of the impl's are backed by facebook folly lib which is better documented and has extensive tests.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by spershin** [comment]
Wow, it is 2016 and fbthrift binary STILL cannot generate cpp2 code.
Good support guys, good support. :(

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
