### ISSUE TITLE
100% CPU on some IOThreadPool threads

### ISSUE THREAD

**Issue by newpoo** [facebook/fbthrift#211]
We are using TM ThriftServer. Sometimes, some IOThreads get stuck in libevent and keep consuming 100% CPU. I did some google search, it seems to be a libevent/epoll bug ( https://www.google.com/search?q=libevent+high+cpu+fbthrift&oq=libevent+high&aqs=chrome.0.69i59l2j69i57j0l2j69i60.4555j0j1&sourceid=chrome&ie=UTF-8#q=libevent+high+cpu ).

Has anyone seen the similar issue before?

**Comment by eduardo-elizondo** [comment]
How can you repro?

**Comment by eduardo-elizondo** [comment]
Closing. Please reopen if this persists.
