### ISSUE TITLE
error "TCompactProtocol currently only works if a signed right shift is arithmetic"

### ISSUE THREAD

**Issue by shudaxia** [facebook/fbthrift#213]
**when I try to make the source code, there comes the problem:**

In file included from ../../../thrift/lib/cpp/protocol/TCompactProtocol.h:350:0,
                 from ../../../thrift/lib/cpp/transport/THeader.h:23,
                 from ../../../thrift/lib/cpp/server/TConnectionContext.h:25,
                 from ../../../thrift/lib/cpp/EventHandlerBase.h:26,
                 from ../../../thrift/lib/cpp/TProcessor.h:25,
                 from EventHandlerBase.cpp:17:
../../../thrift/lib/cpp/protocol/TCompactProtocol.tcc:37:3: error: #error "TCompactProtocol currently only works if a signed right shift is arithmetic"
  error "TCompactProtocol currently only works if a signed right shift is arithmetic"
   ^
In file included from ../../../thrift/lib/cpp/protocol/TCompactProtocol.h:350:0,
                 from ../../../thrift/lib/cpp/transport/THeader.h:23,
                 from ../../../thrift/lib/cpp/server/TConnectionContext.h:25,
                 from ../../../thrift/lib/cpp/EventHandlerBase.h:26,
                 from ../../../thrift/lib/cpp/TProcessor.h:25,
                 from ../../../thrift/lib/cpp/transport/TFileTransport.h:25,
                 from transport/TFileTransport.cpp:20:
../../../thrift/lib/cpp/protocol/TCompactProtocol.tcc:37:3: error: #error "TCompactProtocol currently only works if a signed right shift is arithmetic"
  error "TCompactProtocol currently only works if a signed right shift is arithmetic"
   ^
In file included from ../../../thrift/lib/cpp/protocol/TCompactProtocol.h:350:0,
                 from ../../../thrift/lib/cpp/transport/THeader.h:23,
                 from ../../../thrift/lib/cpp/server/TConnectionContext.h:25,
                 from ../../../thrift/lib/cpp/EventHandlerBase.h:26,
                 from ../../../thrift/lib/cpp/TProcessor.h:25,
                 from ../../../thrift/lib/cpp/processor/TMultiplexedProcessor.h:25,
                 from protocol/TMultiplexedProtocol.cpp:21:
../../../thrift/lib/cpp/protocol/TCompactProtocol.tcc:37:3: error: #error "TCompactProtocol currently only works if a signed right shift is arithmetic"
  error "TCompactProtocol currently only works if a signed right shift is arithmetic"
   ^

**the source code 'TCompactProtocol.tcc' shows like:**
![image](https://cloud.githubusercontent.com/assets/6365413/26184794/81b3551a-3bb9-11e7-9455-625a6f5cedbd.png)

**when I excute './configure', it shows:**
checking the behavior of a signed right shift... unknown

**so I don't know how to figure out it, hope for your answer, thank you very much.
my fbthrift version is 0.19.0, operating system version is CentOS 6 in x86_64.**

**Comment by ray-pixar** [comment]
I have the exact error. 
MinGW, GCC 5.4, Windows 10

**Comment by eduardo-elizondo** [comment]
Thrift now supports cmake. Go to the main directory and read the CMakeLists.txt for dependencies and build by doing:
cmake .
make
If you are using MacOSX you need to specify:
cmake -DOPENSSL_ROOT_DIR=path/to/openssl .
make
