### ISSUE TITLE
fbthrift folly/folly/stats/test won't build on Ubuntu 14.04

### ISSUE THREAD

**Issue by austinpagan** [facebook/fbthrift#216]
We installed Ubuntu 14.04.
We want to install fbthrift there.
We did the git clone of fbthrift.
We then did a git checkout of version v2017.06.05.00.
We followed the guidance in README.md, and ran the script called ./build/deps_ubuntu_14.04.sh
It dies trying to build fbthrift/thrift/build/deps/folly/folly/stats/test saying "*** No rule to make target 'all'. Stop."
It just finished successfully building in .../folly/folly/io/test.
Interestingly, io/test has a Makefile.am, a Makefile.in, and a Makefile. stats/test only has a Makefile.am.
I don't know where in this automated script the "autoconf" and "automake" steps were supposed to be executed on stats/test.
Help?

**Comment by SergeyMakarenko** [comment]
I believe there was a temporary issue with folly library which is one of our internal dependencies which was fixed.
Rerunning build for fbthrift on Travis CI marked build as successful and it is successful now (https://travis-ci.org/facebook/fbthrift/builds).
Could you please rerun your build (including step which executes ./build/deps_ubuntu_14.04.sh)?

**Comment by austinpagan** [comment]
Thank you for your quick reply. I didn't know whether you wanted me to just do a raw clone to get the very latest, or whether it was OK to repeat our "git checkout" of v2017.06.05.00.
I guessed the former.  
It's running now (both on our ubuntu 14 and our ubuntu 17 machines).
I'll advise shortly what the outcome is...
(thanks again!)

**Comment by austinpagan** [comment]
**Results on our ubuntu 14 machine:**


make[1]: Leaving directory `/home/netsres/fbthrift/thrift/build/deps/folly/folly/stats/test'
+ sudo ldconfig
+ popd
~/fbthrift/thrift/build/deps
+ install_mstch ubuntu_14.04
+ pushd .
~/fbthrift/thrift/build/deps ~/fbthrift/thrift/build/deps
+ [[ ! -e mstch ]]
+ git clone https://github.com/no1msd/mstch
Cloning into 'mstch'...
+ cd mstch
+ cmake .
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.0.2 or higher is required.  You are running version 2.8.12.2


**Results on our ubuntu 17 machine:**


Scanning dependencies of target FilePollerTest
[ 40%] Building CXX object CMakeFiles/FilePollerTest.dir/util/test/FilePollerTest.cpp.o
[ 41%] Building CXX object CMakeFiles/FilePollerTest.dir/test/TestMain.cpp.o
[ 42%] Linking CXX executable bin/FilePollerTest
/usr/local/lib/libfolly.so: undefined reference to `boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
/usr/local/lib/libfolly.so: undefined reference to `boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
collect2: error: ld returned 1 exit status
CMakeFiles/FilePollerTest.dir/build.make:141: recipe for target 'bin/FilePollerTest' failed
make[2]: *** [bin/FilePollerTest] Error 1


Please note: we are most interested in just getting up and running on ubuntu 14, but if you can also give us some guidance on how we should change the script to get ubuntu 17 to work as well, that would be awesome.

**Comment by austinpagan** [comment]
Don't know if you get notified (I'm guessing you do), but I have replied 
to your most welcome commentary on the fbthrift page.
(I've now gotten further, but there are more problems)

Gordon C. Fossum
Advisory Engineer, Computational Science
IBM T. J. Watson Research Center
Phone: 1-512-286-6200 (T/L: 363-6200)

**Comment by SergeyMakarenko** [comment]
I think you need to install more recent version of CMake on your ubuntu 14.
I'm not sure what problem is for Ubuntu 17.
I think we have outdated scripts for Ubuntu 12 and 14. We are actually testing this on Ubuntu 16 just using scripts for Ubuntu 14.
I guess we should remove scripts for older versions and just have one setup/build script for Ubuntu 16.
Also you could have a look at https://github.com/facebook/fbthrift/tree/master/thrift/build/docker and try to follow instructions on that page. Using Docker could provide more repeatable build and typically that is what I'm testing with.
To provide some broader context: we are not using neither Ubuntu nor Docker inside Facebook so unfortunately it makes it a little more complicated to have robust and reproducible build outside internal build system.

**Comment by austinpagan** [comment]
I will get a newer CMake, and continue looking at ubuntu 14.
If you get something that seems to build clean on ubuntu 16, let us know, as we'd be happy to try that.
Just FYI, we would REALLY like to have a version that builds on Centos (or RHEL), but we've run into just TOO MANY PROBLEMS there...  *sigh*

**Comment by SergeyMakarenko** [comment]
Thrift has a lot of dependencies so it could be difficult to build it in new environment. However I expect our scripts (originally designed for Ubuntu 14) should work without issues on Ubuntu 16. At least we test them on Ubuntu 16.

**Comment by austinpagan** [comment]
Can you recommend which branch or tag of "cmake" I should pull for installation on ubuntu 14?
(The latest prebuilt package available is 2.8.12.2, which is apparently not new enough)

**Comment by austinpagan** [comment]
Never mind...  we'll try v3.8.1 of cmake, and hope for the best!

**Comment by austinpagan** [comment]
The script finished just fine on ubuntu 14.  Next step was "autoreconf -if".
It appeared to finish, but it issued a warning:

lib/cpp2/Makefile.am:116: warning: variable 'thrift2include_fatal_SOURCES' is defined but no program or library has 'thrift2include_fatal' as canonical name (possible typo)

Should we be concerned, or shall we press on to the "./configure" step?

**Comment by SergeyMakarenko** [comment]
You should be safe to proceed and ignore that warning.
We have in plans to migrate to CMake completely but I can not give exact time for that.

**Comment by austinpagan** [comment]
Thank you!  the ./configure worked, and the "make" worked, and then I guessed that a "sudo make install" would be a good idea, and that also worked (or at least appeared to).

We're particularly interested in an easy tutorial on using fbthrift to implement RPCs with asynchronous clients.  I can see in the tutorial directory, under cpp, under async, we have two samples: "sort" and "fetcher".  Could I have your opinion on which is the more elementary sample?

**Comment by austinpagan** [comment]
I looked in fbthrift/thrift/test/cpp, and found a makefile.
So, I tried "make -f thrift-test.mk".
It complained that it couldn't find ../../compiler/cpp/thrift.
Indeed, while there was a compiler directory, there was no cpp subdirectory there.
I then went to look in /usr/local/bin, and found "thrift1", but no "thrift."
I'm now eager to compile and run a sample.  Can you point me in the right direction?

**Comment by SergeyMakarenko** [comment]
I'm afraid existing Makefiles were not updated to include tests or examples. You could also look at thrift/lib/cpp2/test but you probably will need to figure out how to build them yourself.

**Comment by austinpagan** [comment]
OK...  I found an example online that looked very promising, at this web page:
http://www.avabodh.com/thrift/intro.html
I followed the instructions to the letter through the part where it asked me to compile the server.
At that point, I needed to change "-std=c++11" to "-std=c++14" to avoid a zillion error messages.
Only two complaints remained, and I wonder if I should close this and open a new problem for it?

The compile line, and the errors generated look like this:

    ~/thrift.example$ g++ -o server server.cpp gen-cpp2/Calculator.cpp gen-cpp2/calculator_constants.cpp gen-cpp2/calculator_types.cpp -std=c++14 -I gen-cpp -lboost_system -lpthread -lglog -lfolly -lthrift -lthriftcpp2 
    /usr/bin/ld: /tmp/ccJ30Cag.o: undefined reference to symbol '_ZN3fLI46FLAGS_thrift_cpp2_protocol_reader_string_limitE'
    //usr/local/lib/libthriftprotocol.so.32: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
    ~/thrift.example$

**Comment by austinpagan** [comment]
As my current problems are no longer about building fbthrift, but about building applications using fbthrift, I am closing this issue, and if I can find a better example of my current problems, I'll open a new one.  Thanks for the assistance!
