### ISSUE TITLE
Installed "fbthrift" and typed "thrift".  It's not found.

### ISSUE THREAD

**Issue by austinpagan** [facebook/fbthrift#217]
We installed Ubuntu 14.04 on a target machine.
We installed fbthrift there, using the "build" script for Ubuntu 14.04 that is provided.
When we type "thrift" it says 
    The program 'thrift' is currently not installed. You can install it by typing:
    sudo apt-get install thrift-compiler.
We do see that there's a "thrift1" in /usr/local/bin.
Are we supposed to type "thrift1" instead of "thrift"?

**Comment by eduardo-elizondo** [comment]
Due to legacy reasons. We are working on fixing this.
