### ISSUE TITLE
Trouble installing fbthrift - folly issues

### ISSUE THREAD

**Issue by z3ppj1g5aw** [facebook/fbthrift#228]
Hi,

I installed folly and the library files are in /usr/local/lib. When I tried to install fbthrift using ./configure, I'm getting the following error:

checking for folly/folly-config.h in /usr/local... yes
checking whether compiling and linking against folly works... no
configure: Unable to find the folly library.
configure: error: Please install the folly library

I checked the config.log file and came across these messages:

configure:19036: checking for folly/folly-config.h in /usr/local
configure:19041: result: yes
configure:19052: checking whether compiling and linking against folly works
configure:19085: g++ -o conftest -std=gnu++1y -I/usr/local/include   -L/usr/local/lib conftest.cpp -lfolly  >&5
/usr/local/lib/libfolly.so: undefined reference to `unw_backtrace'
/usr/local/lib/libfolly.so: undefined reference to `_ULx86_64_step'
/usr/local/lib/libfolly.so: undefined reference to `_ULx86_64_get_reg'
/usr/local/lib/libfolly.so: undefined reference to `_Ux86_64_getcontext'
/usr/local/lib/libfolly.so: undefined reference to `_ULx86_64_init_local'
/usr/local/lib/libfolly.so: undefined reference to `_ULx86_64_is_signal_frame'
collect2: error: ld returned 1 exit status
configure:19085: $? = 1
configure: failed program was:
| /* confdefs.h */
...
configure:19093: result: no
configure:19113: Unable to find the folly library.
configure:19115: error: Please install the folly library

Any help is appreciated.

Thanks.

**Comment by eduardo-elizondo** [comment]
Thrift now supports cmake. Go to the main directory and read the CMakeLists.txt for dependencies. Docs will be coming soon. 
For now build by doing:
cmake .
make
If you are using MacOSX you need to specify:
cmake -DOPENSSL_ROOT_DIR=path/to/openssl .
make
