### ISSUE TITLE
Add FunctionInfo.h to thrift2include_transportcore_HEADERS

### ISSUE THREAD

**Issue by menzow** [facebook/fbthrift#229]
Hey,

I was trying to make a build of bistro (https://github.com/facebook/bistro) and was not able to complete the build due to a compile error in the fbthrift dependency. The compiler stopped because it was not able to locate the `FunctionInfo.h` header file. This dependency is introduced by https://github.com/facebook/fbthrift/blob/76d376e1b7d0f189708ef6438abb40862be360d5/thrift/lib/cpp2/transport/core/ThriftProcessor.h#L21. 

I also notice that on ThriftProcessor.h:22 `transporter/core/ThriftChannelIf.h` is included. This file is also not included in the Makefile.am ( https://github.com/facebook/fbthrift/blob/76d376e1b7d0f189708ef6438abb40862be360d5/thrift/lib/cpp2/Makefile.am#L182-L184 )

I'm no C++ programmer, these are just my findings after browsing through the code. Hope it helps resolving the problem or that I might be doing something wrong entirely.

**Comment by eduardo-elizondo** [comment]
Working on this right now. This should be fixed within a day or two.

**Comment by eduardo-elizondo** [comment]
Just landed a fix. Please try again and reopen if this doesn't work.
