### ISSUE TITLE
execv deprecated on Windows

### ISSUE THREAD

**Issue by capsocrates** [facebook/fbthrift#230]
https://github.com/facebook/fbthrift/blob/11e418530987adb4002e41e8338ba780ae5c027a/thrift/compiler/main.cc#L197

The obvious fix is
> #ifdef _WIN32
>       ret = _execv(pycompiler.c_str(), argv.data());
> #else
> 	  ret = execv(pycompiler.c_str(), argv.data());
> #endif

Along with, at the top of the file
> #ifdef _WIN32
> #include <process.h>
> #endif

I have this fix locally and am happy to commit it if that's alright.

**Comment by Orvid** [comment]
It's not deprecated, it's MS being pedantic for no real reason. The preferred method of dealing with it would be adding the appropriate portability header upstream to Folly and then just including that in the right place in thrift. I've not done any work on getting any part of thrift, other than the small part used by HHVM, to work on Windows, so there are likely many such issues just waiting to be found.

**Comment by eduardo-elizondo** [comment]
Feel free to do a pull request. Also, that codepath is now deprecated. Docs coming soon.

**Comment by eduardo-elizondo** [comment]
Closing. Please reopen if you have more comments.
