### ISSUE TITLE
Undocumented hard dependency on pthreads

### ISSUE THREAD

**Issue by capsocrates** [facebook/fbthrift#231]
fbthrift appears to have a hard dependency on pthreads which is A) undocumented on the dependencies page and B) incompatible with Windows.

Are there any plans to make fbthrift cross-platform compatible? In the meantime, are there any plans to document that pthreads is only for `*nix` systems?

**Comment by Orvid** [comment]
There are pthread implementations for Windows that are available and usable. I've been using https://github.com/GerHobbelt/pthread-win32 when testing things :)

**Comment by eduardo-elizondo** [comment]
Thrift now supports cmake. Go to the main directory and read the CMakeLists.txt for dependencies. Docs will be coming soon. 
For now build by doing:
cmake .
make
If you are using MacOSX you need to specify:
cmake -DOPENSSL_ROOT_DIR=path/to/openssl .
make
