### ISSUE TITLE
thrift1 compiler does not normalize slashes in paths

### ISSUE THREAD

**Issue by capsocrates** [facebook/fbthrift#232]
This line in the compiler (see hyperlink):
[`    return abspath.string();`](https://github.com/facebook/fbthrift/blob/0da39a12b753e64698e5aae8b270a6bedd3f1ec2/thrift/compiler/common.cc#L142)
Does not normalize `\` vs. `/` on Windows, which can generate invalid paths with mixed `\`s and `/`s depending on the user's input. The ultimate behavior is that no files are generated, but there is also no error. I had to step into the debugger to figure out what was going wrong.

Using `.generic_string()` instead of `.string()` should solve the problem for Windows without breaking `*nix` builds (where the two methods [give the same output](http://www.boost.org/doc/libs/1_62_0/libs/filesystem/doc/reference.html#path-decomposition-table)).

**Comment by eduardo-elizondo** [comment]
Unfortunately we don't have great windows support. Feel free to do a pull requet to fix this.

**Comment by eduardo-elizondo** [comment]
Closing. Please reopen if you have more comments.
