### ISSUE TITLE
thrift1 compiler generates invalid C++ code for enums

### ISSUE THREAD

**Issue by capsocrates** [facebook/fbthrift#233]
When generating code for an enum, the thrift1 compiler generates this line:
[`    "TEnumTraits<" << fullname << ">::size;" << endl <<`](https://github.com/facebook/fbthrift/blob/0da39a12b753e64698e5aae8b270a6bedd3f1ec2/thrift/compiler/generate/t_cpp_generator.cc#L942)

Which gives this hard compiler error on MSVC:
`error C2734: 'apache::thrift::TEnumTraits<apache::thrift::reflection::Type>::size': 'const' object must be initialized if not 'extern'`

**Comment by eduardo-elizondo** [comment]
Feel free to do a pull request. Unfortunately we don't have great MSVC support.

**Comment by eduardo-elizondo** [comment]
Closing. Please reopen if you have more comments.

**Comment by Orvid** [comment]
This is an issue I've known about for a while, and have a fix for, it's just that the last time I tried to fix it I broke some stuff internally which was expecting these forward declarations to exist :) I need to revive the diff, but this is a fairly trivial fix.

**Comment by eduardo-elizondo** [comment]
Looking forward to the pull request!

**Comment by Orvid** [comment]
Re-fixed again in https://github.com/facebook/fbthrift/commit/4cd64b68c207e75147915c507a147eab3c65373d, which also marks the point at which FBThrift should be able to be compiled on Windows :)
