### ISSUE TITLE
Undefined types in GeneratedSerializationCodeHelper.h

### ISSUE THREAD

**Issue by capsocrates** [facebook/fbthrift#234]
https://github.com/facebook/fbthrift/blob/0da39a12b753e64698e5aae8b270a6bedd3f1ec2/thrift/lib/cpp2/GeneratedSerializationCodeHelper.h#L118

GeneratedSerializationCodeHelper.h refers to several types that are not defined in any of the headers that it includes. These types are
`Byte`, `I16`, `I32`, `I64`, `Double`, `Float`, and `Binary`. Where do these type names come from?

**Comment by yfeldblum** [comment]
It does not refer to any such types.

When the preprocessed code is fully expanded, these words form suffixes of function names, such as `readByte` and `writeByte`, which are member functions of the various protocol readers and writers.
