### ISSUE TITLE
Problem in make

### ISSUE THREAD

**Issue by SANTO-P** [facebook/fbthrift#239]
First I  installed Torch and Folly separately and now trying to install fbthrift. All dependencies are installed properly but gives error in last command of make...

/usr/bin/ld: /usr/local/lib/libfolly.so: undefined reference to symbol '_ZNK17double_conversion23DoubleToStringConverter11ToPrecisionEdiPNS_13StringBuilderE'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libdouble-conversion.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
thrift/lib/cpp2/CMakeFiles/chatroomserver.dir/build.make:174: recipe for target 'bin/chatroomserver' failed
make[2]: *** [bin/chatroomserver] Error 1
CMakeFiles/Makefile2:790: recipe for target 'thrift/lib/cpp2/CMakeFiles/chatroomserver.dir/all' failed
make[1]: *** [thrift/lib/cpp2/CMakeFiles/chatroomserver.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eduardo-elizondo** [comment]
Did you install folly using the Double Conversion library?

**Comment by eduardo-elizondo** [comment]
If you check the readme in: https://github.com/facebook/folly
It has instructions to install double-conversion. That is:

```
  git clone https://github.com/google/double-conversion.git
  cd double-conversion
  cmake -DBUILD_SHARED_LIBS=ON .
  make
  sudo make install
```

**Comment by SANTO-P** [comment]
Installed as you said but still I get the same error

**Comment by SANTO-P** [comment]
[100%] Building CXX object thrift/lib/cpp2/CMakeFiles/chatroomserver.dir/example/ExampleServer.cpp.o
[100%] Linking CXX executable ../../../bin/chatroomserver
/usr/bin/ld: /usr/local/lib/libfolly.so: undefined reference to symbol '_ZNK17double_conversion23DoubleToStringConverter11ToPrecisionEdiPNS_13StringBuilderE'
//usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
thrift/lib/cpp2/CMakeFiles/chatroomserver.dir/build.make:174: recipe for target 'bin/chatroomserver' failed
make[2]: *** [bin/chatroomserver] Error 1
CMakeFiles/Makefile2:790: recipe for target 'thrift/lib/cpp2/CMakeFiles/chatroomserver.dir/all' failed
make[1]: *** [thrift/lib/cpp2/CMakeFiles/chatroomserver.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eduardo-elizondo** [comment]
Sorry I might not have been clean, I meant - go back to the folly readme and start from the instructions that I gave you. Your error means that you didn't compile folly correctly. Especifically follow exactly these instructions: https://github.com/facebook/folly#other-linux-distributions to install folly with the correct linking to double-conversion.

**Comment by SANTO-P** [comment]
It worked out. Thank you.

**Comment by SANTO-P** [comment]
Hey I have installed Torch, folly and thpp. Now how to just install fblualib? if i got to its repo and install from there it again clones folly ..it all begins from start....help

**Comment by eduardo-elizondo** [comment]
No idea, check with them!
