### ISSUE TITLE
Problem in make

### ISSUE THREAD

**Issue by apoptoxin** [facebook/fbthrift#245]
I got a fetal error when running make. 

/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I../../..  -pthread -I/usr/include  -I../cpp -I../../../../gperftools-2.0.99/src -I/usr/local/include   -std=gnu++1y -MT server/libthriftcpp2_la-Cpp2Connection.lo -MD -MP -MF server/.deps/libthriftcpp2_la-Cpp2Connection.Tpo -c -o server/libthriftcpp2_la-Cpp2Connection.lo `test -f 'server/Cpp2Connection.cpp' || echo './'`server/Cpp2Connection.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I../../.. -pthread -I/usr/include -I../cpp -I../../../../gperftools-2.0.99/src -I/usr/local/include -std=gnu++1y -MT server/libthriftcpp2_la-Cpp2Connection.lo -MD -MP -MF server/.deps/libthriftcpp2_la-Cpp2Connection.Tpo -c server/Cpp2Connection.cpp  -fPIC -DPIC -o server/.libs/libthriftcpp2_la-Cpp2Connection.o
In file included from ../../../thrift/lib/cpp2/transport/core/ThriftProcessor.h:25:0,
                 from ../../../thrift/lib/cpp2/server/ThriftServer.h:47,
                 from ../../../thrift/lib/cpp2/server/Cpp2Connection.h:29,
                 from server/Cpp2Connection.cpp:17:
../../../thrift/lib/cpp2/transport/core/ThriftChannelIf.h:22:58: fatal error: thrift/lib/thrift/gen-cpp2/RpcMetadata_types.h: No such file or directory
compilation terminated.
Makefile:1629: recipe for target 'server/libthriftcpp2_la-Cpp2Connection.lo' failed
make[5]: *** [server/libthriftcpp2_la-Cpp2Connection.lo] Error 1
make[5]: Leaving directory '/home/machine_learning/torch2caffe/fbthrift/thrift/lib/cpp2'
Makefile:2145: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/machine_learning/torch2caffe/fbthrift/thrift/lib/cpp2'
Makefile:895: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/machine_learning/torch2caffe/fbthrift/thrift/lib/cpp2'
Makefile:416: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/machine_learning/torch2caffe/fbthrift/thrift/lib'
Makefile:499: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/machine_learning/torch2caffe/fbthrift/thrift'
Makefile:431: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by freshcoderman** [comment]
@apoptoxin same error when installing fblualib from https://github.com/facebookarchive/fblualib with install_all.sh. Have you solved that?

**Comment by eduardo-elizondo** [comment]
The Makefile is not supported anymore.

Build with cmake: https://github.com/facebook/fbthrift#build
