### ISSUE TITLE
No rule to make target 'transport/core/FunctionInfo.h'

### ISSUE THREAD

**Issue by mathgameapi** [facebook/fbthrift#246]
I cannot find the FunctionInfo.h in the source tree?
how can i build the fbthrift?

Thanks

ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libthriftcpp2.a
libtool: link: ( cd ".libs" && rm -f "libthriftcpp2.la" && ln -s "../libthriftcpp2.la" "libthriftcpp2.la" )
make[5]: *** No rule to make target 'transport/core/FunctionInfo.h', needed by 'all-am'.  Stop.
make[5]: Leaving directory '/tmp/fblualib-build.IVdCUu/fbthrift/thrift/lib/cpp2'
Makefile:2145: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/tmp/fblualib-build.IVdCUu/fbthrift/thrift/lib/cpp2'
Makefile:895: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/tmp/fblualib-build.IVdCUu/fbthrift/thrift/lib/cpp2'
Makefile:416: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/fblualib-build.IVdCUu/fbthrift/thrift/lib'
Makefile:498: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/fblualib-build.IVdCUu/fbthrift/thrift'
Makefile:430: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eduardo-elizondo** [comment]
The makefile build is not supported anymore.

Build with cmake: https://github.com/facebook/fbthrift#build
