### ISSUE TITLE
Generated static library (.a files) instead dynamic library (.so)

### ISSUE THREAD

**Issue by developer-mayuan** [facebook/fbthrift#247]
By following your installation commands, I can only generate the static library file `libthriftcpp2.a` under my `usr/local/lib` folder instead of the dynamic link library file `libthriftcpp2.a` as mentioned in your Readme file. Do you know how can I solve this issue? Thanks.

**Comment by jgkimi** [comment]
I have the same issue. There's no libthriftcpp2.so.

**Comment by QingchaoChen** [comment]
Got the same issue. Any solutions?

**Comment by ryandesign** [comment]
If you're building with cmake, its default is to build static libraries. If you want shared libraries instead, use the standard cmake flag `-DBUILD_SHARED_LIBS=ON`.

**Comment by vitaut** [comment]
As @ryandesign wrote, you can enable building shared libraries with `-DBUILD_SHARED_LIBS=ON` in CMake.
