### ISSUE TITLE
An error in installing "thpp" looks like "fbthrift" doesn't provide the library for thrift_compiler

### ISSUE THREAD

**Issue by jgkimi** [facebook/fbthrift#250]
According to the fblualibs guideline, I'm installing folly, waggle, fbthrift and thpp in order on Ubuntu 16.04.
The three programs are successfully installed as the lastest one, but thpp cannot be installed.
That has the following error, it seems to be caused by fbthrift because I cannot import thrift_compiler in python as well. (Maybe, the library for it would be not generated.)

*******************************************************
/usr/bin/python: No module named thrift_compiler
CMakeFiles/thpp.dir/build.make:61: recipe for target 'thpp/if/gen-cpp2/Tensor_data.h' failed
make[2]: *** [thpp/if/gen-cpp2/Tensor_data.h] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/thpp.dir/all' failed
make[1]: *** [CMakeFiles/thpp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
******************************************************

How should I do?

I found if I use "python setup.py install" in thrift/compiler/py, the problem is solved, but then "cannot import name frontend" error appears. Maybe, frontend is missing.

**Comment by IlldianX** [comment]
Same here, looks like /usr/local/lib/python2.7/dist-packages/thrift_py-0.9.0-py2.7.egg is not populated anymore.

**Comment by mansu** [comment]
I encountered the same issue. Is python support deprecated?

**Comment by ilovin** [comment]
same issue

**Comment by codecolony** [comment]
:( 
No resolution for this?

**Comment by edsburke** [comment]
I have a similar problem. Do you guys have a solution? Thanks.

**Comment by stevegury** [comment]
This is probably not the answer you're expecting but both `thpp` and `fblualibs` are in archive mode. It means the code is released to the open source community but nobody is working on it at Facebook.

You can probably fix the build file if you spend enough time updating everything but unfortunately nobody here (the Thrift team) has knowledge about those 2 libraries.
