### ISSUE TITLE
After switching to cmake, python compiler (for cpp2) isn't installed

### ISSUE THREAD

**Issue by shermandemo** [facebook/fbthrift#251]
Current cpp2 can only be generated by python compiler. But after switched to cmake build system, it seems the python compiler (for cpp2) will not be installed (by make install)

**Comment by shermandemo** [comment]
Just found out that cpp2 capability has been integrated into thrift1

**Comment by tinro** [comment]
The mstch_cpp2 option in thrift1 is not equivalent to cpp2. For example we are using the "compatibility" option in thrift2 --gen cpp2 to enable thrift1 and thrift2 mixed in one project.

Could we have a way to build the py binding code, or have full cpp2 support as before?

**Comment by yfeldblum** [comment]
Both Thrift 1 and Compatibility mode will be removed.

For now, perhaps the mstch_cpp2 language target may be used but the cpp2 language target will hopefully be fixed as well.
