### ISSUE TITLE
thrift/test lacks any way to build

### ISSUE THREAD

**Issue by chetmurthy** [facebook/fbthrift#255]
there's no cmakefile provided for building thrift/test and running those tests.

**Comment by JoeLoser** [comment]
Can't you just build the `test` target via `make test`? See https://github.com/facebook/fbthrift/blob/master/CMakeLists.txt#L95

**Comment by chetmurthy** [comment]
was so long ago I've forgotten.  in any case, no longer something I'm working with, so I'll close this.
