### ISSUE TITLE
Question: Why IDL identifiers end with "Args"/"Result" interferes with the implicit service?

### ISSUE THREAD

**Issue by bobintornado** [facebook/fbthrift#256]
https://github.com/facebook/fbthrift/blob/3ac07a4fc0dda16d0fc75638aab0052ae926aeea/thrift/compiler/generate/t_go_generator.cc#L461

**Comment by yfeldblum** [comment]
Blames to fafe143466507fd3b7a3ae2e6aa98edd8fc5f3e8 by @nemith.

**Comment by bobintornado** [comment]
actually I think maybe @knyar and @djwatson could tell me more? 😄

**Comment by vitaut** [comment]
Here's an example of a generated `Args` type that the comment is referring to: https://github.com/facebook/fbthrift/blob/e389dc25e144616e78d3b4093281642243e6617d/thrift/compiler/test/fixtures/basic/gen-go/module/myservice.go#L659
