### ISSUE TITLE
cmake ... 

### ISSUE THREAD

**Issue by zeynali** [facebook/fbthrift#259]
Hi.
my system ubuntu 16.04 .
when i run cmake ... i faced with this error : 

mm@mm:~/fbthrift/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.6.0") 
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  MSTCH_LIBRARIES (missing: MSTCH_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  thrift/cmake/FindMstch.cmake:26 (find_package_handle_standard_args)
  CMakeLists.txt:52 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/mm/fbthrift/build/CMakeFiles/CMakeOutput.log".
See also "/home/mm/fbthrift/build/CMakeFiles/CMakeError.log".

**Comment by boilersam** [comment]
I'm seeing the same thing.  In my case it is within the openr docker container.
Did you figure out a solution?

**Comment by yfeldblum** [comment]
The error message is referring to this library: https://github.com/no1msd/mstch.

**Comment by wangdongxuking61** [comment]
just install mstch.

run : 
$ git clone  https://github.com/no1msd/mstch
$ mkdir build
 $ cd build
 $ cmake ..
 $ make
 $ make install

**Comment by stevegury** [comment]
@wangdongxuking61 is right, your problem is coming from the fact that you don't have the mstch library.
You can either install it globally (see @wangdongxuking61 example) or locally and specify its directory with `MSTCH_INCLUDE_DIRS`.
