### ISSUE TITLE
build failure 'cannot import name frontend'

### ISSUE THREAD

**Issue by dm-jrae** [facebook/fbthrift#26]
Hi, I'm running Ubuntu 14.04 x86_64. I've installed folly with no known issues, but when running make within thrift I receive an import error from python,

PYTHONPATH=../../.python-local/lib/python python -mthrift_compiler.main --gen cpp2 Sasl.thrift
/usr/bin/python: cannot import name frontend

This issue has also been raised in fblualib https://github.com/facebook/fblualib/issues/3

**Comment by msiraj83** [comment]
I also face the same problem....My system Ubuntu 14.04 LTS.
when I try to build this TH++... i get this error..
![th](https://user-images.githubusercontent.com/8863047/31390192-6e294958-adfd-11e7-9583-9464b7973699.png)
Can some body help me

Thanks

**Comment by msiraj83** [comment]
I also face the same problem... when building Thpp as shown below...

![th](https://user-images.githubusercontent.com/8863047/31390598-88bd7770-adfe-11e7-8d13-8e575da59d7a.png)

Although as pre-requesit i build and install` fbthrift` successfully using cmake with following options...

![fbthrift](https://user-images.githubusercontent.com/8863047/31390705-c4b8c374-adfe-11e7-915e-5e74dbeb2304.png)

The main problem is `frontend.so `is not build...

**Comment by internetegir** [comment]
you need to install boost-python before install fbthrift

brew install boost-python

**Comment by khalilo** [comment]
Hi, @msiraj83
How you solved the problem ? I meet the same question.
