### ISSUE TITLE
Where are the 'configure.ac' or 'configure.in' file?

### ISSUE THREAD

**Issue by billyzju** [facebook/fbthrift#263]
I got this error: autoreconf: 'configure.ac' or 'configure.in' is required

**Comment by billyzju** [comment]
And when I tried to install fbthrift using Cmake .., I got the same error with this issue https://github.com/facebook/fbthrift/issues/259

**Comment by yfeldblum** [comment]
Use cmake. And if using cmake, then closing this issue as a duplicate.
