### ISSUE TITLE
Missing YARPL & WANGLE!

### ISSUE THREAD

**Issue by billyzju** [facebook/fbthrift#264]
Hello everyone, I tried to install fbthrift using Cmake, but it seems cmake can not find facebook YARPL & WANGLE, I search a lot for YARPL, but got nothing! Can someone give some helps? Thanks a lot!

cgim@cgim-All-Series:~/3rdParty/fbthrift/build$ cmake ..
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- MSTCH: /usr/local/include
-- DOUBLE_CONVERSION: /usr/include/double-conversion
-- FOLLY: /usr/local/include
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.so)
-- GLOG: /usr/local/include
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib/x86_64-linux-gnu/libkrb5.so;/usr/lib/x86_64-linux-gnu/libk5crypto.so;/usr/lib/x86_64-linux-gnu/libcom_err.so;/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so
-- YARPL PATH: 
-- YARPL_INCLUDE_DIRS (missing: YARPL_LIBRARIES) 
CMake Error at /usr/local/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  WANGLE_INCLUDE_DIRS (missing: WANGLE_LIBRARIES)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  thrift/cmake/FindWangle.cmake:26 (find_package_handle_standard_args)
  CMakeLists.txt:69 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/cgim/3rdParty/fbthrift/build/CMakeFiles/CMakeOutput.log".
See also "/home/cgim/3rdParty/fbthrift/build/CMakeFiles/CMakeError.log"

**Comment by stevegury** [comment]
Thanks @billyzju for reporting!
YARPL is available [here](https://github.com/rsocket/rsocket-cpp/tree/master/yarpl)
And Wangle [here](https://github.com/facebook/wangle)

**Comment by yuanzhenjie** [comment]
Please:    How build  YARPL; @stevegury 
  It is always failure  follow  ;https://github.com/rsocket/rsocket-cpp/tree/master/yarpl
make rsocket-cpp-0.10.0 (with ) 
[root@dl-gpu yarpl]# cmake .
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Compiler has atomic std::shared_ptr support
-- Found Folly: /usr/local/lib/libfolly.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
glog include_dir </usr/local/include> lib </usr/local/lib/libglog.so>
including /data/benjamine/projects/rsocket-cpp/yarpl
yarpl source dir: /data/benjamine/projects/rsocket-cpp/yarpl
-- Configuring done
CMake Error at CMakeLists.txt:168 (add_dependencies):
  The dependency target "gmock" of target "yarpl-tests" does not exist.


-- Generating done
-- Build files have been written to: /data/benjamine/projects/rsocket-cpp/yarpl
[root@dl-gpu yarpl]# make
Scanning dependencies of target yarpl
[  4%] Building CXX object CMakeFiles/yarpl.dir/flowable/Subscription.cpp.o
c++: error：unrecognized command line option ‘-std=c++14’
c++: error：unrecognized command line option ‘-std=c++14’
make[2]: *** [CMakeFiles/yarpl.dir/flowable/Subscription.cpp.o] error 1
make[1]: *** [CMakeFiles/yarpl.dir/all] error 2
make: *** [all] error 2

**Comment by fiorix** [comment]
I'm having the same trouble with yarpl and also with fizz.

**Comment by duynl58** [comment]
You may want to install google mock:
https://github.com/google/googlemock

Or remove yarpl test by deleting lines 129->171 in yarpl - CMakeLists.txt
https://github.com/rsocket/rsocket-cpp/blob/master/yarpl/CMakeLists.txt

About this option: ‘-std=c++14’, you may want to remove lines 11 & 18 in CMakeLists.
However, I recommend using any compiler which supports C++14 standard.

**Comment by aasishIsaac** [comment]
I am having a problem while building fizz. Attaching the logScanning dependencies of target OpenSSLKeyUtilsTest
[ 29%] Building CXX object CMakeFiles/RandomGeneratorTest.dir/crypto/test/RandomGeneratorTest.cpp.o
[ 29%] Building CXX object CMakeFiles/OpenSSLKeyUtilsTest.dir/crypto/openssl/test/OpenSSLKeyUtilsTest.cpp.o
[ 30%] Building CXX object CMakeFiles/DualTicketCipherTest.dir/server/test/DualTicketCipherTest.cpp.o
/usr/bin/ld: /usr/local/lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
/usr/bin/ld: /usr/local/lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
CMakeFiles/AeadCookieCipherTest.dir/build.make:129: recipe for target 'bin/AeadCookieCipherTest' failed
make[2]: *** [bin/AeadCookieCipherTest] Error 1
CMakeFiles/FizzCommandCommonTest.dir/build.make:129: recipe for target 'bin/FizzCommandCommonTest' failed
make[2]: *** [bin/FizzCommandCommonTest] Error 1
CMakeFiles/Makefile2:224: recipe for target 'CMakeFiles/AeadCookieCipherTest.dir/all' failed
make[1]: *** [CMakeFiles/AeadCookieCipherTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:186: recipe for target 'CMakeFiles/FizzCommandCommonTest.dir/all' failed
make[1]: *** [CMakeFiles/FizzCommandCommonTest.dir/all] Error 2
[ 31%] Building CXX object CMakeFiles/OpenSSLKeyUtilsTest.dir/test/CMakeTestMain.cpp.o
[ 31%] Building CXX object CMakeFiles/RandomGeneratorTest.dir/test/CMakeTestMain.cpp.o
[ 31%] Building CXX object CMakeFiles/DualTicketCipherTest.dir/test/CMakeTestMain.cpp.o
/usr/bin/ld: /usr/local/lib/libgmock.a(gmock-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
CMakeFiles/FizzUtilTest.dir/build.make:129: recipe for target 'bin/FizzUtilTest' failed
make[2]: *** [bin/FizzUtilTest] Error 1
CMakeFiles/Makefile2:148: recipe for target 'CMakeFiles/FizzUtilTest.dir/all' failed
make[1]: *** [CMakeFiles/FizzUtilTest.dir/all] Error 2
/usr/bin/ld: /usr/local/lib/libgmock.a(gmock-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
CMakeFiles/AsyncFizzBaseTest.dir/build.make:129: recipe for target 'bin/AsyncFizzBaseTest' failed
make[2]: *** [bin/AsyncFizzBaseTest] Error 1
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/AsyncFizzBaseTest.dir/all' failed
make[1]: *** [CMakeFiles/AsyncFizzBaseTest.dir/all] Error 2
[ 32%] Linking CXX executable bin/RandomGeneratorTest
[ 32%] Linking CXX executable bin/OpenSSLKeyUtilsTest
/usr/bin/ld: /usr/local/lib/libgmock.a(gmock-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
CMakeFiles/AsyncFizzServerTest.dir/build.make:129: recipe for target 'bin/AsyncFizzServerTest' failed
make[2]: *** [bin/AsyncFizzServerTest] Error 1
CMakeFiles/Makefile2:262: recipe for target 'CMakeFiles/AsyncFizzServerTest.dir/all' failed
make[1]: *** [CMakeFiles/AsyncFizzServerTest.dir/all] Error 2
/usr/bin/ld: /usr/local/lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
CMakeFiles/OpenSSLKeyUtilsTest.dir/build.make:129: recipe for target 'bin/OpenSSLKeyUtilsTest' failed
make[2]: *** [bin/OpenSSLKeyUtilsTest] Error 1
CMakeFiles/Makefile2:376: recipe for target 'CMakeFiles/OpenSSLKeyUtilsTest.dir/all' failed
make[1]: *** [CMakeFiles/OpenSSLKeyUtilsTest.dir/all] Error 2
/usr/bin/ld: /usr/local/lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
CMakeFiles/RandomGeneratorTest.dir/build.make:129: recipe for target 'bin/RandomGeneratorTest' failed
make[2]: *** [bin/RandomGeneratorTest] Error 1
CMakeFiles/Makefile2:338: recipe for target 'CMakeFiles/RandomGeneratorTest.dir/all' failed
make[1]: *** [CMakeFiles/RandomGeneratorTest.dir/all] Error 2
[ 33%] Linking CXX executable bin/DualTicketCipherTest
/usr/bin/ld: /usr/local/lib/libgmock.a(gmock-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
CMakeFiles/DualTicketCipherTest.dir/build.make:129: recipe for target 'bin/DualTicketCipherTest' failed
make[2]: *** [bin/DualTicketCipherTest] Error 1
CMakeFiles/Makefile2:300: recipe for target 'CMakeFiles/DualTicketCipherTest.dir/all' failed
make[1]: *** [CMakeFiles/DualTicketCipherTest.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vitaut** [comment]
fizz is a separate project: https://github.com/facebookincubator/fizz. Please follow the build instructions (and report issues) there. Same for wangle and yarpl.
