### ISSUE TITLE
how do i fix undefined reference to 'apache::thrift::RequestRpcMetadata::~RequestRpcMetadata()?

### ISSUE THREAD

**Issue by jlinoff** [facebook/fbthrift#265]
I have successfully built fbthrift 2017.11.20 and was using it when the following link error occurred.

```
libthriftcpp2.so: undefined reference to 'apache::thrift::RequestRpcMetadata::~RequestRpcMetadata()'
```

Any hints about how to debug/fix this would be greatly appreciated.

Here are some details about how i build thrift version `2017.11.20.00`.

These are the thrift libraries generated.

```
     1	libthrift.a
     2	libthrift-core.a
     3	libthrift-core.so
     4	libthriftcpp2.a
     5	libthriftcpp2.so
     6	libthriftfrozen2.a
     7	libthriftfrozen2.so
     8	libthriftprotocol.a
     9	libthriftprotocol.so
    10	libthrift.so
```

Here is how I ran cmake.

```bash
$ cmake -D CMAKE_INSTALL_PREFIX=/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64 \
    -D CMAKE_C_COMPILER=gcc \
    -D CMAKE_CXX_COMPILER=g++ \
    -D FOLLY_INCLUDE_DIR=/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include \
    -D OPENSSL_INCLUDE_DIR=/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include \
    -D BOOST_INCLUDEDIR=/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include \
    -D BOOST_LIBRARYDIR=/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/lib \
    -D BOOST_ROOT=/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64 \
    -D Boost_NO_SYSTEM_PATHS=0 \
    -D DOUBLE_CONVERSION_INCLUDE_DIR=/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include \
    -D BUILD_SHARED_LIBS=ON \
    -D CMAKE_SHARED_LINKER_FLAGS='-L/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/lib -L/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/lib64' \
    -D CMAKE_EXE_LINKER_FLAGS='-L/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/lib -L/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/lib64' \
   ..
```

Here is the cmake output. 

```
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/bin/gcc
-- Check for working C compiler: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/bin/g++
-- Check for working CXX compiler: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2n") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- Found BISON: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/bin/bison (found version "3.0.4") 
-- Found FLEX: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/bin/flex (found version "2.6.4") 
-- Found Mstch: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include  
-- MSTCH: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include
-- Found DOUBLE_CONVERSION: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include  
-- DOUBLE_CONVERSION: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include
-- Found FOLLY: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/lib/libfolly.so  
-- FOLLY: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include
-- Found GFlags: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include  
-- Found gflags  (include: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include, library: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/lib/libgflags.so)
-- Found Glog: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/lib/libglog.so  
-- GLOG: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
-- YARPL PATH: 
-- YARPL_INCLUDE_DIRS (missing: YARPL_LIBRARIES) 
-- Found Wangle: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/lib/libwangle.so  
-- WANGLE: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include
-- Found Zstd: /usr/lib64/libz.so  
-- ZLIB: /usr/include
-- Found Zstd: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/lib/libzstd.so  
-- ZSTD: /opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64/include
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Configuring done
-- Generating done
```

**Comment by jlinoff** [comment]
When I run the thrift (`thrift1`) compiler on `RpcMetadata.thrift`, the generated `RpcMetadata_types.cpp` file has the correct destructor definition. I should be able to workaround the issue by including the generated object file after the libthriftcpp2 library.

**Comment by jlinoff** [comment]
I solved the problem by creating the `libthrift-rpcmetadata.so` shared library, as show below, and adding a reference to it right after the libthriftcpp2.so reference (`-lthriftcpp2 -lthrift-rpcmetadata`).

```bash
$ # In the fbthrift source directory.
$ mkdir tmp
$ RTF_DIR="/opt/cxx-dev-tool-chain/0.8.0/linux-centos-6.9-x86_64"
$ thrift1 \
    --out $(pwd) \
    --gen mstch_cpp2:include_prefix=$RTF/include \
    --templates ../thrift/compiler/generate/templates \
    ../thrift/lib/thrift/RpcMetadata.thrift
$ g++ -Wall -O2 -fPIC -I. -c -o RpcMetadata_constants.cpp.o RpcMetadata_constants.cpp
$ g++ -Wall -O2 -fPIC -I. -c -o RpcMetadata_data.cpp.o RpcMetadata_data.cpp
$ g++ -Wall -O2 -fPIC -I. -c -o RpcMetadata_types.cpp.o RpcMetadata_types.cpp
$ g++ -O2 -fPIC -shared \
    -o libthrift-rpcmetadata.so \
    RpcMetadata*.o \
    -L$RTF_DIR/lib64 \
    -L$RTF_DIR/lib \
    -lthrift -lssl -lcrypto -ldl
$ cp libthrift-rpcmetadata.so $RTF_DIR/lib/
```

**Comment by jlinoff** [comment]
It is not clear why `libthriftcpp2.so` requires the RequestRpcMetadata destructor but this workaround is sufficient for me to move forward.

I would appreciate any hints about solving this in a more elegant way.

**Comment by jlinoff** [comment]
I found a workaround.

**Comment by nagu0011** [comment]
[ 57%] Built target Analyzer
[ 57%] Built target CsvImport
[ 58%] Built target QueryRunner
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_new@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_verify_mode@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_verify@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_num_locks@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_default_passwd_cb_userdata@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_wbio@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `BIO_ctrl@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_peek@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_dynlock_destroy_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_use_certificate_chain_file@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_shutdown@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_get_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_locking_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `TLSv1_method@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_new@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_load_error_strings@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ASN1_STRING_data@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_NAME_get_entry@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_write@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `EVP_cleanup@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_verify_cert_error_string@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_load_verify_locations@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ASN1_STRING_length@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_use_PrivateKey_file@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_peek_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_free_strings@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `sk_num@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_accept@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_remove_state@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_ctrl@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ASN1_STRING_to_UTF8@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_clear_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `TLSv1_2_method@OPENSSL_1.0.1'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_rbio@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_set_fd@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_cleanup_all_ex_data@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `BIO_s_mem@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_read@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_set_bio@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `GENERAL_NAME_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_reason_error_string@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_connect@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_NAME_get_index_by_NID@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_ctrl@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `RAND_poll@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_default_passwd_cb@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSLv23_method@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `BIO_new@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_library_init@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_get_subject_name@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_cipher_list@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_get_ext_d2i@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_NAME_ENTRY_get_data@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `TLSv1_1_method@OPENSSL_1.0.1'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `sk_value@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_dynlock_create_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `sk_pop_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_dynlock_lock_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_verify_result@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_shutdown@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_peer_certificate@OPENSSL_1.0.0'
collect2: error: ld returned 1 exit status
Import/CMakeFiles/KafkaImporter.dir/build.make:108: recipe for target 'bin/KafkaImporter' failed
make[2]: *** [bin/KafkaImporter] Error 1
CMakeFiles/Makefile2:1354: recipe for target 'Import/CMakeFiles/KafkaImporter.dir/all' failed
make[1]: *** [Import/CMakeFiles/KafkaImporter.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- Configuring done
-- Generating done
-- Build files have been written to: /home/thickstat/Downloads/mapd-core/build
[ 58%] Built target rerun_cmake
[ 84%] Built target QueryEngine
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
