### ISSUE TITLE
More documentations and tutorials are needed

### ISSUE THREAD

**Issue by Pc6** [facebook/fbthrift#266]
I failed to find some useful documentations or tutorials on how to use the framework. Are there tutorials that I ignored? if not, do you have the plan to implement the tutorials?

**Comment by stevegury** [comment]
Unfortunately we only have [examples](https://github.com/facebook/fbthrift/tree/master/thrift/example) not tutorials.
We don't have plans to create a tutorial right now, but it could change in the future.

If you want to transform these examples into tutorials, we would gladly accept them and give your credits for it. Just create a pull-request if it's something you're interested in doing.

**Comment by Pc6** [comment]
Transforming examples into tutorials sounds interesting. Maybe I can have a try : )

**Comment by tdargahi** [comment]
Never mind the tutorials. Where is the documentation. How do I even use the compiler. The old thrift commands don't work here.  Why did you abandon the classical thrift. Could have just created a new version.  
Install requires too much effort and things can go wrong which is horrible to debug.
