### ISSUE TITLE
cmake failed on macOS

### ISSUE THREAD

**Issue by geekbaba** [facebook/fbthrift#268]
Hi,my system is macOS,
i was already installed folly with brew。
----------------------------------------------------------------------------------------------

CMake Error at CMakeLists.txt:76 (find_package):
  Could not find a package configuration file provided by "folly" with any of
  the following names:

    follyConfig.cmake
    folly-config.cmake

  Add the installation prefix of "folly" to CMAKE_PREFIX_PATH or set
  "folly_DIR" to a directory containing one of the above files.  If "folly"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by khsibr** [comment]
It fails also on Ubuntu 16.04 with the same error.

**Comment by JohnTian** [comment]
It fails also on Ubuntu 16.04 with the same error.

**Comment by saxenarohit** [comment]
same error

**Comment by ryandesign** [comment]
This happens if folly was built with autotools. Build folly with cmake instead.

**Comment by ProfFan** [comment]
Just a side note that with Homebrew you can use my tap (proffan/robotics) if you just want to install `fbthrift` in a hassle-free way.

**Comment by ryandesign** [comment]
Or with `sudo port install fbthrift` if you use MacPorts.

**Comment by calebmarchent** [comment]
I suspect either ports or brew is always going to be needed to install fbthrift?
As such I think options for the next action on this issue are:

1) Document the supported build and install processes for MacOS
2) Include MacOS in TravisCI builds; to ensure it is maintained
3) No action: just accept users have one of two options provided.

My intuition is that 1 & 2 are the correct options.

**Comment by vitaut** [comment]
> I suspect either ports or brew is always going to be needed to install fbthrift?

Not necessarily. It is always possible to build and install from source.

**Comment by vitaut** [comment]
This is an issue with folly's HomeBrew package which doesn't install the package configuration file. Please open an issue there. In the meantime you can build and install folly using CMake.
