### ISSUE TITLE
[Go] generated code is incompatible with latest apache.thrift library

### ISSUE THREAD

**Issue by ermik** [facebook/fbthrift#269]
Library as linked in generated code:
`"git.apache.org/thrift.git/lib/go/thrift"`

Compiler errors:
```
not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
```
```
cannot use andreServiceProcessorFindProduct literal (type *andreServiceProcessorFindProduct) as type thrift.TProcessorFunction in assignment:
	*andreServiceProcessorFindProduct does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
```
```
not enough arguments in call to processor.Process
	have (int32, thrift.TProtocol, thrift.TProtocol)
	want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
```

**Comment by ermik** [comment]
@pmenglund Um. Thanks for the reply. 2 things.
1. I am sorry but your comment doesn't make sense. The two urls are identical. Typo?
2. I am not "importing" _per se_... fbthrift is importing! (When it generates this code.) Maybe we shouldn't generate code with a dependency that may introduce breaking changes? Perhaps a safe space at facebook/fbthrift would make sure (golang) code doesn't break?
3. If there is a specific version for some libraries this is pinned to — I'd like to make (or hope you will) a pull request introducing such notes to the README

PS. well I guess 3 things

**Comment by pmenglund** [comment]
We're working on making the Go side of fbthrift nice and shiny. I know the change broke old code, but it pointed to the old (thrift1) source, so you could not take advantage of the bug fixes that has been done in `thrift/lib/go/thrift` this repo.

**Comment by ermik** [comment]
I'd like to help with docs, as soon as I get a little bit more into it. Maybe that will solve some of these issues. 
Currently, I just want to know what golang thrift library at which version to use with `thrift1` that I installed via your homebrew tap. Whatever is the latest working solution suits me.

**Comment by yfeldblum** [comment]
> I just want to know which version of fbthrift to use and which libraries (and their versions) will work with the generated code.

A good assumption to make is that generated code will only be guaranteed to work with libraries at the same rev as the thrift compiler which was invoked to generate the code. When updating the library, also update the thrift compiler and re-generate all generated code; likewise, when updating the thrift compiler.

**Comment by mrngm** [comment]
> @pmenglund [..]
>     2. I am not "importing" _per se_... fbthrift is importing! (When it generates this code.) Maybe we shouldn't generate code with a dependency that may introduce breaking changes? Perhaps a safe space at facebook/fbthrift would make sure (golang) code doesn't break?

Relevant to your comment: https://issues.apache.org/jira/projects/THRIFT/issues/THRIFT-4542?filter=allopenissues

This change from Apache Thrift did not only break this project's (generated) Go code, but nearly every Go project that used `git.apache.org/thrift` as import path.

**Comment by ermik** [comment]
Could we use Go's new module system in the future? Isn't it import-path agnostic?

**Comment by vitaut** [comment]
Closing as the original issue seems to be resolved. Please open a new issue for any follow ups.
