### ISSUE TITLE
I can create cpp2 interfaces using python -mthrift_compiler.main but not with thrift1

### ISSUE THREAD

**Issue by jlinoff** [facebook/fbthrift#271]
I am hoping that someone can give me a hint about what I am doing wrong.

The issue is that i can create gen-cpp2 files using the python interface (using `frontend.so`) but i cannot create them using the thrift compiler directly.

### python -mthrift_compiler.main
I am currently compiling my cpp2 thrift specifications using something like this:

```
$ python -mthrift_compiler.main -v -gen cpp2:json,fatal,include_prefix -I path1 -I path2 -o outdir1 my.thrift
```

It works just fine.

### thrift1
However when i try the same thing using the thrift compiler the cpp2 code is not generated, something like this.

```
$ thrift1 -v -gen cpp2:json,fatal,include_prefix -I path1 -I path2 -o outdir2 my.thrift
```

It will correctly generate code for `py` and for `java` if I add `--gen py --gen java`.

### specifics

| package | version | notes |
| --------- | ------: | ------ |
| thrift | 2018.05.07.00 | but the same problem occurred in earlier versions
| folly| 2018.05.07.00 | |
| wangle | 2018.05.07.00 | |
| gcc | 7.3.0 | |
| boost | 1.67.0 ||

**Comment by yfeldblum** [comment]
For now, I think you can use the `mstch_cpp2` target language (note that it will be switched back to `cpp2` at some point).
