### ISSUE TITLE
thrift1 -v -r --gen cpp2:cpp2:json,fatal,include_prefix not creating "*fatal_all.h"

### ISSUE THREAD

**Issue by jlinoff** [facebook/fbthrift#272]
I am running thrift version `2018.05.07` (also folly, wangle and fatal) as shown below and was expecting to see a file of the form `*fatal_all.h` generated. 

```
$ thrift1 -r -v --gen mstch_cpp2:json,fatal,include_prefix --templates $TEMPLATE_DIR -I $INC_DIR -o $OUT_DIR my.thrift
```

I also tried using `--gen mstch_cpp2:json,reflection,fatal,include_prefix` as well.

Has that changed? Is there a new way to get support for dynamic types?

**Comment by avalonalex** [comment]
previously, reflection generation is done using thrift/compiler/py under https://github.com/facebook/fbthrift/tree/master/thrift/compiler/py. But we recently move all the reflection generation logic to main thrift compiler now. the command you posted should work now.
