### ISSUE TITLE
how to install fbthrift in an easy way ?

### ISSUE THREAD

**Issue by JohnTian** [facebook/fbthrift#273]
It's horrible to install fbthrift. Is there any easy way to install fbthrift?
Like:
```
$ sudo apt-get update
$ sudo apt-get install fbthrift
```
OR
```
$ brew update
$ brew install fbthrift
```

**Comment by ryandesign** [comment]
If fbthrift is not in your package manager of choice, you should probably ask your package manager of choice to add it.

It is in [MacPorts](https://www.macports.org) and can be installed as usual with `sudo port install fbthrift`.

**Comment by ermik** [comment]
Isn't there a fb [cask](https://github.com/facebook/homebrew-fb)?

**Comment by calebmarchent** [comment]
> Isn't there a fb [cask](https://github.com/facebook/homebrew-fb)?

Looking at the source to the fb-cask; fbthrift is now out of date: its compiled with autotools; which I believe is no longer supported and the version of fbthrift is hard-coded to a release in 2017.
