### ISSUE TITLE
CWE-676

### ISSUE THREAD

**Issue by teamwoot** [facebook/fbthrift#274]
Hi Team, 

`https://github.com/facebook/fbthrift/blob/master/thrift/test/RWMutexStarveTest.cpp#L137`

i.e

usleep(2000);

This C routine is considered obsolete (as opposed to the shell command by the same name). The interaction of this function with SIGALRM and other timer functions such as sleep(), alarm(), setitimer(), and nanosleep() is unspecified such as (CWE-676). 

However we recommend to use nanosleep(2) or setitimer(2) instead.

Request team to please have a look

Cheers!
Team w00t

**Comment by yfeldblum** [comment]
The highlighted code is in a unit-test for legacy code which is slated for removal.
