### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by agorman** [facebook/fbthrift#275]
Running Ubuntu 14.04.5 LTS

# make
[  3%] Built target compiler_ast
[  7%] Built target compiler_base
[ 25%] Built target compiler_generators
[ 26%] Linking CXX executable ../../bin/thrift1
../../lib/libcompiler_generators.a(t_mstch_generator.cc.o): In function `t_mstch_generator::render(std::string const&, boost::variant<boost::detail::variant::recursive_flag<decltype(nullptr)>, std::string, int, double, bool, mstch::internal::lambda_t<boost::recursive_variant_>, std::shared_ptr<mstch::internal::object_t<boost::recursive_variant_> >, std::map<std::string const, boost::recursive_variant_, std::less<std::string const>, std::allocator<std::pair<std::string const, boost::recursive_variant_> > >, std::vector<boost::recursive_variant_, std::allocator<boost::recursive_variant_> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&)':
t_mstch_generator.cc:(.text+0x5f65): undefined reference to `mstch::render(std::string const&, boost::variant<boost::detail::variant::recursive_flag<decltype(nullptr)>, std::string, int, double, bool, mstch::internal::lambda_t<boost::recursive_variant_>, std::shared_ptr<mstch::internal::object_t<boost::recursive_variant_> >, std::map<std::string const, boost::recursive_variant_, std::less<std::string const>, std::allocator<std::pair<std::string const, boost::recursive_variant_> > >, std::vector<boost::recursive_variant_, std::allocator<boost::recursive_variant_> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/thrift1] Error 1
make[1]: *** [thrift/compiler/CMakeFiles/thrift1.dir/all] Error 2
make: *** [all] Error 2

**Comment by stevegury** [comment]
Can you check that you've correctly installed the external dependencies (especially [mstch](https://github.com/no1msd/mstch))?
More details here: https://github.com/facebook/fbthrift/tree/master/thrift/compiler

**Comment by agorman** [comment]
I believe so

cmake ..

 ---> Running in 50412fd86b4e
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.54.0
-- Configuring done
-- Generating done
-- Build files have been written to: /root/torch/mstch/build


make && make install

Scanning dependencies of target mstch
[ 12%] Building CXX object src/CMakeFiles/mstch.dir/state/in_section.cpp.o
[ 25%] Building CXX object src/CMakeFiles/mstch.dir/state/outside_section.cpp.o
[ 37%] Building CXX object src/CMakeFiles/mstch.dir/mstch.cpp.o
[ 50%] Building CXX object src/CMakeFiles/mstch.dir/render_context.cpp.o
[ 62%] Building CXX object src/CMakeFiles/mstch.dir/template_type.cpp.o
[ 75%] Building CXX object src/CMakeFiles/mstch.dir/token.cpp.o
[ 87%] Building CXX object src/CMakeFiles/mstch.dir/utils.cpp.o
[100%] Linking CXX static library libmstch.a
[100%] Built target mstch
[100%] Built target mstch
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libmstch.a
-- Installing: /usr/local/include/mstch/mstch.hpp
-- Installing: /usr/local/lib/cmake/mstch/mstch-targets.cmake
-- Installing: /usr/local/lib/cmake/mstch/mstch-targets-release.cmake
-- Installing: /usr/local/lib/cmake/mstch/mstch-config.cmake
-- Installing: /usr/local/lib/cmake/mstch/mstch-config-version.cmake

**Comment by agorman** [comment]
Looks like you were right. I reinstalled all deps and now it compiles.

¯\\_(ツ)_/¯
