### ISSUE TITLE
Building shared libraries fails on macOS while running thrift1

### ISSUE THREAD

**Issue by ryandesign** [facebook/fbthrift#276]
Building fbthrift on OS X (El Capitan, but the problem should be the same on any version of macOS) with `-DBUILD_SHARED_LIBS=ON` fails with:

```
dyld: Library not loaded: /opt/local/lib/libcompiler_generators.dylib
  Referenced from: ..../build/thrift/lib/thrift/../../../bin/thrift1
  Reason: image not found
/bin/sh: line 1: 31097 Trace/BPT trap: 5       ../../../bin/thrift1 --gen mstch_cpp2:include_prefix=thrift/lib/thrift -o ..../fbthrift-2018.06.04.00/thrift/lib/thrift --templates ..../fbthrift-2018.06.04.00/thrift/compiler/generate/templates ..../fbthrift-2018.06.04.00/thrift/lib/thrift/RpcMetadata.thrift
```

The build is trying to run the just-compiled `thrift1` program, which links with the not-yet-installed libcompiler_generators.dylib library. When running `thrift1` at build time, you must set `DYLD_LIBRARY_PATH` to the path where the not-yet-installed libcompiler_generators.dylib library can be found, otherwise it will either fail (as it did for me, because I did not yet have any version of fbthrift installed), or it will link with the wrong version (the previously installed version) of the library.

On OS X El Capitan and later, a new system security measure prevents dangerous environment variables like `DYLD_LIBRARY_PATH` from being passed to subshells, so you must set the variable as close to the invocation of `thrift1` as possible.

**Comment by ryandesign** [comment]
I can work around this problem using this patch:

```
--- ThriftLibrary.cmake.orig	2018-06-03 15:53:33.000000000 -0500
+++ ThriftLibrary.cmake	2018-06-09 14:55:30.000000000 -0500
@@ -210,7 +210,7 @@
 endif()
 add_custom_command(
   OUTPUT ${${file_name}-${language}-HEADERS} ${${file_name}-${language}-SOURCES}
-  COMMAND ${THRIFT1}
+  COMMAND env DYLD_LIBRARY_PATH="${CMAKE_BINARY_DIR}/lib" "${CMAKE_BINARY_DIR}/bin/${THRIFT1}"
     --gen "${gen_language}:${options}${include_prefix_text}"
     -o ${output_path}
     --templates ${THRIFT_TEMPLATES}
```

but this is probably not the best way to solve it, since it sets `DYLD_LIBRARY_PATH` for all systems, not just macOS. I'm not proficient enough in cmake to know how to properly conditionalize this.

**Comment by vitaut** [comment]
`compiler_generators` is always built as a static library now.
