### ISSUE TITLE
Undefined symbols error_message(long)

### ISSUE THREAD

**Issue by ryandesign** [facebook/fbthrift#278]
Building fbthrift 2018.06.04.00 fails when kerberos5 1.16.1 and libcomerr 1.44.2 (part of e2fsprogs) are installed with MacPorts:

```
Undefined symbols for architecture x86_64:
  "error_message(long)", referenced from:
      apache::thrift::krb5::Krb5Context::Krb5Context(apache::thrift::krb5::Krb5Context::ContextType) in Krb5Util.cpp.o
ld: symbol(s) not found for architecture x86_64
```

`error_message` is in libcom_err, and the fbthrift build is linking with libcom_err, but in libcomerr 1.44.2's com_err.h, it is defined as:

    extern char const *error_message (long);

In the copy of com_err.h included with OS X El Capitan, with which fbthrift builds without this error, it's defined as:

    const char *error_message (errcode_t code);

I'm not sure why this difference exists. I see that the copy included with macOS is newer, with a copyright date of 1998-2000, while the one in e2fsprogs has a copyright date of 1988. I'm not sure if there's anything fbthrift can do to be compatible with both implementations, or if I just need to contact the e2fsprogs people and ask them to update their com_err.h to the newer definition.

**Comment by vitaut** [comment]
Thrift no longer has `Krb5Context`.
