### ISSUE TITLE
Hack runtime library references unbound names

### ISSUE THREAD

**Issue by renaudb** [facebook/fbthrift#283]
Running `hh_client` in the hack runtime [src/](https://github.com/facebook/fbthrift/tree/master/thrift/lib/hack) folder results in a number of errors due to unbound names.

```
src/ThriftAsyncProcessor.php:51:63,75: Could not find method getWaitHandle in an object of type Awaitable (Typing[4053])
```

```
src/protocol/simplejson/TSimpleJSONProtocol.php:196:15,26: Unbound name: StringBuffer (an object type) (Naming[2049])
src/protocol/simplejson/TSimpleJSONProtocol.php:507:15,26: Unbound name: StringBuffer (an object type) (Naming[2049])
```

**Comment by DavidSnider** [comment]
Looks like stringbuffer is actively worse than string concatenation. This should be fixed by just copying the version we have in flib.

I _believe_ we can just remove the call to getWaitHandle and everything should "just work".

**Comment by DavidSnider** [comment]
cc @spalamarchuk who should be able to make these fixes.

**Comment by renaudb** [comment]
I've put together a fix if it can be useful: https://github.com/facebook/fbthrift/pull/296

**Comment by vitaut** [comment]
The fix has been merged.
