### ISSUE TITLE
Hack codegen references unbound names

### ISSUE THREAD

**Issue by renaudb** [facebook/fbthrift#284]
Running the hack codegen with required fields (non optional) results un unbound name errors due to the missing `nullthrows` function.

**Comment by DavidSnider** [comment]
Sigh. I think we can probably use a different construct here.

**Comment by DavidSnider** [comment]
cc @spalamarchuk who should hopefully have the bandwidth for this.

Just replace nullthrows(<expr>) with (<expr> as nonnull). The parens may or may not be necessary.

**Comment by vitaut** [comment]
AFAICS this has been fixed already. Feel free to reopen with more details if this is not the case.
