### ISSUE TITLE
Make failed  : Generating frozen files ../fbthrift/thrift/lib/thrift

### ISSUE THREAD

**Issue by yuanzhenjie** [facebook/fbthrift#285]
Please check this issue. thanks
ENV:gcc 4.9.2 \centOS7 

make failed
[  0%] Building CXX object thrift/compiler/CMakeFiles/compiler_ast.dir/ast/t_program.cc.o
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h: 在成员函数‘bool apache::thrift::compiler::t_function::any_stream_params() const’中:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:73: error：形参声明为‘auto’
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                                         ^
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h: 在 lambda 函数中:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:159:14: error：‘arg’在此作用域中尚未声明
       return arg->get_type()->is_pubsub_stream();
              ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__find_if(_RandomAccessIterator, _RandomAccessIterator, _Predicate, std::random_access_iterator_tag) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<apache::thrift::compiler::t_field* const*, std::vector<apache::thrift::compiler::t_field*> >; _Predicate = apache::thrift::compiler::t_function::any_stream_params() const::__lambda2]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:4465:41:   required from ‘_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<apache::thrift::compiler::t_field* const*, std::vector<apache::thrift::compiler::t_field*> >; _Predicate = apache::thrift::compiler::t_function::any_stream_params() const::__lambda2]’
/usr/include/c++/4.8.2/bits/stl_algo.h:747:71:   required from ‘bool std::none_of(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<apache::thrift::compiler::t_field* const*, std::vector<apache::thrift::compiler::t_field*> >; _Predicate = apache::thrift::compiler::t_function::any_stream_params() const::__lambda2]’
/usr/include/c++/4.8.2/bits/stl_algo.h:765:51:   required from ‘bool std::any_of(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<apache::thrift::compiler::t_field* const*, std::vector<apache::thrift::compiler::t_field*> >; _Predicate = apache::thrift::compiler::t_function::any_stream_params() const::__lambda2]’
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:160:6:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:214:23: error：对‘(apache::thrift::compiler::t_function::any_stream_params() const::__lambda2) (apache::thrift::compiler::t_field* const&)’的调用没有匹配
    if (__pred(*__first))
                       ^
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:59: 附注：备选是：
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                           ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:214:23: 附注：void (*)()  <转换>
    if (__pred(*__first))
                       ^
/usr/include/c++/4.8.2/bits/stl_algo.h:214:23: 附注： 备选需要 1 实参，但提供了 2 个
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注：apache::thrift::compiler::t_function::any_stream_params() const::__lambda2
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                                            ^
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注： 备选需要 0 实参，但提供了 1 个
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:218:23: 错误：对‘(apache::thrift::compiler::t_function::any_stream_params() const::__lambda2) (apache::thrift::compiler::t_field* const&)’的调用没有匹配
    if (__pred(*__first))
                       ^
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:59: 附注：备选是：
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                           ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:218:23: 附注：void (*)()  <转换>
    if (__pred(*__first))
                       ^
/usr/include/c++/4.8.2/bits/stl_algo.h:218:23: 附注： 备选需要 1 实参，但提供了 2 个
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注：apache::thrift::compiler::t_function::any_stream_params() const::__lambda2
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                                            ^
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注： 备选需要 0 实参，但提供了 1 个
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:222:23: 错误：对‘(apache::thrift::compiler::t_function::any_stream_params() const::__lambda2) (apache::thrift::compiler::t_field* const&)’的调用没有匹配
    if (__pred(*__first))
                       ^
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:59: 附注：备选是：
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                           ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:222:23: 附注：void (*)()  <转换>
    if (__pred(*__first))
                       ^
/usr/include/c++/4.8.2/bits/stl_algo.h:222:23: 附注： 备选需要 1 实参，但提供了 2 个
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注：apache::thrift::compiler::t_function::any_stream_params() const::__lambda2
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                                            ^
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注： 备选需要 0 实参，但提供了 1 个
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:226:23: 错误：对‘(apache::thrift::compiler::t_function::any_stream_params() const::__lambda2) (apache::thrift::compiler::t_field* const&)’的调用没有匹配
    if (__pred(*__first))
                       ^
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:59: 附注：备选是：
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                           ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:226:23: 附注：void (*)()  <转换>
    if (__pred(*__first))
                       ^
/usr/include/c++/4.8.2/bits/stl_algo.h:226:23: 附注： 备选需要 1 实参，但提供了 2 个
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注：apache::thrift::compiler::t_function::any_stream_params() const::__lambda2
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                                            ^
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注： 备选需要 0 实参，但提供了 1 个
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:234:23: error：对‘(apache::thrift::compiler::t_function::any_stream_params() const::__lambda2) (apache::thrift::compiler::t_field* const&)’的调用没有匹配
    if (__pred(*__first))
                       ^
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:59: 附注：备选是：
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                           ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:234:23: 附注：void (*)()  <转换>
    if (__pred(*__first))
                       ^
/usr/include/c++/4.8.2/bits/stl_algo.h:234:23: 附注： 备选需要 1 实参，但提供了 2 个
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注：apache::thrift::compiler::t_function::any_stream_params() const::__lambda2
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                                            ^
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注： 备选需要 0 实参，但提供了 1 个
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:238:23: error：对‘(apache::thrift::compiler::t_function::any_stream_params() const::__lambda2) (apache::thrift::compiler::t_field* const&)’的调用没有匹配
    if (__pred(*__first))
                       ^
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:59: 附注：备选是：
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                           ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:238:23: 附注：void (*)()  <转换>
    if (__pred(*__first))
                       ^
/usr/include/c++/4.8.2/bits/stl_algo.h:238:23: 附注： 备选需要 1 实参，但提供了 2 个
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注：apache::thrift::compiler::t_function::any_stream_params() const::__lambda2
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                                            ^
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注： 备选需要 0 实参，但提供了 1 个
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:242:23: error：对‘(apache::thrift::compiler::t_function::any_stream_params() const::__lambda2) (apache::thrift::compiler::t_field* const&)’的调用没有匹配
    if (__pred(*__first))
                       ^
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:59: 附注：备选是：
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                           ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:23,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/usr/include/c++/4.8.2/bits/stl_algo.h:242:23: 附注：void (*)()  <转换>
    if (__pred(*__first))
                       ^
/usr/include/c++/4.8.2/bits/stl_algo.h:242:23: 附注： 备选需要 1 实参，但提供了 2 个
In file included from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_service.h:26:0,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_scope.h:27,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.h:31,
                 from /data/benjamine/projects/fbthrift/thrift/compiler/ast/t_program.cc:16:
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注：apache::thrift::compiler::t_function::any_stream_params() const::__lambda2
     return std::any_of(members.cbegin(), members.cend(), [](auto const& arg) {
                                                                            ^
/data/benjamine/projects/fbthrift/thrift/compiler/ast/t_function.h:158:76: 附注： 备选需要 0 实参，但提供了 1 个
make[2]: *** [thrift/compiler/CMakeFiles/compiler_ast.dir/ast/t_program.cc.o] error 1
make[1]: *** [thrift/compiler/CMakeFiles/compiler_ast.dir/all] error 2
make: *** [all] error 2

**Comment by duynl58** [comment]
@yuanzhenjie  are you still facing the issue?

Please consider checking if you added EXCLUDE_FROM_ALL flag in your project-wide CMakeLists.txt

If the problem still persists, please add this line to `master/thrift/lib/cpp2/CMakeLists.txt` file

```
add_dependencies(thriftcpp2 Sasl-cpp2-target RpcMetadata-cpp2-target)
```
