### ISSUE TITLE
Hack codegen invalid when using namespaces

### ISSUE THREAD

**Issue by renaudb** [facebook/fbthrift#293]
Generating hack code results in a number of errors when using namespaces. I identified at least two types of errors:

* Unqualified reference to global functions (invalid as of Hack 3.26).

* Invalid fully qualified union enum declarations.

**Comment by renaudb** [comment]
I have a fix here: https://github.com/facebook/fbthrift/pull/292

**Comment by yfeldblum** [comment]
Fixed in #292.
