### ISSUE TITLE
Hack runtime lib uses pre HHVM 3.24 call by reference syntax

### ISSUE THREAD

**Issue by renaudb** [facebook/fbthrift#295]
The Hack runtime doesn't have reference annotations at the callsite (required since HHVM 3.24).

**Comment by renaudb** [comment]
Here is a fix: https://github.com/facebook/fbthrift/pull/294

**Comment by vitaut** [comment]
I believe this was fixed in https://github.com/facebook/fbthrift/commit/605b1f98fbebf6ac1f74c5d1a1ed08570fc50e27.
