### ISSUE TITLE
make error with gcc5.4

### ISSUE THREAD

**Issue by junstor** [facebook/fbthrift#299]
[ 27%] Linking CXX executable ../../bin/thrift1
../../lib/libcompiler_generators.a(t_hs_generator.cc.o): In function `t_hs_generator::init_generator()':
t_hs_generator.cc:(.text+0x152): undefined reference to `split_namespace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../lib/libcompiler_generators.a(t_mstch_py3_generator.cc.o): In function `(anonymous namespace)::t_mstch_py3_generator::get_py3_namespace(apache::thrift::compiler::t_program const&, std::initializer_list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)':
t_mstch_py3_generator.cc:(.text+0x6cd2): undefined reference to `split_namespace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../lib/libcompiler_generators.a(t_mstch_pyi_generator.cc.o): In function `(anonymous namespace)::t_mstch_pyi_generator::get_py_namespace_raw(apache::thrift::compiler::t_program const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
t_mstch_pyi_generator.cc:(.text+0x2eef): undefined reference to `split_namespace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/thrift1] Error 1
make[1]: *** [thrift/compiler/CMakeFiles/thrift1.dir/all] Error 2
make: *** [all] Error 2

**Comment by vitaut** [comment]
GCC 5.4 is no longer supported. If you still give this error with a newer version of gcc and fbthrift, please provide more repro details.
