### ISSUE TITLE
How can I build the example on debian9.4 amd64

### ISSUE THREAD

**Issue by GitXiaoZe** [facebook/fbthrift#300]
I have built and installed [proxygen()](https://github.com/facebook/proxygen) and [rsocket-cpp](https://github.com/rsocket/rsocket-cpp). And in order to build fbthrift/thrift/example, I added add_subdirectory(example) to thrift/CMakeLists.txt.:
`if(lib_only OR build_all)`
`add_subdirectory(lib)`
`endif(lib_only OR build_all)`
`add_subdirectory(example)`
`include(CMakePackageConfigHelpers)`

Then I entered into fbthrift/build and executed the following command:
 `cmake ..`
 `make`
During the process of building, I got an error and the error:
**``Scanning dependencies of target example_server
[ 97%] Building CXX object thrift/example/cpp2/CMakeFiles/example_server.dir/server/ExampleServer.cpp.o
[ 97%] Linking CXX executable ../../../bin/example_server
CMakeFiles/example_server.dir/server/ExampleServer.cpp.o: In function `apache::thrift::HTTP2RoutingHandler::HTTP2RoutingHandler(std::unique_ptr<proxygen::HTTPServerOptions, std::default_delete<proxygen::HTTPServerOptions> >, apache::thrift::ThriftProcessor*, apache::thrift::server::ServerConfigs const&)':
ExampleServer.cpp:(.text._ZN6apache6thrift19HTTP2RoutingHandlerC2ESt10unique_ptrIN8proxygen17HTTPServerOptionsESt14default_deleteIS4_EEPNS0_15ThriftProcessorERKNS0_6server13ServerConfigsE[_ZN6apache6thrift19HTTP2RoutingHandlerC5ESt10unique_ptrIN8proxygen17HTTPServerOptionsESt14default_deleteIS4_EEPNS0_15ThriftProcessorERKNS0_6server13ServerConfigsE]+0x27): undefined reference to `vtable for apache::thrift::HTTP2RoutingHandler'
CMakeFiles/example_server.dir/server/ExampleServer.cpp.o: In function `apache::thrift::RSRoutingHandler::RSRoutingHandler()':
ExampleServer.cpp:(.text._ZN6apache6thrift16RSRoutingHandlerC2Ev[_ZN6apache6thrift16RSRoutingHandlerC5Ev]+0x1b): undefined reference to `vtable for apache::thrift::RSRoutingHandler'
collect2: error: ld returned 1 exit status
thrift/example/cpp2/CMakeFiles/example_server.dir/build.make:192: recipe for target 'bin/example_server' failed
make[2]: *** [bin/example_server] Error 1
CMakeFiles/Makefile2:1144: recipe for target 'thrift/example/cpp2/CMakeFiles/example_server.dir/all' failed
make[1]: *** [thrift/example/cpp2/CMakeFiles/example_server.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2``**

How can I fix this problem and build the example?

**Comment by vitaut** [comment]
fbthrift doesn't provide build configs for transport libraries at the moment which is one of the reasons that `example_server` is not part of the build.

**Comment by GitXiaoZe** [comment]
@vitaut  Thanks for your reply :-)

**Comment by RoshanPAN** [comment]
@vitaut new to cmake world, what's the build config you are referring to? 
I'm trying to build the example code myself and failed with the same error msg. How could I build the target sucessfully?

**Comment by vitaut** [comment]
There is no CMake config for the `example_server` so you cannot build it with CMake.

**Comment by yfeldblum** [comment]
Closing due to age.
