### ISSUE TITLE
SO_REUSEPORT is always enabled once ThriftServer::setReusePort was called.

### ISSUE THREAD

**Issue by dutor** [facebook/fbthrift#301]
As title. 

I think this problem is due to a bug introduced here: https://github.com/facebook/fbthrift/blob/master/thrift/lib/cpp2/server/ThriftServer.cpp#L367.

`reusePort_` is of type `folly::Optional<bool>`, but not `bool`.

**Comment by vitaut** [comment]
This was fixed in https://github.com/facebook/fbthrift/commit/e14e6d244e875857da8c10d058b7fc5292075522. Thanks for reporting!
