### ISSUE TITLE
Add rules to build thrift interfaces for Python3 to ThriftLibrary.cmake 

### ISSUE THREAD

**Issue by calebmarchent** [facebook/fbthrift#302]
ThriftLibrary.cmake currently supports build of cpp and cpp2; as I need to build interfaces for Python3 for https://github.com/facebookincubator/LogDevice; will need to either add or find equivalent macros to do that. I am currently investigating ...

**Comment by yfeldblum** [comment]
Note that there is no longer cpp, only cpp2.

**Comment by calebmarchent** [comment]
Been working through the compile process today, unless I have misunderstood, which is likely) the interface for fbthrift itself is not compiled; which might explain why even my very simple example does not compile.

Now looking to ensure that those libs are compiled; will need to split off additional issue if confirmed that this does indeed need doing.

**Comment by calebmarchent** [comment]
Update:

So far have been working on a hacked up prototype; designed "just to see the parts operating together"; before creating a design for a production solution. py3 thrift is built with Cython; which prefers to see all Cython created as Python packages using distutils. Of course, the rest of FBThrift is built with CMake so at some point I will need to bring these together.

I have published a branch to my public fork: https://github.com/calebmarchent/fbthrift/tree/build_thrift_lib_in_oss
used with a similar name branch with folly:
https://github.com/calebmarchent/folly/tree/build_python_bindings_in_oss_no_reloc

I am getting pretty close; but presently getting conflicts with Python when I try to test the scripts.

**Comment by calebmarchent** [comment]
Have provided first chunk of work to compile fbthrift-py3 as prototype under https://github.com/facebook/fbthrift/pull/308.

**Comment by calebmarchent** [comment]
Update: first chunk of work landed, types modules seem to work fine; but now I need to be able to make clients; so working on getting the clients.py unit test going - which will result in another PR.

**Comment by vitaut** [comment]
This issue is out of date and thrift-py3 codegen has been superseded by thrift-python.
