### ISSUE TITLE
Compilation error: Preprocessor doesn't like std::pair<t_struct*, t_struct*>

### ISSUE THREAD

**Issue by akreuzkamp** [facebook/fbthrift#304]
Compiling current HEAD of fbthrift fails on my machine (archlinux, gcc 8.2.1) with the error
```
thrift/compiler/thrifty.hh:686:90: error: macro "YY_RVREF" passed 2 arguments, but takes just 1
       basic_symbol (typename Base::kind_type t, YY_RVREF (std::pair<t_struct*, t_struct*>) v);
```
which is because the preprocessor considers `std::pair<t_struct*` and `t_struct*>` as separate arguments to the macro.
This issue can be resolved by reverting commit af4c1ba5 (or by replacing the definition of `t_structpair` by a `using t_structpair = std::pair<t_struct*, t_struct*>` and using that in thrifty.yy)

**Comment by vitaut** [comment]
Fixed in https://github.com/facebook/fbthrift/commit/8a8172aec6bbad4398bd0a6f64b4a6aa4d0ef96c, thanks for reporting!
