### ISSUE TITLE
Is there a way to have multiple request queue in fbthrift

### ISSUE THREAD

**Issue by newpoo** [facebook/fbthrift#306]
We have several types of requests. One of them is very critical. We want to put them into a different request queue so that it won't be discarded when the server is overloaded by other types of requests. We could do this in the application level. Just wanted to check out if there is any built in features that could solve this problem already? Thank you!

**Comment by yfeldblum** [comment]
In C++, you can use a higher priority for that request type with the `priority` annotation as long as you are using a priority-aware thread manager (the default has per-priority thread pools but you may need to customize the size of one or more of the pools), or you can use the `thread = 'eb'` annotation and override the `async_eb_` handler function for that request type which will be called in the event loop before any kind of enqueueing (overriding any other handler function won't work), or you can write a custom processor replacing the default generated async processor for more granular control or do to whatever you want.

**Comment by newpoo** [comment]
Thank you for the comment, it's really helpful!

**Comment by newpoo** [comment]
@yfeldblum I couldn't find an example thrift file with priority annotation for functions. Would you please provide a pointer for that?

**Comment by yfeldblum** [comment]
[Example](https://github.com/facebook/fbthrift/blob/v2019.01.07.00/thrift/compiler/test/fixtures/basic/src/module.thrift#L41-L48)
