### ISSUE TITLE
I cannot use the hack code generator

### ISSUE THREAD

**Issue by a20012251** [facebook/fbthrift#33]
In the compiler there's a hack generator but it's not bundled with the rest of the main binary. Can you do that?

Thanks!

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
