### ISSUE TITLE
Add some tutorial for windows

### ISSUE THREAD

**Issue by soroshsabz** [facebook/fbthrift#330]
ITNOA

In README.md, some brief documentation about windows build and usage is needed.

**Comment by vitaut** [comment]
The same CMake build instructions apply to all platforms, including Windows.

**Comment by soroshsabz** [comment]
@vitaut In README.md in [Build section](https://github.com/facebook/fbthrift#build) say 


> This will create:
> thrift/bin/thrift1: The Thrift compiler binary to generate client and server code.
> thrift/lib/libthriftcpp2.so: Runtime library for clients and servers.

that is not currect in windows, and some instruction above of that does not work on windows like `make -j`. so I think, some brief documentation about windows build and usage is needed. :)

thanks for replays

**Comment by vitaut** [comment]
Just use `cmake --build .` (I added it to the README) or follow the CMake documentation.
