### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by jiazerojia** [facebook/fbthrift#335]
i am sure __cplusplus == 201402L

[ 37%] Building CXX object thrift/lib/cpp/CMakeFiles/thrift-core.dir/Thrift.cpp.o
In file included from /usr/local/include/folly/Range.h:22:0,
                 from /home/fbthrift/thrift/lib/cpp/Thrift.h:20,
                 from /home/fbthrift/thrift/lib/cpp/Thrift.cpp:21:
/usr/local/include/folly/Portability.h:22:1: error: static assertion failed: __cplusplus >= 201402L
 static_assert(__cplusplus >= 201402L, "__cplusplus >= 201402L");
 ^~~~~~~~~~~~~
In file included from /home/fbthrift/thrift/lib/cpp/Thrift.h:20:0,
                 from /home/fbthrift/thrift/lib/cpp/Thrift.cpp:21:
/usr/local/include/folly/Range.h:522:12: error: 'std::enable_if_t' has not been declared
       std::enable_if_t<
            ^~~~~~~~~~~
/usr/local/include/folly/Range.h:522:23: error: expected '>' before '<' token
       std::enable_if_t<
                       ^
/usr/local/include/folly/Range.h:532:12: error: 'std::enable_if_t' has not been declared
       std::enable_if_t<
            ^~~~~~~~~~~
/usr/local/include/folly/Range.h:532:23: error: expected '>' before '<' token
       std::enable_if_t<
                       ^
/usr/local/include/folly/Range.h:537:22: error: 'template<class Iter> template<class Tgt, <typeprefixerror><anonymous> > constexpr folly::Range<Iter>::operator Tgt() const' cannot be overloaded
   constexpr explicit operator Tgt() const noexcept(
                      ^~~~~~~~
/usr/local/include/folly/Range.h:526:22: error: with 'template<class Iter> template<class Tgt, <typeprefixerror><anonymous> > constexpr folly::Range<Iter>::operator Tgt() const'
   constexpr explicit operator Tgt() const noexcept(

**Comment by vitaut** [comment]
> i am sure __cplusplus == 201402L

Well, the compiler says otherwise:

```
/usr/local/include/folly/Portability.h:22:1: error: static assertion failed: __cplusplus >= 201402L
```
Folly requires a C++14-capable compiler.
