### ISSUE TITLE
make error with gcc 7.4 in ubuntu 18.04

### ISSUE THREAD

**Issue by silveric10** [facebook/fbthrift#338]
I use ubuntu 18.04 and gcc version is 7.4. I can build folly successfully. But when I make thrift, those errors will occur.
Scanning dependencies of target thrift-core
[ 40%] Building CXX object thrift/lib/cpp/CMakeFiles/thrift-core.dir/Thrift.cpp.o
In file included from /usr/local/include/folly/Range.h:22:0,
from /home/yy/openr/build/deps/fbthrift/thrift/lib/cpp/Thrift.h:20,
from /home/yy/openr/build/deps/fbthrift/thrift/lib/cpp/Thrift.cpp:21:
/usr/local/include/folly/Portability.h:22:1: error: static assertion failed: __cplusplus >= 201402L
static_assert(__cplusplus >= 201402L, "__cplusplus >= 201402L");
^~~~~~~~~~~~~
In file included from /home/yy/openr/build/deps/fbthrift/thrift/lib/cpp/Thrift.h:20:0,
from /home/yy/openr/build/deps/fbthrift/thrift/lib/cpp/Thrift.cpp:21:
/usr/local/include/folly/Range.h:522:12: error: ‘std::enable_if_t’ has not been declared
std::enable_if_t<
^~~~~~~~~~~
/usr/local/include/folly/Range.h:522:23: error: expected ‘>’ before ‘<’ token
std::enable_if_t<
^
/usr/local/include/folly/Range.h:532:12: error: ‘std::enable_if_t’ has not been declared
std::enable_if_t<
^~~~~~~~~~~
/usr/local/include/folly/Range.h:532:23: error: expected ‘>’ before ‘<’ token
std::enable_if_t<
I know that is because I did not use c++14 compiler, but how? I already add added "_compile_options(-std=c++14)" to the CMakeList.txt. My gcc version is 7.4 and it should be c++14 compiler.

**Comment by AhmedSoliman** [comment]
I'm seeing the same issue while building LogDevice with the same compiler.

**Comment by AhmedSoliman** [comment]
Looking into the c++ command, something is adding `-std=c++11` along with the `-std=gnu++14` which I presume confuses the compiler and it decides to go with the lowest denominator.

```
/usr/bin/c++  -DGFLAGS_IS_A_DLL=0 -DTHRIFT_HAVE_LIBSNAPPY=0 -I/home/ubuntu/LogDevice-deps-fixes/logde
vice/external/fbthrift -I/home/ubuntu/LogDevice-deps-fixes/logdevice/_build/fbthrift-prefix/src/fbthrift-build -isystem /home/ubuntu/LogDevice-deps-fixes/logdevice/_build/staging/usr/local/include -isystem /u
sr/include/libdwarf -isystem /usr/include/libiberty  -std=gnu++14 -fPIC   -pthread -std=gnu++11 -o CMakeFiles/thrift-core.dir/Thrift.cpp.o -c /home/ubuntu/LogDevice-deps-fixes/logdevice/external/fbthrift/thri
ft/lib/cpp/Thrift.cpp
```

**Comment by AhmedSoliman** [comment]
It turns out that it's because of "fmt". Since fbthrift depends on Fmt::fmt, The build works if I comment this line in fmt/CMakeLists.txt
```
set(FMT_REQUIRED_FEATURES cxx_auto_type cxx_variadic_templates)
```

**Comment by AhmedSoliman** [comment]
Ok, it seems that passing `-DCMAKE_CXX_STANDARD=17` to the fbthrift build forces cmake to pick C++17 rather than guessing and that worked for me.

**Comment by berserkr** [comment]
I get: error: no matching function for call to ‘bit_cast(unsigned char&)’ ... this is a `folly` issue, setting `-DCMAKE_CXX_STANDARD=14` fixed it for me as well.

**Comment by vitaut** [comment]
This was an issue in Folly's CMake config which was fixed in https://github.com/facebook/folly/commit/240c15930ae8c08f1c81bef0a3ba7f90b97ee3eb. Thanks for reporting.
