### ISSUE TITLE
Change except to catch ImportError. 

### ISSUE THREAD

**Issue by farziengineer** [facebook/fbthrift#339]
https://github.com/facebook/fbthrift/blob/71d08faff124f0705e28fb45a95c2e7e0edea0ce/thrift/compiler/test/fixtures/basic/gen-py/module/MyServiceEmpty.py#L30-L33

Can this be changed to, in order to make it more explicit:
```python
  try:
    from thrift.protocol import fastproto
  except ImportError as e:
    print(e)
```
Can I raise a PR for this

**Comment by yfeldblum** [comment]
This change could cause programs which work properly right now to start spamming stdout. That is not desirable.
