### ISSUE TITLE
Cannot compile under Slackware64

### ISSUE THREAD

**Issue by CriztianiX** [facebook/fbthrift#34]
Trying to compile under slackware64 14.1 i get:

../lib64 -L/usr/lib/../lib64 -L/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/lib -L/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../.. /usr/lib64/../lib64/libstdc++.so -lm -lc -lgcc_s /usr/lib64/gcc/x86_64-slackware-linux/4.8.2/crtendS.o /usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../lib64/crtn.o    -pthread -Wl,-soname -Wl,frontend.so -o .libs/frontend.so
../.libs/libparse.a(libparse_la-thriftl.o):(.data+0x4): multiple definition of `y_field_val'
../.libs/libparse.a(libparse_la-thrifty.o):(.data+0x0): first defined here
../.libs/libparse.a(libparse_la-thriftl.o):(.data+0x8): multiple definition of `y_enum_val'
../.libs/libparse.a(libparse_la-thrifty.o):(.data+0x4): first defined here
../.libs/libparse.a(libparse_la-thriftl.o):(.bss+0x2028): multiple definition of `g_arglist'
../.libs/libparse.a(libparse_la-thrifty.o):(.bss+0x0): first defined here
../.libs/libparse.a(libparse_la-thriftl.o):(.bss+0x202c): multiple definition of `yychar'
../.libs/libparse.a(libparse_la-thrifty.o):(.bss+0x4): first defined here
../.libs/libparse.a(libparse_la-thriftl.o):(.bss+0x2030): multiple definition of `yylval'
../.libs/libparse.a(libparse_la-thrifty.o):(.bss+0x10): first defined here
../.libs/libparse.a(libparse_la-thriftl.o):(.bss+0x2040): multiple definition of `yynerrs'
../.libs/libparse.a(libparse_la-thrifty.o):(.bss+0x20): first defined here
../.libs/libparse.a(libparse_la-thriftl.o): In function `yyparse()':
thriftl.cc:(.text+0x24): multiple definition of `yyparse()'
../.libs/libparse.a(libparse_la-thrifty.o):thrifty.cc:(.text+0x24): first defined here
collect2: error: ld returned 1 exit status
make[4]: *** [frontend.la] Error 1
make[4]: se sale del directorio `/usr/src/build/fbthrift/thrift/compiler/py'
make[3]: *** [all-recursive] Error 1
make[3]: se sale del directorio `/usr/src/build/fbthrift/thrift/compiler'
make[2]: *** [all] Error 2
make[2]: se sale del directorio `/usr/src/build/fbthrift/thrift/compiler'
make[1]: *** [all-recursive] Error 1
make[1]: se sale del directorio `/usr/src/build/fbthrift/thrift'
make: *** [all] Error 2

**Comment by andrewcox** [comment]
We only support building on ubuntu 13 or 14.

We'll be happy to take patches that make it build on other distros, but we don't support them.
