### ISSUE TITLE
How can i check out which version of fbthrift installed?

### ISSUE THREAD

**Issue by laura-ding** [facebook/fbthrift#341]
Can I get the version info of fbthrift from the command binary file? 
I want to see which version of fbthrift installed in the current system.
But I don't see any `-version` or `-V` command option included.

**Comment by yfeldblum** [comment]
The version is effectively "master." We have non-intrusive weekly tags, but those don't actually update anything in the repo (e.g. there is no version file that gets updated alongside the weekly tag).

**Comment by laura-ding** [comment]
Thank you very much! @yfeldblum
