### ISSUE TITLE
Please provide a specific version of folly, wang, fizz dependency

### ISSUE THREAD

**Issue by prehistoric-penguin** [facebook/fbthrift#342]
Since these facebook libraries are keeping change their API, it's hard to build fbthrift if we don't know which version to use and I have faced several  build errors caused by API incapable these days.

Please add a explicit dependency file to say which version of folly, wangle and fizz to use. Something like the go.mod file will be welcome.

**Comment by yfeldblum** [comment]
Either use all the projects at the same weekly tag, or check the dep hashes at https://github.com/facebook/fbthrift/tree/master/build/deps/github_hashes/facebook.
