### ISSUE TITLE
Generated PHP classes from structs produce public fields, make them private

### ISSUE THREAD

**Issue by 2DSharp** [facebook/fbthrift#352]
The PHP autogenerated code currently keeps the struct derived class attributes public, and they have to be accessed like: $class->field.

The java version keeps them private instead and uses getters and setters to access and mutate the data.

A similar approach would be a better choice for most oop based php coding standards.

**Comment by vitaut** [comment]
Closing per https://github.com/facebook/fbthrift/pull/353#issuecomment-803118707.
