### ISSUE TITLE
how to build Python3 using mstch_py3:include_prefix

### ISSUE THREAD

**Issue by darionyaphet** [facebook/fbthrift#354]
Hi experts:

When I try to compile thrift file into python3 source code, using the follow command: 

`bin/thrift1  --strict --allow-neg-enum-vals --gen mstch_py3:include_prefix="interface"  -o . test.thrift`

It seems `Must set template directory when using mstch generator`. 

But I can't find it. thanks a lot :)

**Comment by yfeldblum** [comment]
Is this still a problem after f9e97df0a4f2357030c86446374df58a6914c3f3?

**Comment by darionyaphet** [comment]
@yfeldblum thanks ! Do you fix it in this PR . Actually, we are using `v-2018.08.20`
