### ISSUE TITLE
How to compile a thrift configuration file for python to use?

### ISSUE THREAD

**Issue by song3134** [facebook/fbthrift#357]
How to compile a thrift configuration file with current master branch library for python to use? I'm a fb outside user using linux ubuntu 16.04 and have installed the library. I now can import thrift in python and write the configuration thrift but don't know how to compile the thrift file in order to import the ''ttypes'' for python to use. Any suggestions? Thanks a lot!

**Comment by yfeldblum** [comment]
Build the Thrift compiler and run it, passing in `--gen py` and the `.thrift` file as arguments. It generates Python files into `gen-py/` that can then be imported by other Python code.

**Comment by song3134** [comment]
Thanks!
