### ISSUE TITLE
cpp2 generated incorrect header include

### ISSUE THREAD

**Issue by zjzzjz1979** [facebook/fbthrift#359]
`thrift1 --gen mstch_cpp2 -I . -o . abc.thrift`

The generated abc_types.cpp is like this

`#include "/gen-cpp2/abs_type.h"`

If I do
   `thrift1 --gen mstch_cpp2 -I . -out /tmp abc.thrift`
The generated code /tmp/abc_types.cpp still includes header files like the above.

Should `#include "/gen-cpp2/abs_type.h"` be `#include "gen-cpp2/abs_type.h"` ?

Did I miss anything?

**Comment by korena** [comment]
@zjzzjz1979 this is old .. but for those unfortunate enough to miss this, you should use something like:
`thrift1 -r --gen mstch_cpp2:include_prefix=/path/to/prefix/`

Which would produce includes of the form:

`#include "/path/to/prefix/gen-cpp2/abs_type.h"`

**Comment by jievince** [comment]
@korena Hi korena, what is the difference between lib cpp2 and lib cpp?
![image](https://user-images.githubusercontent.com/38901892/95814169-52a2ab00-0d4c-11eb-8d0e-e2dc32566bbc.png)

**Comment by korena** [comment]
@jievince I'm not sure, seems like a fork to restructure cmake build for thrift .. the commit messages  don't give much context, This is something someone from facebook can probably answer, I use cpp2 exclusively, because it has "2", no other reason ..
