### ISSUE TITLE
where is pom.xml of the java lib?

### ISSUE THREAD

**Issue by zjzzjz1979** [facebook/fbthrift#364]
pom.xml got removed by the diff
https://github.com/facebook/fbthrift/commit/68319a4cdecd377aabdb21f7c03a7dfd69f2f61a#diff-b72667de80c1ca805f2fad2505ec72f1

after the removal, how do we build it...?

**Comment by stevegury** [comment]
@zjzzjz1979 Unfortunately, this code is only buildable with Facebook internal build system "Buck".
Buck itself is open-sourced (https://buck.build/) but the build files are full of internal references which would make it impossible to use outside of Facebook.
