### ISSUE TITLE
Build fails on macOS Catalina

### ISSUE THREAD

**Issue by pradeep-epic** [facebook/fbthrift#370]
Just tried the build on Catalina and I get this error

`In file included from /Users/pbanavara/dev/proxygen/proxygen/_build/deps/folly/folly/memory/Malloc.h:43:
/Users/pbanavara/dev/proxygen/proxygen/_build/deps/folly/folly/memory/detail/MallocImpl.h:51:6: error: redefinition of 'mallctlbymib' as different kind of symbol
    *mallctlbymib)(const size_t*, size_t, void*, size_t*, void*, size_t);
     ^
/usr/local/include/jemalloc/jemalloc.h:252:38: note: previous definition is here
JEMALLOC_EXPORT int JEMALLOC_NOTHROW    je_mallctlbymib(const size_t *mib,
                                        ^
/usr/local/include/jemalloc/jemalloc.h:64:27: note: expanded from macro 'je_mallctlbymib'
#  define je_mallctlbymib mallctlbymib
                          ^
In file included from /Users/pbanavara/dev/proxygen/proxygen/_build/deps/folly/folly/Conv.cpp:17:
In file included from /Users/pbanavara/dev/proxygen/proxygen/_build/deps/folly/folly/Conv.h:116:
In file included from /Users/pbanavara/dev/proxygen/proxygen/_build/deps/folly/folly/Demangle.h:19:
In file included from /Users/pbanavara/dev/proxygen/proxygen/_build/deps/folly/folly/FBString.h:48:
`
So looks like a redefinition of mallctlbymib  and the original mallctlbymib is  in /usr/local/include/jemalloc/jemalloc.h . Not sure. Are there any version dependencies that I am missing ?

**Comment by yfeldblum** [comment]
Closing due to age.
