### ISSUE TITLE
How can I use Dns name construct AsyncSocket?

### ISSUE THREAD

**Issue by knightXun** [facebook/fbthrift#371]
Hi guys, We use fbthrift in k8s,but pod is not stable in k8s, thy ip is not stable, but dns is stable. So how can i use dns name instead of ip to constuct asyncsocket?

**Comment by knightXun** [comment]
ping @yns88

**Comment by soyuzzzZ** [comment]
@knightXun the TAsyncSocket class definition has no member function that takes a hostname as an argument. See https://github.com/facebook/fbthrift/blob/e2e13157e15ed3541352e3c8075ff7d9e2dc947f/thrift/lib/cpp/async/TAsyncSocket.h#L29-L85

I'd say just resolve the hostname before you create the async socket.

**Comment by knightXun** [comment]
@soyuzzzZ That's Not suitable in k8s. Because Pod IP will always changes in k8s. I thought fbthrift had better take dns-name construct Socket. Grpc already did this.

**Comment by yfeldblum** [comment]
What do you mean about stability? What happens when your code queries dns for an ip address and then uses the ip address?

**Comment by knightXun** [comment]
@yfeldblum  We deploy apps in k8s. App will be a Pod in k8s. Pods'IP is not stable in K8s, But Pod dns name can be stable. If Kubernetes Evict or Kill a app Pod for some reason, Kubernetes Controller Will Construct a New Pod. The New Pod will continue the same task of the dead pod ahead. We could mark the new and old pod as the same dns name to continue the app service.

**Comment by soyuzzzZ** [comment]
@knightXun there's no way around it. Every time you need to connect to your pod, you must resolve the DNS name to get the correct IP and then pass it to the client.

**Comment by knightXun** [comment]
@soyuzzzZ can fbthrift auto resolve dns when we use fbthrift client? I thought this is very common needs in cloud-native environments.

**Comment by yfeldblum** [comment]
The only two ways this can work are:
* you give X a DNS name and X resolves it to an IP address and uses that IP address
* you resolve a DNS name to an IP address and give X that IP address

Not sure yet why it is terribly important that fbthrift does it.

Anyway, `SocketAddress` has a constructor that takes a DNS name and a port and that immediately resolves the name to an IP address. Note though that it does not keep the DNS name around.

**Comment by knightXun** [comment]
@yfeldblum I notice Envoy has a proxy for thrift,  Maybe this can be fixed by side-car like envoy. I ask help for them about this later.

**Comment by knightXun** [comment]
@yfeldblum hi, I find a dns-resolver in https://github.com/etcd-io/etcd/blob/a96bc4826872d61aa6451dc8044d818094311b26/vendor/google.golang.org/grpc/resolver/dns/dns_resolver.go#L106, this dns-resolver will auto resolver dns at regular intervals. I think it's better to realize it in fbthrift.

**Comment by knightXun** [comment]
@yfeldblum

**Comment by yfeldblum** [comment]
I don't think this is a feature that fbthrift necessarily needs to provide since you can provide it on top for your use-case.

Check out `ReconnectingRequestChannel` for an example of how to do it. Your code would extend on that by doing a new DNS lookup before reconnecting.
