### ISSUE TITLE
How to use async python client

### ISSUE THREAD

**Issue by laura-ding** [facebook/fbthrift#372]
I have used thrift1 to generate python client code, but I can't find the async interface in the code. And I use `asyncio`, but they still work synchronously. Could you give me some examples to use it? Thanks very much!

**Comment by rhodo** [comment]
Here is the generated code example for your reference https://github.com/facebook/fbthrift/tree/master/thrift/compiler/test/fixtures/pyi

**Comment by laura-ding** [comment]
> Here is the generated code example for your reference https://github.com/facebook/fbthrift/tree/master/thrift/compiler/test/fixtures/pyi

@rhodo Thanks very much!
