### ISSUE TITLE
How to use the interface which through py:asyncio generate

### ISSUE THREAD

**Issue by laura-ding** [facebook/fbthrift#373]
This is the generated code 
![image](https://user-images.githubusercontent.com/48548375/71774404-f9317280-2fa8-11ea-9166-2efadc10a4d1.png)

I don't know how to use them, why the `execute` function not call the `recv_execute` function.
Can someone help me? Thanks very much!

**Comment by laura-ding** [comment]
Which version support mstch_py3? I use the version `2018.08.20.00`, and I can't see the setup.py under directory `thrift/lib/py3`.

**Comment by yfeldblum** [comment]
Closing because this is old.

In general, the application will override handler functions and not use `send` and `recv` functions directly.
