### ISSUE TITLE
Build instruction in README needs to be updated

### ISSUE THREAD

**Issue by dingxiangfei2009** [facebook/fbthrift#376]
If one follows the build instruction on a fresh Debian Buster install, with the dependencies built and installed, there is still one dependency missing, which is `python-six`.

`CMakeLists.txt` lists `python-six` as a CMake-configurable package, which is usually not the case for a `python-wheel`-configured package. In fact, `python-six` is downloaded and re-packaged by `fbcode_builder` into a CMake module.

That mandates an update on the actual working build instruction in `README.md`. The instruction should at least clearly show how `fbcode_builder` can be configured, with or without Docker builds, to trigger the build at alternative destinations other than in the `~/.fbcode_builder-<mangled-path>` directory: it is not a standard installation path in Debian.

**Comment by Todddt** [comment]
I've met this problem, too, in Ubuntu 18.04.4 LTS 

CMake Warning at CMakeLists.txt:134 (find_package):
  By not providing "Findpython-six.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "python-six", but CMake did not find one.

  Could not find a package configuration file provided by "python-six" with
  any of the following names:

    python-sixConfig.cmake
    python-six-config.cmake

  Add the installation prefix of "python-six" to CMAKE_PREFIX_PATH or set
  "python-six_DIR" to a directory containing one of the above files.  If
  "python-six" provides a separate development package or SDK, be sure it has
  been installed.


CMake Error at CMakeLists.txt:147 (message):
  Unable to find python-six, but building thrift/lib/py was requested


-- Configuring incomplete, errors occurred!

Can you tell me how to solve this problem?
I cant find python-sixConfig.cmake

**Comment by nankedr** [comment]
@Todddt 
I've met the same problem in window 10 wsl2 (debian)
Have you already solve the problem? Can you tell me the solution?

**Comment by phwd** [comment]
Anyone else reach here there is a build script in fbcode_builder, use it to build the six project, that will generate six cmake file  which is referenced as the OP mentioned in the fbcode_builder-<mangled-path> . You can then supply it as a path option on cmake

**Comment by mbasmanova** [comment]
@phwd Would you clarify how to build six project? I see lots of scripts in fbcode_builder directory, but not sure which one to use and how.

$ ls -l
total 248
drwxr-xr-x  24 mbasmanova  staff    768 Feb 23 17:57 CMake
-rw-r--r--   1 mbasmanova  staff   1086 Feb 23 17:57 LICENSE
-rw-r--r--   1 mbasmanova  staff   1510 Feb 23 17:57 README.docker
-rw-r--r--   1 mbasmanova  staff   1945 Feb 23 17:57 README.md
-rwxr-xr-x   1 mbasmanova  staff   7542 Feb 23 17:57 docker_build_with_ccache.sh
-rw-r--r--   1 mbasmanova  staff   7671 Feb 23 17:57 docker_builder.py
-rwxr-xr-x   1 mbasmanova  staff    459 Feb 23 17:57 docker_enable_ipv6.sh
-rw-r--r--   1 mbasmanova  staff  17610 Feb 23 17:57 fbcode_builder.py
-rw-r--r--   1 mbasmanova  staff    454 Feb 23 17:57 fbcode_builder_config.py
drwxr-xr-x  19 mbasmanova  staff    608 Feb 23 17:57 getdeps
-rwxr-xr-x   1 mbasmanova  staff  39057 Feb 23 17:57 getdeps.py
-rwxr-xr-x   1 mbasmanova  staff   6474 Feb 23 17:57 make_docker_context.py
drwxr-xr-x  87 mbasmanova  staff   2784 Feb 23 17:57 manifests
-rw-r--r--   1 mbasmanova  staff   2821 Feb 23 17:57 parse_args.py
-rw-r--r--   1 mbasmanova  staff   3710 Feb 23 17:57 shell_builder.py
-rw-r--r--   1 mbasmanova  staff   3237 Feb 23 17:57 shell_quoting.py
drwxr-xr-x  17 mbasmanova  staff    544 Feb 23 17:57 specs
-rwxr-xr-x   1 mbasmanova  staff   1515 Feb 23 17:57 travis_docker_build.sh
-rw-r--r--   1 mbasmanova  staff   2883 Feb 23 17:57 utils.py

**Comment by jbroll** [comment]
@Masha - Do something like this:

cd build/fbcode_builder && ./getdeps.py build python-six

**Comment by bdhobare** [comment]
Set of commands I used for anyone still not sure:
- `./fbthrift/build/fbcode_builder/getdeps.py build python-six` : Note the mangled path from here.
-  `export PYTHON_SIX_PATH = <mangled_path>`
-  Open CMakeLists.txt and edit this line `find_package(python-six)` to `find_package(python-six PATHS $ENV{PYTHON_SIX_PATH} NO_DEFAULT_PATH)`
- `cmake --build .`

**Comment by ahornby** [comment]
Updated the instructions to reference the getdeps.py build tool
