### ISSUE TITLE
Support for C# / .NET?

### ISSUE THREAD

**Issue by emmenlau** [facebook/fbthrift#379]
Are there plans to add support for C#, for example via .NET Standard?

**Comment by vitaut** [comment]
Thrift already has a C# code generator: https://github.com/facebook/fbthrift/blob/master/thrift/compiler/generate/t_csharp_generator.cc

**Comment by emmenlau** [comment]
> Thrift already has a C# code generator: https://github.com/facebook/fbthrift/blob/master/thrift/compiler/generate/t_csharp_generator.cc

But does that not require also a C# library for writing server and client? I could not see anything related to C# in https://github.com/facebook/fbthrift/tree/master/thrift/lib/, or am I on the wrong track here?

**Comment by vitaut** [comment]
fbthrift doesn't provide a runtime library for C# and there are no plans to add it in the near future. However you could try Apache Thrift instead.

**Comment by emmenlau** [comment]
thanks @vitaut! But would an Apache Thrift C# client work with an fbthrift server? I've seen the compatibility discussion in https://github.com/facebook/fbthrift/issues/83 but its dated from 2015...

**Comment by vitaut** [comment]
Older transports such as framed should be compatible between Apache Thrift and fbthrift but I have not experience using Thrift in C# so this is mostly an informed guess.

**Comment by jievince** [comment]
> fbthrift doesn't provide a runtime library for C# and there are no plans to add it in the near future. However you could try Apache Thrift instead.

@vitaut Hi vitaut, I am very confused. If the C# library is not supported, how can the generated C# be used?

**Comment by vitaut** [comment]
You could use the generated data types for something but neither serialization not RPC is provided. That's why I'm suggesting 

> try Apache Thrift instead

We don't plan to support C#.

**Comment by Cloud33** [comment]
What a sad decision
