### ISSUE TITLE
Make error - RocketServerConnection.cpp:286:9: internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by physician85** [facebook/fbthrift#380]
Error while make on Ubuntu on Windows:

`/root/build/fbthrift/thrift/lib/cpp2/transport/rocket/server/RocketServerConnection.cpp: In instantiation of ‘apache::thrift::rocket::RocketServerConnection::handleUntrackedFrame(std::unique_ptr<folly::IOBuf>, apache::thrift::rocket::StreamId, apache::thrift::rocket::FrameType, apache::thrift::rocket::Flags, folly::io::Cursor)::<lambda(auto:88&)> [with auto:88 = apache::thrift::rocket::RequestChannelFrame]’:
/usr/include/boost/variant/detail/apply_visitor_unary.hpp:120:31:   recursively required from ‘static decltype(auto) boost::detail::variant::result_multideduce1<Visitor, Variant>::deduce_impl(It, unsigned int) [with It = boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<3l>, apache::thrift::rocket::RequestFnfFrame, boost::mpl::l_item<mpl_::long_<2l>, apache::thrift::rocket::RequestStreamFrame, boost::mpl::l_item<mpl_::long_<1l>, apache::thrift::rocket::RequestChannelFrame, boost::mpl::l_end> > > >; Visitor = const folly::detail::Overload<apache::thrift::rocket::RocketServerConnection::handleUntrackedFrame(std::unique_ptr<folly::IOBuf>, apache::thrift::rocket::StreamId, apache::thrift::rocket::FrameType, apache::thrift::rocket::Flags, folly::io::Cursor)::<lambda(auto:88&)> >; Variant = boost::variant<apache::thrift::rocket::RequestResponseFrame, apache::thrift::rocket::RequestFnfFrame, apache::thrift::rocket::RequestStreamFrame, apache::thrift::rocket::RequestChannelFrame>]’
/usr/include/boost/variant/detail/apply_visitor_unary.hpp:120:31:   required from ‘static decltype(auto) boost::detail::variant::result_multideduce1<Visitor, Variant>::deduce_impl(It, unsigned int) [with It = boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<4l>, apache::thrift::rocket::RequestResponseFrame, boost::mpl::l_item<mpl_::long_<3l>, apache::thrift::rocket::RequestFnfFrame, boost::mpl::l_item<mpl_::long_<2l>, apache::thrift::rocket::RequestStreamFrame, boost::mpl::l_item<mpl_::long_<1l>, apache::thrift::rocket::RequestChannelFrame, boost::mpl::l_end> > > > >; Visitor = const folly::detail::Overload<apache::thrift::rocket::RocketServerConnection::handleUntrackedFrame(std::unique_ptr<folly::IOBuf>, apache::thrift::rocket::StreamId, apache::thrift::rocket::FrameType, apache::thrift::rocket::Flags, folly::io::Cursor)::<lambda(auto:88&)> >; Variant = boost::variant<apache::thrift::rocket::RequestResponseFrame, apache::thrift::rocket::RequestFnfFrame, apache::thrift::rocket::RequestStreamFrame, apache::thrift::rocket::RequestChannelFrame>]’
/usr/include/boost/variant/detail/apply_visitor_unary.hpp:127:27:   required from ‘static decltype(auto) boost::detail::variant::result_multideduce1<Visitor, Variant>::deduce() [with Visitor = const folly::detail::Overload<apache::thrift::rocket::RocketServerConnection::handleUntrackedFrame(std::unique_ptr<folly::IOBuf>, apache::thrift::rocket::StreamId, apache::thrift::rocket::FrameType, apache::thrift::rocket::Flags, folly::io::Cursor)::<lambda(auto:88&)> >; Variant = boost::variant<apache::thrift::rocket::RequestResponseFrame, apache::thrift::rocket::RequestFnfFrame, apache::thrift::rocket::RequestStreamFrame, apache::thrift::rocket::RequestChannelFrame>]’
/usr/include/boost/variant/detail/apply_visitor_unary.hpp:134:67:   required from ‘struct boost::detail::variant::result_wrapper1<const folly::detail::Overload<apache::thrift::rocket::RocketServerConnection::handleUntrackedFrame(std::unique_ptr<folly::IOBuf>, apache::thrift::rocket::StreamId, apache::thrift::rocket::FrameType, apache::thrift::rocket::Flags, folly::io::Cursor)::<lambda(auto:88&)> >, boost::variant<apache::thrift::rocket::RequestResponseFrame, apache::thrift::rocket::RequestFnfFrame, apache::thrift::rocket::RequestStreamFrame, apache::thrift::rocket::RequestChannelFrame> >’
/usr/include/boost/variant/detail/apply_visitor_unary.hpp:165:71:   required from ‘decltype(auto) boost::apply_visitor(const Visitor&, Visitable&, typename boost::disable_if<boost::detail::variant::has_result_type<Visitor> >::type*) [with Visitor = folly::detail::Overload<apache::thrift::rocket::RocketServerConnection::handleUntrackedFrame(std::unique_ptr<folly::IOBuf>, apache::thrift::rocket::StreamId, apache::thrift::rocket::FrameType, apache::thrift::rocket::Flags, folly::io::Cursor)::<lambda(auto:88&)> >; Visitable = boost::variant<apache::thrift::rocket::RequestResponseFrame, apache::thrift::rocket::RequestFnfFrame, apache::thrift::rocket::RequestStreamFrame, apache::thrift::rocket::RequestChannelFrame>; typename boost::disable_if<boost::detail::variant::has_result_type<Visitor> >::type = void]’
/usr/local/include/folly/Overload.h:75:23:   required from ‘decltype(auto) folly::variant_match(Variant&&, Cases&& ...) [with Variant = boost::variant<apache::thrift::rocket::RequestResponseFrame, apache::thrift::rocket::RequestFnfFrame, apache::thrift::rocket::RequestStreamFrame, apache::thrift::rocket::RequestChannelFrame>&; Cases = {apache::thrift::rocket::RocketServerConnection::handleUntrackedFrame(std::unique_ptr<folly::IOBuf>, apache::thrift::rocket::StreamId, apache::thrift::rocket::FrameType, apache::thrift::rocket::Flags, folly::io::Cursor)::<lambda(auto:88&)>}]’
/root/build/fbthrift/thrift/lib/cpp2/transport/rocket/server/RocketServerConnection.cpp:291:8:   required from here
/root/build/fbthrift/thrift/lib/cpp2/transport/rocket/server/RocketServerConnection.cpp:286:9: internal compiler error: Segmentation fault
         if (!hasFollows) {
         ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/build.make:1022: recipe for target 'thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/transport/rocket/server/RocketServerConnection.cpp.o' failed
make[2]: *** [thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/transport/rocket/server/RocketServerConnection.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1005: recipe for target 'thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/all' failed
make[1]: *** [thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by vitaut** [comment]
This is a bug in gcc, not thrift. Please submit a bug report there as the error message suggests.

**Comment by physician85** [comment]
@vitaut what version of GCC do I need to compile this?

**Comment by vitaut** [comment]
I recommend using GCC 7 or later.

**Comment by xiaohe-real** [comment]
> @vitaut what version of GCC do I need to compile this?

it works to me by changing
"const bool hasFollows = payloadFrame.hasFollows();"　just above "if (!hasFollows)"
into "bool hasFollows = payloadFrame.hasFollows();"

**Comment by xiaohe-real** [comment]
@vitaut yes, it helps

**Comment by vitaut** [comment]
What gcc version do you use?

**Comment by vitaut** [comment]
Worked around in https://github.com/facebook/fbthrift/commit/08752f0c237b6c62cc977ba545fdb865a8554d27.

**Comment by xiaohe-real** [comment]
@vitaut gcc version 5.4.0 20160609
