### ISSUE TITLE
Build error in Linux

### ISSUE THREAD

**Issue by NoobSolver** [facebook/fbthrift#387]
Just tried the build on Catalina and I get this error

`In file included from /Users/pbanavara/dev/proxygen/proxygen/_build/deps/folly/folly/memory/Malloc.h:43:

/Users/pbanavara/dev/proxygen/proxygen/_build/deps/folly/folly/memory/detail/MallocImpl.h:51:6:
 error: redefinition of 'mallctlbymib' as different kind of symbol
mallctlbymib)(const size_t, size_t, void*, size_t*, void*, size_t);
^
/usr/local/include/jemalloc/jemalloc.h:252:38: note: previous definition is here
JEMALLOC_EXPORT int JEMALLOC_NOTHROW
 je_mallctlbymib(const size_t *mib,
^
/usr/local/include/jemalloc/jemalloc.h:64:27: note: expanded from macro 'je_mallctlbymib'

**Comment by yfeldblum** [comment]
Closing due to age.
