### ISSUE TITLE
Documentation/Clarification

### ISSUE THREAD

**Issue by blackencino** [facebook/fbthrift#388]
Hello FB Thrift Team - 

I'm a former FB employee who used thrift during my employment there, and I'm a big fan of it. 

It's hard to determine from the documentation and examples whether it's possible to do the following very core thing. Assuming I build from source, and using the compiled thrift1 compiler, if I compile a thrift file into javascript, is it possible to execute this code from a browser on the client side to communicate to an fbthrift server running at some IP:port, which was compiled from C++? I would be using webpack to package up the javascript module, which allows me to expose node modules to the browser.

In theory this should be a no-brainer, because as a friend and fellow FB colleague pointed out, "isn't that the whole point of Thrift?". However I have been dismayed to discover that gRPC+Protobuf, the analogous offering from Google, does NOT allow for the above, because gRPC uses HTTP2 and browsers don't support this, so you need to run an Envoy proxy server to convert HTTP2 to HTTP in order to use grpc-web. The resulting communication is slow, and the management of the proxy server is a pain.

This would be a great hello-world tutorial, if it is indeed possible to do this with fbthrift.

**Comment by yfeldblum** [comment]
Thrift is not currently targeted at the browser. It is generally targeted at backend services communicating with each other.

Isn't that the whole point of Thrift? To extend not just within the datacenter but across all types of heterogeneous deployments? Well, maybe. I can see why one might want that to be the case. But that's not really where Thrift is.

JavaScript code running in the browser can only do what the browser permits. If the browser does not permit HTTP2, then it certainly would not permit arbitrary other network protocols that are not even any version of HTTP.

**Comment by blackencino** [comment]
Thank you! I appreciate the prompt response.

**Comment by blackencino** [comment]
I will dispute one point, though: Thrift (Apache Thrift) clearly sees this as a use case, as they provide an example of exactly this, a browser-based Client and Server.

http://thrift.apache.org/lib/js

**Comment by yfeldblum** [comment]
You are right that Apache Thrift sees JS clients as a use-case it targets. I was only speaking for FB Thrift, which, given that we all have to make hard choices regarding what we work on, has a narrower set of target use-cases.

Note that it looks like the Apache Thrift implementation for JS uses HTTP1.1 as the underlying network transport.
