### ISSUE TITLE
What is the difference between lib cpp2 and lib cpp?

### ISSUE THREAD

**Issue by jievince** [facebook/fbthrift#396]
![image](https://user-images.githubusercontent.com/38901892/95814221-6cdc8900-0d4c-11eb-9873-e4f0419b4475.png)
Which one should I choose if I want to make a C++ client?

**Comment by jievince** [comment]
@vitaut

**Comment by vitaut** [comment]
> Which one should I choose if I want to make a C++ client?

cpp2 (cpp is the old runtime)
