### ISSUE TITLE
[cpp2] Illegal codegen for union field of type unique ref to container

### ISSUE THREAD

**Issue by dutor** [facebook/fbthrift#406]
```thrift
union Value {
1: List lval (cpp.ref_type = "unique");
}
typedef list<Value> List
```

The deserialize part of the codegen is as:
```cpp
template <class Protocol_>
void Value::readNoXfer(Protocol_* iprot) {
    ...
    switch (_readState.fieldId) {
      case 1:
      {
        if (_readState.isCompatibleWithType(iprot, apache::thrift::protocol::T_LIST)) {
          this->set_lval();
          std::unique_ptr< ::cpp2::List> ptr = std::make_unique< ::cpp2::List>();
          this->mutable_lval() =  ::cpp2::List();  // Trying to assign a List to a std::unique_ptr<List>
          ...
          this->mutable_lval() = std::move(ptr);
          ...
        }
        ...
      }
      ...
    }
    ...
}
```

There is no such issue if `Value` were a `struct`

**Comment by Mizuchi** [comment]
This use case is unsupported. Is there a good reason to use unique ref here? Otherwise please consider using following code instead

```
union Value {
  1: list<Value> lval
}
```

**Comment by dutor** [comment]
@Mizuchi Thanks for the reply.

For this simple case, yes, I could use a `list` directly. But in my complete scenario, there are fields whose type are also `struct` and have `Value` field in themselves. Such as:
```thrift
struct Pair {
1: string key;
2: Value value;
}
union Value {
1: list<Value> lval;
2: Pair pval;
}
``` 
In this case, `pval` must be a pointer due to the cylic reference. At last, for the sake of consistency, we use unique ref for all  composite fields.

I think it makes no sense that only containers are not supported in such a use case.
