### ISSUE TITLE
best practice to return a future in a service callback

### ISSUE THREAD

**Issue by chanwai1219** [facebook/fbthrift#419]
Dear thrift team,

I'm testing with the chatroom example, the thrift compiler will generate something like below, I remove some irrelevant code to keep things clear.

```
class ChatRoomServiceSvAsyncIf {
 public:
  virtual void async_tm_getMessages(std::unique_ptr<apache::thrift::HandlerCallback<std::unique_ptr< ::example::chatroom::GetMessagesResponse>>> callback, std::unique_ptr< ::example::chatroom::GetMessagesRequest> p_req) = 0;
  virtual folly::Future<std::unique_ptr< ::example::chatroom::GetMessagesResponse>> future_getMessages(std::unique_ptr< ::example::chatroom::GetMessagesRequest> p_req) = 0;
  virtual folly::SemiFuture<std::unique_ptr< ::example::chatroom::GetMessagesResponse>> semifuture_getMessages(std::unique_ptr< ::example::chatroom::GetMessagesRequest> p_req) = 0;
};

class ChatRoomServiceAsyncProcessor;

class ChatRoomServiceSvIf : public ChatRoomServiceSvAsyncIf, public apache::thrift::ServerInterface {
 public:

  virtual void getMessages( ::example::chatroom::GetMessagesResponse& /*_return*/, std::unique_ptr< ::example::chatroom::GetMessagesRequest> /*req*/);
  folly::Future<std::unique_ptr< ::example::chatroom::GetMessagesResponse>> future_getMessages(std::unique_ptr< ::example::chatroom::GetMessagesRequest> p_req) override;
  folly::SemiFuture<std::unique_ptr< ::example::chatroom::GetMessagesResponse>> semifuture_getMessages(std::unique_ptr< ::example::chatroom::GetMessagesRequest> p_req) override;
  void async_tm_getMessages(std::unique_ptr<apache::thrift::HandlerCallback<std::unique_ptr< ::example::chatroom::GetMessagesResponse>>> callback, std::unique_ptr< ::example::chatroom::GetMessagesRequest> p_req) override;
};
```

My question is if I need to do a asynchronous operation in the service callback, which class should I override, ChatRoomServiceSvAsyncIf or ChatRoomServiceSvIf?
Can I do a future_get another RPC in ChatRoomServiceSvIf:: getMessages?
Or the right way is to implement ChatRoomServiceSvAsyncIf:: future_getMessages.

Thanks in advance.

BR

**Comment by yfeldblum** [comment]
Your handler class should in the normal case inherit `ChatRoomServiceSvIf`.

It is not recommended to use future_get within an asynchronous handler override. Instead, it is recommended to use asynchronous code using futures to chain callbacks together.

**Comment by chanwai1219** [comment]
Dear Jay,
Thanks for the reply. 
So if my understanding is right, if I need to call a external RPC in the service handler, I should override the ChatRoomServiceSvIf::future_getMessages function like this

```
folly::Future<std::unique_ptr< ::example::chatroom::GetMessagesResponse>> future_getMessages(std::unique_ptr< ::example::chatroom::GetMessagesRequest> p_req) {
  folly::Promise<std::unique_ptr< ::example::chatroom::GetMessagesResponse>> promise;
  auto future = promise.getFuture();

 // create a client try to get the real message back from another micro service
 auto futureMsg = client_->future_generateMessage();

 futureMsg.thenValue([promise = std::move(promise)](auto&& msg) mutable {
    promise.setValue(std::make_unique<::example::chatroom::GetMessagesResponse>(std::move(msg)));
  });

 return future;
}
```

The compiler generated ChatRoomServiceSvIf::future_getMessages is just used to wrap the synchronous ChatRoomServiceSvIf::getMessages result inside a future?

Do I misunderstand something above?

BR

**Comment by yfeldblum** [comment]
Yes, that will work, although that's more complicated than necessary.

```
folly::Future<std::unique_ptr<GetMessagesResponse>>
future_getMessages(std::unique_ptr<GetMessagesRequest>) {
 return client_->future_generateMessage()
      .thenValue([](auto&& msg) {
        return folly::copy_to_unique_ptr(std::move(msg));
      });
}
```

Note that `future_getMessages` is *not* "just used to wrap the synchronous [method]." Under the hood, at the present moment in time, it happens to be implemented that way. But the asynchronous method is there to be asynchronous.

**Comment by chanwai1219** [comment]
Dear Jay,
Thanks for the clear explanation.

BR
