### ISSUE TITLE
perf client build with coroutines, error building

### ISSUE THREAD

**Issue by domen55** [facebook/fbthrift#420]
I am trying to build perf binaries, server compiles, but client has some issues.
Does anyone else has this problem ? Or might explain what might be issue ?

Is it right that getAsyncFrame() is called when using CoroutineType = detail::ViaCoroutine<false>;

gcc is 10.2.0

> /usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DFMT_LOCALE -DFMT_SHARED -DGFLAGS_IS_A_DLL=0 -I/root/web_project/mojthrift -I/root/web_project/mojthrift/thrift/perf/cpp2 -isystem /tmp/build/install/include -isystem /tmp/build/gflags/include -isystem /usr/include/libiberty -march=native -mtune=native -ggdb3 -fcoroutines -std=c++17 -MD -MT CMakeFiles/testclient.dir/thrift/perf/cpp2/client/Client.cpp.o -MF CMakeFiles/testclient.dir/thrift/perf/cpp2/client/Client.cpp.o.d -o CMakeFiles/testclient.dir/thrift/perf/cpp2/client/Client.cpp.o -c /root/web_project/mojthrift/thrift/perf/cpp2/client/Client.cpp
In file included from /tmp/build/install/include/folly/experimental/coro/CurrentExecutor.h:23,
                 from /tmp/build/install/include/folly/experimental/coro/AsyncGenerator.h:24,
                 from /tmp/build/install/include/thrift/lib/cpp2/async/ServerStream.h:21,
                 from /tmp/build/install/include/thrift/lib/cpp2/async/ResponseChannel.h:29,
                 from /tmp/build/install/include/thrift/lib/cpp2/async/ReplyInfo.h:20,
                 from /tmp/build/install/include/thrift/lib/cpp2/async/AsyncProcessor.h:36,
                 from /tmp/build/install/include/thrift/lib/cpp2/gen/service_h.h:26,
                 from /root/web_project/mojthrift/thrift/perf/cpp2/if/gen-cpp2/StreamBenchmark.h:9,
                 from /root/web_project/mojthrift/thrift/perf/cpp2/client/Client.cpp:18:
/tmp/build/install/include/folly/experimental/coro/ViaIfAsync.h: In instantiation of âfolly::coro::ViaIfAsyncAwaiter<IsCallerAsyncStackAware, Awaitable>::await_suspend_result_t folly::coro::ViaIfAsyncAwaiter<IsCallerAsyncStackAware, Awaitable>::await_suspend(std::__n4861::coroutine_handle<P>) [with Promise = folly::coro::detail::ViaCoroutine<false>::promise_type; bool IsCallerAsyncStackAware = true; Awaitable = folly::fibers::Baton&; folly::coro::ViaIfAsyncAwaiter<IsCallerAsyncStackAware, Awaitable>::await_suspend_result_t = void; folly::coro::ViaIfAsyncAwaiter<IsCallerAsyncStackAware, Awaitable>::Awaiter = folly::fibers::detail::BatonAwaitableWaiter; folly::coro::ViaIfAsyncAwaiter<IsCallerAsyncStackAware, Awaitable>::WrapperHandle = std::__n4861::coroutine_handle<folly::coro::detail::ViaCoroutine<false>::promise_type>]â:
/tmp/build/install/include/folly/experimental/coro/ViaIfAsync.h:328:31:   required from âfolly::coro::ViaIfAsyncAwaiter<IsCallerAsyncStackAware, Awaitable>::await_suspend_result_t folly::coro::ViaIfAsyncAwaiter<IsCallerAsyncStackAware, Awaitable>::await_suspend(std::__n4861::coroutine_handle<P>) [with Promise = folly::coro::detail::TaskPromise<facebook::thrift::benchmarks::TwoInts>; bool IsCallerAsyncStackAware = true; Awaitable = folly::coro::StackAwareViaIfAsyncAwaitable<folly::fibers::Baton&>; folly::coro::ViaIfAsyncAwaiter<IsCallerAsyncStackAware, Awaitable>::await_suspend_result_t = void; folly::coro::ViaIfAsyncAwaiter<IsCallerAsyncStackAware, Awaitable>::Awaiter = folly::coro::ViaIfAsyncAwaiter<true, folly::fibers::Baton&>; folly::coro::ViaIfAsyncAwaiter<IsCallerAsyncStackAware, Awaitable>::WrapperHandle = std::__n4861::coroutine_handle<folly::coro::detail::ViaCoroutine<false>::promise_type>]â
/root/web_project/mojthrift/thrift/perf/cpp2/if/gen-cpp2/BenchmarkAsyncClient.h:219:7:   required from âfolly::coro::Task<facebook::thrift::benchmarks::TwoInts> facebook::thrift::benchmarks::BenchmarkAsyncClient::co_sum(apache::thrift::RpcOptions*, const facebook::thrift::benchmarks::TwoInts&) [with bool hasRpcOptions = false]â
/root/web_project/mojthrift/thrift/perf/cpp2/if/gen-cpp2/BenchmarkAsyncClient.h:192:25:   required from âfolly::coro::Task<facebook::thrift::benchmarks::TwoInts> facebook::thrift::benchmarks::BenchmarkAsyncClient::co_sum(const facebook::thrift::benchmarks::TwoInts&) [with int <anonymous> = 0]â
/root/web_project/mojthrift/thrift/perf/cpp2/util/SimpleOps.h:296:19:   required from âvoid CoSum<AsyncClient>::async(AsyncClient*, std::unique_ptr<apache::thrift::RequestCallback>) [with AsyncClient = facebook::thrift::benchmarks::StreamBenchmarkAsyncClient]â
/root/web_project/mojthrift/thrift/perf/cpp2/util/Operation.h:99:23:   required from âvoid Operation<AsyncClient>::async(OP_TYPE, std::unique_ptr<LoadCallback<AsyncClient> >) [with AsyncClient = facebook::thrift::benchmarks::StreamBenchmarkAsyncClient]â
/root/web_project/mojthrift/thrift/perf/cpp2/util/Runner.h:56:18:   required from âvoid Runner<AsyncClient>::run() [with AsyncClient = facebook::thrift::benchmarks::StreamBenchmarkAsyncClient]â
/root/web_project/mojthrift/thrift/perf/cpp2/client/Client.cpp:108:14:   required from here
/tmp/build/install/include/folly/experimental/coro/ViaIfAsync.h:311:62: error: no matching function for call to âfolly::coro::detail::ViaCoroutine<false>::promise_type::getAsyncFrame()â
  311 |       auto& asyncFrame = continuation.promise().getAsyncFrame();
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/tmp/build/install/include/folly/experimental/coro/ViaIfAsync.h:133:29: note: candidate: âtemplate<bool IsStackAware2, typename std::enable_if<IS_PACKED, int>::type <anonymous> > folly::AsyncStackFrame& folly::coro::detail::ViaCoroutine<IsStackAware>::promise_type::getAsyncFrame() [with bool IsStackAware2 = IsStackAware2; typename std::enable_if<X, int>::type <anonymous> = <anonymous>; bool IsStackAware = false]â
  133 |     folly::AsyncStackFrame& getAsyncFrame() noexcept {
      |                             ^~~~~~~~~~~~~
/tmp/build/install/include/folly/experimental/coro/ViaIfAsync.h:133:29: note:   template argument deduction/substitution failed:
/tmp/build/install/include/folly/experimental/coro/ViaIfAsync.h:132:48: error: no type named âtypeâ in âstruct std::enable_if<false, int>â
  132 |         std::enable_if_t<IsStackAware2, int> = 0>

**Comment by yfeldblum** [comment]
Since gcc's coroutine support is so new, we do not yet test fbthrift coroutines with gcc.
