### ISSUE TITLE
go lib throw "Invalid data length" 

### ISSUE THREAD

**Issue by laura-ding** [facebook/fbthrift#421]
I use the latest go lib, use the `BinaryProtocol` and `Socket`, but I get the exception `invalidDataLength`. And the BinaryProtocol needs to check p`.trans.RemainingBytes() == UnknownRemaining`, but I see the 

```
func (p *Socket) RemainingBytes() (num_bytes uint64) {
	return UnknownRemaining // the truth is, we just don't know unless framed is used
}
```

here is always true.  Is there anything to set?

**Comment by laura-ding** [comment]
@fiorix Could you take a look at it?

**Comment by natemueller** [comment]
You can no longer use the unframed protocols directly, because it is trivial for a client to crash your server.  You need to wrap it in the FramedTransport, then it should work.
