### ISSUE TITLE
How to bind multi services to one port with ThriftServer in cpp2?

### ISSUE THREAD

**Issue by LMig2k** [facebook/fbthrift#424]
Hi, in the exmaple, there are two service:  ChatRoomService and EchoService, is there any way to bind the two services to one port?
method 1: 
  auto handler = std::make_shared&lt;ChatRoomServiceHandler>();
  auto server = std::make_shared&lt;ThriftServer>();
  server->**setInterface**(handler);
  server->setPort(port);
  server->serve();

method 2:   
  auto handler = std::make_shared&lt;ServiceHandler>();
  auto proc_factory = std::make_shared&lt;ThriftServerAsyncProcessorFactory&lt;ServiceHandler>>(handler);
  auto server = std::make_shared&lt;ThriftServer>();
  server->setPort(port);
  server->**setProcessorFactory**(proc_factory);

**Comment by yfeldblum** [comment]
These would normally be run in two separate servers.

It is possible to set up a custom processor-factory with processors that can inspect the method name and dispatch appropriately. But this is not a normal usage.
