### ISSUE TITLE
Compile failed with the wrong usage of gmock. 

### ISSUE THREAD

**Issue by dangleptr** [facebook/fbthrift#425]
I am trying to compile some UTs in fbthrift.  
When i am trying to build 'thrift/lib/cpp2/test/RetryingRequestChannelTest.cpp',  it failed because of gmock don't support move-only types , such as unique_ptr in codegen interface.  (https://fuchsia.googlesource.com/third_party/googletest/+/HEAD/googlemock/docs/cook_book.md#mocking-methods-that-use-move_only-types)

So i want to know how did your guys build the UT?

**Comment by vitaut** [comment]
GMock does support move-only types although you might need to use a relatively recent version. The test in question is known to work with GMock 1.14.
