### ISSUE TITLE
fatal error: folly/experimental/channels/detail/AtomicQueue.h: No such file or directory

### ISSUE THREAD

**Issue by zahradehghanpur** [facebook/fbthrift#428]
Hi , when i want to compile the source code , i get the following error:
`fbthrift/thrift/lib/cpp2/async/TwoWayBridge.h:24:10: fatal error: folly/experimental/channels/detail/AtomicQueue.h: No such file or directory
 #include <folly/experimental/channels/detail/AtomicQueue.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/build.make:89: thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/GeneratedCodeHelper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:855: thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
`
i checked the folly project and this file folly/experimental/channels/detail/AtomicQueue.h does not exist...

**Comment by Revaj** [comment]
I found the same issue with master branch. I was able to compile it with v2021.05.24.00 tag.

**Comment by mshneer** [comment]
We are looking at the issues with folly - the repo is stale.

**Comment by mshneer** [comment]
For now please use the workaround from @Revaj  - i.e. v2021.05.24.00 tag
There are people working on getting folly up to date but this might take time. Sorry about it.

**Comment by schulei** [comment]
> For now please use the workaround from @Revaj - i.e. v2021.05.24.00 tag
> There are people working on getting folly up to date but this might take time. Sorry about it.

thanks

**Comment by mamrezb** [comment]
Same issue here
