### ISSUE TITLE
Could I specify the implementation of container in rust generating?

### ISSUE THREAD

**Issue by Shylock-Hg** [facebook/fbthrift#439]
E.g. for the `set` type, could I choose `HashSet` or `BtreeSet` implementation?

**Comment by vitaut** [comment]
It seems to be possible with the `rust.type` annotation: https://github.com/facebook/fbthrift/blob/c0f8ffb345d847df512ae9c404a58379fcd51cb9/thrift/lib/rust/test/if.thrift#L20
