### ISSUE TITLE
Maybe a bug in NumaThreadManager

### ISSUE THREAD

**Issue by dawnlucky** [facebook/fbthrift#44]
Hi guy,

I use threadmanager of NumaThreadManager, I just dynamic add workers and remove it.
but after remove sometimes, the server not response anything.

I look into the code, maybe the follow code need some judgement.

void NumaThreadManager::removeWorker(size_t t) {
  for (size_t i = 0; i < t; i++) {
    managers_[workerNode_-- % managers_.size()]->removeWorker(1);
  }
}

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
