### ISSUE TITLE
gcc, c++20 compilation error: constructor syntax

### ISSUE THREAD

**Issue by alex-700** [facebook/fbthrift#444]
There is a constructor of `ThriftAcceptorFactory` on [L1007](https://github.com/facebook/fbthrift/blob/36f38e4076c02d38233b95f44f43f2e67bd61b1f/thrift/lib/cpp2/server/ThriftServer.h#L1007) which can't be compiled with trunk `gcc --std=c++20`.

I'm not sure whether is this a bug of gcc or not ([simple godbolt reproducer](https://godbolt.org/z/bE685b6f1)), but it can be fixed easily here by dropping unnecessary `<AcceptorClass, SharedSSLContextManagerClass>`.

**Comment by vitaut** [comment]
Should be fixed in https://github.com/facebook/fbthrift/commit/6b616fb6390138c09d38a737c5a01996820f8879, thanks for reporting.
