### ISSUE TITLE
is there any reason only java fbthrift doesn't have ssl socket?

### ISSUE THREAD

**Issue by klay-ke** [facebook/fbthrift#469]
i can see 
python ssl socket: https://github.com/facebook/fbthrift/blob/master/thrift/lib/py/transport/TSSLSocket.py
go ssl socket: https://github.com/facebook/fbthrift/blob/master/thrift/lib/go/thrift/ssl_socket.go

https://github.com/facebook/fbthrift/tree/master/thrift/lib/java/src/main/java/com/facebook/thrift/transport
but there is no java version there, any reason?

**Comment by stevegury** [comment]
That code exists but it is in another closed-source project that is used internally at Facebook.
It is closed source because this library combines Facebook specific security configuration and SSL socket.

We should refactor that code, but to be entirely honest, it's not our top priority.
