### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [facebook/fbthrift#47]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html)" to [your build specification](https://github.com/facebook/fbthrift/blob/34ad64c2217ae6127aee19b904c5d0ab061a1254/thrift/configure.ac#L440)?

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
