### ISSUE TITLE
Difference between Rocket Parser::readDataAvailable methods.

### ISSUE THREAD

**Issue by Revaj** [facebook/fbthrift#479]
Hello!

I found in Rocket parser, it provides three alternatives of readDataAvailable method.

- readDataAvailableOld
- readDataAvailableNew
- readDataAvailableHybrid

I'm interested on the reason of why there are three alternatives. I found these alternatives here:
https://github.com/facebook/fbthrift/blob/4ce7857d40a6ef609bde704b514badf3c1043d25/thrift/lib/cpp2/transport/rocket/framing/Parser-inl.h#L456

**Comment by Revaj** [comment]
I see these alternatives are for optimize memory usage when it parses the arrived requests, specifically, to avoid copies and reallocs as possible. Is Meta interested to stabilize these experimental options? 🤔 I could with the efforts for stabilization or look for optimizations.

**Comment by avalonalex** [comment]
most of these stuff is now deleted, we will make some more future simplifications.

**Comment by Revaj** [comment]
> most of these stuff is now deleted, we will make some more future simplifications. 

Thanks!
