### ISSUE TITLE
Make fbthrift coexist with thrift

### ISSUE THREAD

**Issue by anatol** [facebook/fbthrift#48]
I am trying to pack fbthrift (and some other FB projects that need fbthrift). And now I am trying to understand the project structure.

One of the problems that I met is that it is not possible to install fbthrift along with thrift itself. Following files are conflicting if I run 'make install':

```
fbthrift-git: /usr/lib/libthrift.so exists in filesystem
fbthrift-git: /usr/lib/libthriftz.so exists in filesystem
fbthrift-git: /usr/lib/pkgconfig/thrift-z.pc exists in filesystem
fbthrift-git: /usr/lib/pkgconfig/thrift.pc exists in filesystem
```

Should the libraries be renamed to libfbthrift.so instead? This will make possible to install these 2 packages together.

The binary with name 'thrift1' also looks weird. I suggest to rename it to fbthrift.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by anatol** [comment]
Facebook Thrift team should absolutely look at https://issues.apache.org/jira/browse/THRIFT-2835

There are several proposals for Thrift plugins. It would be great if fb-thrift can use it instead of forking whole codebase.
