### ISSUE TITLE
Wrong check for libevent

### ISSUE THREAD

**Issue by RoyBellingan** [facebook/fbthrift#49]
I'm getting the error
...
checking for libevent >= 1.0... no
configure: error: Please install libevent

The code used to check the libevent version is https://gist.github.com/RoyBellingan/42d1cd5a974e64ce3367
(of course the stdio and the printf are mine, I've also hardcoded the min requested version)
This is around line 18070 in configure (another check is around 19888)
The first check is failed (and secondo seems to pass or is not executed) but the version  is 2.0.21-stable

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
