### ISSUE TITLE
When AX_BOOST_PYTHON fails, it sets BOOST_PYTHON_LIB="" which doesn't work

### ISSUE THREAD

**Issue by RoyBellingan** [facebook/fbthrift#50]
Make stop beacuse it found a -l 
The line is 

make[4]: Entering directory `/xxx/proxygen/proxygen/fbthrift/thrift/compiler/py'
/bin/sh ../../libtool  --tag=CXX   --mode=link g++  -std=gnu++0x -module -avoid-version -no-undefined -l -L/usr/lib64 -lpython2.7 -L/mnt/neuhome/home/roy/sorgenti/proxygen/proxygen/fbthrift/thrift/folly/folly/.libs/ -o frontend.la -rpath /usr/local/lib64 frontend_la-compiler.lo ../libparse.la ../libthriftcompilerbase.la -lssl -lcrypto -lrt -lpthread -lsasl2 -lfolly -lnuma -lsnappy -lgflags -lglog 

I've removed the -l and executed by hand the command and is ok, I've tried to search where the problem is but nothing.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
