### ISSUE TITLE
options of mstch_cpp2 (cpp2)

### ISSUE THREAD

**Issue by daleiz** [facebook/fbthrift#507]
Hi,
where can I find all options of cpp2 generator? like ``json``,``include_prefix``, etc.
``thrift1 --help`` shows no options for cpp2 : `` mstch_cpp2 (cpp2):``

**Comment by avalonalex** [comment]
you can search for `register_has_option` on this file https://github.com/facebook/fbthrift/blob/main/thrift/compiler/generate/t_mstch_cpp2_generator.cc

Note: not all existing options are recommended to use.
