### ISSUE TITLE
libssl-dev needed for Debian build

### ISSUE THREAD

**Issue by CJCombrink** [facebook/fbthrift#525]
Following the "Building" steps I still had to manually install `libssl-dev` on Debian before I could continue building fbthrift.

**Comment by thedavekwon** [comment]
Hi, I can try to figure out better way, but this are some pointers that talk about the missing libssl https://github.com/facebook/fbthrift/commit/946f48a849cda9be3b3fa10a7e63f1808e925623
and
https://github.com/facebook/fbthrift/blob/main/build/fbcode_builder/manifests/folly#L26

Thanks!

**Comment by vitaut** [comment]
SSL is listed as a dependency.

**Comment by CJCombrink** [comment]
Thanks for the responses.
Perhaps a check in the "Dependencies step", stating that it is missing?
```
sudo ./build/fbcode_builder/getdeps.py install-system-deps --recursive fbthrift
```

Or explicitly state that OpenSSL is actually not installed as suggested:
The wording and listing on the README made me believe that it would be installed, since it was not I raised this issue
See [Line 84](https://github.com/facebook/fbthrift/blob/main/README.md?plain=1#L84)

**Comment by vitaut** [comment]
It is installed if you omit `install-system-deps`. The latter option is specifically for the case when you want to install dependencies yourself.
