### ISSUE TITLE
build error fmt format

### ISSUE THREAD

**Issue by restlesswind** [facebook/fbthrift#549]
https://github.com/facebook/fbthrift/blob/main/thrift/lib/cpp2/server/ParallelConcurrencyController.cpp#L159

It seems like the line should look 
"{{ParallelConcurrencyController executionLimit={}}}", executionLimit_.load());
instead of
"{{ParallelConcurrencyController executionLimit={}}}", executionLimit_);

**Comment by Mizuchi** [comment]
Thanks for reporting. fmtlib broke it (https://github.com/fmtlib/fmt/commit/fce74caa15b24cbc0fcafe4706692cb06cb0b815). Let me check with the author.

**Comment by vitaut** [comment]
Fixed in https://github.com/facebook/fbthrift/commit/ae499882a1bfe8a6e2348e749a68010833ea1771.
