### ISSUE TITLE
2023.05.01.00: The library libcompiler_base  changed type from shared to static

### ISSUE THREAD

**Issue by yurivict** [facebook/fbthrift#551]
Previous versions installed these libs:
```
lib/libcompiler_base.so
lib/libcompiler_base.so.1.0.0
```
among many other shared libs.

2023.05.01.00 installs 
```
lib/libcompiler_base.a
```
which is the only static lib among many other shared libs.

This looks like a mistake.

**Comment by nanshu** [comment]
It's not. See b537aed .
