### ISSUE TITLE
fatal error: thrift/lib/thrift/gen-cpp2/protocol_types.h: No such file or directory

### ISSUE THREAD

**Issue by xiedeacc** [facebook/fbthrift#565]
I want use bazel to build fbthrift, but it seems some file miss generated, how generate these files?

**Comment by avalonalex** [comment]
These files are generated using thrift compiler. Thrift compiler reads `.thrift` file and generates bunch of sources files for specified programming languages. You can check here https://github.com/facebook/fbthrift/blob/main/ThriftLibrary.cmake#L190
