### ISSUE TITLE
missing build/deps/github_hashes/facebook/mvfst-rev.txt

### ISSUE THREAD

**Issue by ahornby** [facebook/fbthrift#577]
I see intermittent build breaks due to mismatched mvfst and folly versions from fbthrift

fbthrift uses mvfst from thrift/conformance/stresstest/client/ClientFactory.cpp  but doesn't declare the dependency with a build/deps/github_hashes/facebook/mvfst-rev.txt.

Without that config it pulls mvfst main branch, which may or may not be compatible with the other submodules (notably folly)

Ask is to add the mvfst dependency to the internal fbthrift shipit config so that the mvfst-rev.txt reference gets added and auto-updated but the update submodules step

cc @michel-slm for mvfst

**Comment by ahornby** [comment]
Cc @bigfootjon

**Comment by bigfootjon** [comment]
Fixed in https://github.com/facebook/fbthrift/pull/592
