### ISSUE TITLE
HandlerCallback exception() runs outside EventBase

### ISSUE THREAD

**Issue by varunsharmagit** [facebook/fbthrift#58]
We tried to run callback->exception using the HandlerCallback inside a CPP2 ThriftServer using the async_tm callbacks and when we run the exception() call, it fails saying that "not running in eventbase thread". It appears while the callback->result() call does the right thing in terms of switching to the EVB thread, the callback->exception() call does not.

**Comment by alandau** [comment]
Fixed internally, will be available on github at the next push.
