### ISSUE TITLE
Unable to link against libressl / boringssl - get_cipher_by_char usage

### ISSUE THREAD

**Issue by Nemykal** [facebook/fbthrift#61]
While compiling hhvm with a linux system that uses libressl I noted that I get errors like:

In file included from /root/tmp/hhvm/third-party/proxygen/lib/ssl/SSLUtil.h:14:0,
                 from /root/tmp/hhvm/third-party/proxygen/lib/services/ServerSocketConfig.h:14,
                 from /root/tmp/hhvm/third-party/proxygen/lib/services/Acceptor.h:14,
                 from /root/tmp/hhvm/third-party/proxygen/lib/services/Acceptor.cpp:10:
/root/tmp/hhvm/third-party/thrift/thrift/lib/cpp/async/TAsyncSSLSocket.h: In member function 'void apache::thrift::async::TAsyncSSLSocket::getSSLClientCiphers(std::string&)':
/root/tmp/hhvm/third-party/thrift/thrift/lib/cpp/async/TAsyncSSLSocket.h:558:29: error: 'const SSL_METHOD' has no member named 'get_cipher_by_char'
           TLSv1_2_method()->get_cipher_by_char((unsigned char*)&cipherCode);

get_cipher_by_char seems to have been removed in non-openssl openssl's because it's unnecessary with sslv2/v3 removed. 

It would be nice if hhvm supported being built against libressl too.

Cheers,
Michael

**Comment by tedu** [comment]
The current best translation strategy is probably outlined here: http://marc.info/?l=openbsd-tech&m=141823467424781&w=2

**Comment by tedu** [comment]
I wouldn't make any changes immediately though. get_cipher_by_char was supposed to be an internal interface (or so we would have liked to believe), but it seems more than a few programs have found it and started calling it. It may come back to libressl.

**Comment by tedu** [comment]
The magic of get_cipher_by_char has been restored to libressl. It should land in the next portable release in a few days, and then this issue can be closed.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
