### ISSUE TITLE
Broken installation with PY_PREFIX

### ISSUE THREAD

**Issue by jucor** [facebook/fbthrift#62]
Hi

When using PY_PREFIX for a local installation as recommended in the [README](https://github.com/facebook/fbthrift/blob/master/thrift/README#L121), `make install` still tries to `mkdir -p /lib/python`. This is due to 
[https://github.com/facebook/fbthrift/blob/master/thrift/compiler/py/Makefile.am#L48](this line of Makefile.am), which uses `PY_INSTALL_HOME` in the `mkdir` even though the `PY_INSTALL_ARGS` used by `setup.py` is actually set to `PY_PREFIX` in the [main configure script](https://github.com/facebook/fbthrift/blob/master/thrift/configure.ac#L44). 

This causes `make install` to fail when run as normal user, because normal user cannot create `/lib/python`.

I think the mkdir should use the same path as `PY_INSTALL_ARGS` does.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kyrofa** [comment]
Hmm... 30 days, well over a year, who's counting?

**Comment by mineshmathew** [comment]
Is there any update on this? I am stuck with this.
Is there any versions /releases of fblualib and all its all dependencies which can be installed locally on Ubuntu 14.04 without much hassle . I have been trying to get it right for the last couple of days. Had hard time manually editing makefiles and trying to things work, but one or the other fail everytime

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
