### ISSUE TITLE
Propagating Exceptions from server to client

### ISSUE THREAD

**Issue by trigger-happy** [facebook/fbthrift#71]
I'm trying to get my client to catch exceptions that are thrown on the server side but can't seem to get it to work. Am I doing something wrong or is passing exceptions from server to client not supported with fbthrift? https://drive.google.com/file/d/0B160EuskaxhTd084eDFzWXpTclE/view?usp=sharing

**Comment by senior7515** [comment]
@trigger-happy 

I just ran it w/ the latest libs 0.22.0 and 0.19.0 and you are correct. I haven't debugged the library yet, but it's definitely a problem with thrift and not with folly futures. 

I ran the same test w/ the futures and the onError callback does get propagated with either Future<void> and Future<T>.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by djwatson** [comment]
A futures exception bug was fixed recently.

Otherwise exceptions should be the same as cpp - make sure your .thrift file defines the exception.
