### ISSUE TITLE
Java compile failed. Package com.facebook.fbcode.fb303 does not exist.

### ISSUE THREAD

**Issue by philippe-tr** [facebook/fbthrift#72]
On a Vagrant VM with Oracle VirtualBox as the provider, running ubuntu/trusty64 as a guest. Ran the ./deps.sh script to completion without any apparent errors.

Then, ran ANT in the thrift/lib/java folder. The compilation fails with message Package com.facebook.fbcode.fb303 does not exist.

The build output:

vagrant@vagrant-ubuntu-trusty-64:/vagrant/thrift/lib/java$ ant
Buildfile: /vagrant/thrift/lib/java/build.xml

init:

ivy-init-dirs:

ivy-download:
      [get] Getting: http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.0.0-rc2/ivy-2.0.0-rc2.jar
      [get] To: /vagrant/thrift/lib/java/build/ivy/ivy-2.0.0-rc2.jar
      [get] Not modified - so not downloaded

ivy-probe-antlib:

ivy-init-antlib:

resolve:
No ivy:settings found for the default reference 'ivy.instance'.  A default instance will be used
no settings file found, using default...
[ivy:retrieve] :: Ivy 2.0.0-rc2 - 20081028224207 :: http://ant.apache.org/ivy/ ::
:: loading settings :: url = jar:file:/vagrant/thrift/lib/java/build/ivy/ivy-2.0.0-rc2.jar!/org/apache/ivy/core/settings/ivysettings.xml
[ivy:retrieve] :: resolving dependencies :: jayasoft#hello-ivy;working@vagrant-ubuntu-trusty-64
[ivy:retrieve]  confs: [default]
[ivy:retrieve]  found org.slf4j#slf4j-api;1.5.8 in public
[ivy:retrieve]  found org.slf4j#slf4j-simple;1.5.8 in public
[ivy:retrieve]  found commons-lang#commons-lang;2.4 in public
[ivy:retrieve] :: resolution report :: resolve 315ms :: artifacts dl 6ms
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
        ---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: jayasoft#hello-ivy
[ivy:retrieve]  confs: [default]
[ivy:retrieve]  0 artifacts copied, 3 already retrieved (0kB/19ms)

compile:
    [javac] /vagrant/thrift/lib/java/build.xml:115: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 95 source files to /vagrant/thrift/lib/java/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.5
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/DirectTProcessorEventHandler.java:15: error: package com.facebook.fbcode.fb303 does not exist
    [javac] import com.facebook.fbcode.fb303.FacebookBase;
    [javac]                                 ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/DirectTProcessorEventHandler.java:21: error: cannot find symbol
    [javac]   protected FacebookBase handler_;
    [javac]             ^
    [javac]   symbol:   class FacebookBase
    [javac]   location: class DirectTProcessorEventHandler
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/DirectTProcessorEventHandler.java:61: error: cannot find symbol
    [javac]   public DirectTProcessorEventHandler(FacebookBase h) {
    [javac]                                       ^
    [javac]   symbol:   class FacebookBase
    [javac]   location: class DirectTProcessorEventHandler
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/MovingAvgStat.java:13: error: package com.facebook.fbcode.fb303 does not exist
    [javac] import com.facebook.fbcode.fb303.FacebookBase;
    [javac]                                 ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/DirectTProcessorEventHandler.java:30: error: cannot find symbol
    [javac]     TStat(FacebookBase h, String fn_name) {
    [javac]           ^
    [javac]   symbol:   class FacebookBase
    [javac]   location: class TStat
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/MovingAvgStat.java:38: error: cannot find symbol
    [javac]   protected FacebookBase handler_;
    [javac]             ^
    [javac]   symbol:   class FacebookBase
    [javac]   location: class MovingAvgStat
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/MovingAvgStat.java:140: error: cannot find symbol
    [javac]   public MovingAvgStat(FacebookBase h, String fName, MovingAvgStat b) {
    [javac]                        ^
    [javac]   symbol:   class FacebookBase
    [javac]   location: class MovingAvgStat
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:3: error: package org.junit does not exist
    [javac] import static org.junit.Assert.*;
    [javac]                        ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:10: error: package org.junit does not exist
    [javac] import org.junit.BeforeClass;
    [javac]                 ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:11: error: package org.junit does not exist
    [javac] import org.junit.Test;
    [javac]                 ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:13: error: package com.facebook.fbcode.fb303 does not exist
    [javac] import com.facebook.fbcode.fb303.fb_status;
    [javac]                                 ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:22: error: package JavaSimpleService does not exist
    [javac]   private static JavaSimpleService.Client newClient() throws Exception {
    [javac]                                   ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/SimpleServiceHandler.java:8: error: package com.facebook.fbcode.fb303 does not exist
    [javac]   extends com.facebook.fbcode.fb303.FacebookBase
    [javac]                                    ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/SimpleServiceHandler.java:9: error: package JavaSimpleService does not exist
    [javac]   implements JavaSimpleService.Iface {
    [javac]                               ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/SimpleServiceHandler.java:15: error: cannot find symbol
    [javac]   public String simple(SimpleRequest r) throws TException {
    [javac]                        ^
    [javac]   symbol:   class SimpleRequest
    [javac]   location: class SimpleServiceHandler
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/TestServer.java:15: error: package com.facebook.fbcode.fb303 does not exist
    [javac] import com.facebook.fbcode.fb303.*;
    [javac] ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/Tester.java:32: error: package JavaSimpleService does not exist
    [javac]   static JavaSimpleService.Client getClient(String host, int port) {
    [javac]                           ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/transport/THeaderTransport.java:31: error: package org.iq80.snappy does not exist
    [javac] import org.iq80.snappy.Snappy;
    [javac]                       ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/transport/THeaderTransport.java:32: error: package org.iq80.snappy does not exist
    [javac] import org.iq80.snappy.CorruptionException;
    [javac]                       ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:10: error: package javax.servlet does not exist
    [javac] import javax.servlet.ServletException;
    [javac]                     ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:11: error: package javax.servlet.http does not exist
    [javac] import javax.servlet.http.HttpServlet;
    [javac]                          ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:12: error: package javax.servlet.http does not exist
    [javac] import javax.servlet.http.HttpServletRequest;
    [javac]                          ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:13: error: package javax.servlet.http does not exist
    [javac] import javax.servlet.http.HttpServletResponse;
    [javac]                          ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:26: error: cannot find symbol
    [javac] public class TServlet extends HttpServlet {
    [javac]                               ^
    [javac]   symbol: class HttpServlet
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:60: error: cannot find symbol
    [javac]   protected void doPost(HttpServletRequest request, HttpServletResponse response)
    [javac]                         ^
    [javac]   symbol:   class HttpServletRequest
    [javac]   location: class TServlet
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:60: error: cannot find symbol
    [javac]   protected void doPost(HttpServletRequest request, HttpServletResponse response)
    [javac]                                                     ^
    [javac]   symbol:   class HttpServletResponse
    [javac]   location: class TServlet
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:61: error: cannot find symbol
    [javac]       throws ServletException, IOException {
    [javac]              ^
    [javac]   symbol:   class ServletException
    [javac]   location: class TServlet
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:97: error: cannot find symbol
    [javac]   protected void doGet(HttpServletRequest request, HttpServletResponse response)
    [javac]                        ^
    [javac]   symbol:   class HttpServletRequest
    [javac]   location: class TServlet
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:97: error: cannot find symbol
    [javac]   protected void doGet(HttpServletRequest request, HttpServletResponse response)
    [javac]                                                    ^
    [javac]   symbol:   class HttpServletResponse
    [javac]   location: class TServlet
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:98: error: cannot find symbol
    [javac]       throws ServletException, IOException {
    [javac]              ^
    [javac]   symbol:   class ServletException
    [javac]   location: class TServlet
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:28: error: cannot find symbol
    [javac]   @BeforeClass
    [javac]    ^
    [javac]   symbol:   class BeforeClass
    [javac]   location: class JUnitTestHsHaServer
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:55: error: cannot find symbol
    [javac]   @Test
    [javac]    ^
    [javac]   symbol:   class Test
    [javac]   location: class JUnitTestHsHaServer
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:62: error: cannot find symbol
    [javac]   @Test
    [javac]    ^
    [javac]   symbol:   class Test
    [javac]   location: class JUnitTestHsHaServer
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:25: error: package JavaSimpleService does not exist
    [javac]     return new JavaSimpleService.Client(new TBinaryProtocol(trans));
    [javac]                                 ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:30: error: package JavaSimpleService does not exist
    [javac]     JavaSimpleService.Processor proc =
    [javac]                      ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:31: error: package JavaSimpleService does not exist
    [javac]         new JavaSimpleService.Processor(new SimpleServiceHandler());
    [javac]                              ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:43: error: cannot find symbol
    [javac]         if (newClient().getStatus() == fb_status.ALIVE) {
    [javac]                                        ^
    [javac]   symbol:   variable fb_status
    [javac]   location: class JUnitTestHsHaServer
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/JUnitTestHsHaServer.java:57: error: cannot find symbol
    [javac]     assertEquals(fb_status.ALIVE, newClient().getStatus());
    [javac]                  ^
    [javac]   symbol:   variable fb_status
    [javac]   location: class JUnitTestHsHaServer
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/SimpleServiceHandler.java:17: error: cannot find symbol
    [javac]     if (this.hashCode() == System.currentTimeMillis()) {
    [javac]             ^
    [javac]   symbol: method hashCode()
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/SimpleServiceHandler.java:33: error: package com.facebook.fbcode.fb303 does not exist
    [javac]     return com.facebook.fbcode.fb303.fb_status.ALIVE;
    [javac]                                     ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/TestHsHaServer.java:32: error: package JavaSimpleService does not exist
    [javac]     JavaSimpleService.Processor processor =
    [javac]                      ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/TestHsHaServer.java:33: error: package JavaSimpleService does not exist
    [javac]       new JavaSimpleService.Processor(handler);
    [javac]                            ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/TestServer.java:27: error: package JavaSimpleService does not exist
    [javac]     JavaSimpleService.Processor processor =
    [javac]                      ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/TestServer.java:28: error: package JavaSimpleService does not exist
    [javac]       new JavaSimpleService.Processor(handler);
    [javac]                            ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/TestServer.java:32: error: cannot find symbol
    [javac]         new DirectTProcessorEventHandler((FacebookBase)handler));
    [javac]                                           ^
    [javac]   symbol:   class FacebookBase
    [javac]   location: class TestServer
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/Tester.java:41: error: package JavaSimpleService does not exist
    [javac]         JavaSimpleService.Client cli = new JavaSimpleService.Client(proto);
    [javac]                          ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/Tester.java:41: error: package JavaSimpleService does not exist
    [javac]         JavaSimpleService.Client cli = new JavaSimpleService.Client(proto);
    [javac]                                                             ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/Tester.java:61: error: package JavaSimpleService does not exist
    [javac]         JavaSimpleService.Client cli = getClient(host_, port_);
    [javac]                          ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/Tester.java:96: error: cannot find symbol
    [javac]       SimpleRequest r = new SimpleRequest();
    [javac]       ^
    [javac]   symbol:   class SimpleRequest
    [javac]   location: class MultiTestThread
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/Tester.java:96: error: cannot find symbol
    [javac]       SimpleRequest r = new SimpleRequest();
    [javac]                             ^
    [javac]   symbol:   class SimpleRequest
    [javac]   location: class MultiTestThread
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/direct_server/tests/Tester.java:101: error: package JavaSimpleService does not exist
    [javac]         JavaSimpleService.Client cli = getClient(host_, port_);
    [javac]                          ^
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/transport/THeaderTransport.java:530: error: cannot find symbol
    [javac]           Snappy.getUncompressedLength(
    [javac]           ^
    [javac]   symbol:   variable Snappy
    [javac]   location: class THeaderTransport
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/transport/THeaderTransport.java:533: error: cannot find symbol
    [javac]         int length = Snappy.uncompress(
    [javac]                      ^
    [javac]   symbol:   variable Snappy
    [javac]   location: class THeaderTransport
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/transport/THeaderTransport.java:540: error: cannot find symbol
    [javac]       } catch (CorruptionException e) {
    [javac]                ^
    [javac]   symbol:   class CorruptionException
    [javac]   location: class THeaderTransport
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/transport/THeaderTransport.java:568: error: cannot find symbol
    [javac]       byte[] outputBuffer = new byte[Snappy.maxCompressedLength(data.limit())];
    [javac]                                      ^
    [javac]   symbol:   variable Snappy
    [javac]   location: class THeaderTransport
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/transport/THeaderTransport.java:569: error: cannot find symbol
    [javac]       int length = Snappy.compress(
    [javac]                    ^
    [javac]   symbol:   variable Snappy
    [javac]   location: class THeaderTransport
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:89: error: cannot find symbol
    [javac]       throw new ServletException(te);
    [javac]                 ^
    [javac]   symbol:   class ServletException
    [javac]   location: class TServlet
    [javac] /vagrant/thrift/lib/java/src/com/facebook/thrift/server/TServlet.java:59: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] 58 errors
    [javac] 1 warning

BUILD FAILED
/vagrant/thrift/lib/java/build.xml:115: Compile failed; see the compiler error output for details.

Total time: 12 seconds

**Comment by alandau** [comment]
Java builds were not really tested in fbthrift. The supported version of Java for fbthrift is https://github.com/facebook/nifty/ and https://github.com/facebook/swift (or the original Apache Thrift).
Alternatively, if a small patch can fix the error, I'll be glad to accept it.
