### ISSUE TITLE
Broken Generation cpp2 with python -mthrift_compiler not thrift1 

### ISSUE THREAD

**Issue by senior7515** [facebook/fbthrift#73]
Error: 

```
include/bolt/gen-cpp2/bolt_types.h:13:10: fatal error: 'thrift/lib/cpp2/protocol/SimpleJSONProtocol.h' file not found
#include <thrift/lib/cpp2/protocol/SimpleJSONProtocol.h>

```

Given this options to ` python -m thrift_compiler ` 
```
--gen cpp2:process_in_event_base,include_prefix,future,bootstrap,frozen2,json,implicit_templates"
```

Version 0.22.0

The cause is that thrift/lib/cpp2/protocol/SimpleJSONProtocol.h is not exported to /usr/local/include/...

**Comment by roticv** [comment]
I believe this is already fixed, but it is pending a sync. The cause of the compile error is due to the option json added to cpp2 but SimpleJsonProtocol.h wasn't added to Makefile.am.

**Comment by senior7515** [comment]
@roticv  thanks! let me know when its synced. I'd love to test.

**Comment by senior7515** [comment]
@roticv any ideas of the ETA for this sync will come?

**Comment by roticv** [comment]
The sync happened two days ago
