### ISSUE TITLE
The java/swift tutorial fails to build

### ISSUE THREAD

**Issue by vprithvi** [facebook/fbthrift#76]
It includes `com.facebook:facebook-base-pom:pom`, which isn't on Maven Central.

Other includes that I couldn't find on Maven Central are 
`com.facebook.nifty:nifty-header-protocol`
`com.facebook.swift.swift-fb303`

How do we get started on a Java server/client that uses the `THeaderProtocol` on a `THeaderTransport` ?

```
fbthrift/thrift/tutorial/java/swift> mvn clean build                                                                                                                      
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=4048m; support was removed in 8.0
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.facebook.swift:swift-tutorial-parent:0.11.0-SNAPSHOT (/Users/prithvi/knewton/fbthrift/thrift/tutorial/java/swift/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find com.facebook:facebook-base-pom:pom:7 in https://nexus.knewton.net/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of knewton has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 9, column 11 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by alandau** [comment]
Java builds were not really tested in fbthrift. The supported version of Java for fbthrift is https://github.com/facebook/nifty/ and https://github.com/facebook/swift, both of which contain examples (or the original Apache Thrift).

**Comment by vprithvi** [comment]
@alandau We are most interested in ``THeaderProtocol`` and ``THeaderTransport``, both of which are not contained in the facebook/nifty or facebook/swift projects. 
Is it planned for these to be generally available ?

**Comment by alandau** [comment]
Yes, header protocol support for nifty and swift is available internally and we're working on opensourcing it.
