### ISSUE TITLE
Please pull in latest version of folly and tag version

### ISSUE THREAD

**Issue by emyr666** [facebook/fbthrift#77]
Hi,
There has been a fix to folly which sorts out some compiler warnings. The latest tag they have is v0.27.0. Can you update deps.sh to pull in this folly version and also tag your latest version so that upstream projects such as proxygen can pull in an upt-to-date version of fbthrift.
Many thanks,
Emyr

**Comment by arjenroodselaar** [comment]
folly was dumped to v0.47 yesterday.
