### ISSUE TITLE
install target for lib/erl

### ISSUE THREAD

**Issue by sinjar666** [facebook/fbthrift#79]
I observed that python and cpp2 libraries have an install mechanism (cpp2 has via makefile itself) and the py has a setup.py. However the erl folder doesnt seem to have any install mechanism as far as i can see. Even the example code seems to reference it via relative path (erl -pa) 
So does this mean that for a deployment I need to include the lib/erl directory along with my project or I have to manually copy these somewhere.

Please correct me if I am wrong. Thanks in advance!

**Comment by sinjar666** [comment]
Any help is appreciated. I am sure someone would have used thrift erlang bindings and faced this issue. It would be great if you could share how you have set this up.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by djwatson** [comment]
Sorry, we haven't been actively supporting anything except the cpp2 code.
