### ISSUE TITLE
Exception passing broken for wangle future based servers

### ISSUE THREAD

**Issue by varunsharmagit** [facebook/fbthrift#80]
We are seeing an issue where if a server returns a future wrapping an exception using:

makeFuture<void>(exc_wrapper);

The exception is not being propagated back to the client. This issue only happens for future based servers - the servers implementing async_eb* methods work just fine.

**Comment by djwatson** [comment]
There appears to already be a test for this (https://github.com/facebook/fbthrift/blob/master/thrift/lib/cpp2/test/FutureTest.cpp#L87) and It Works For Me (tm).  Do you have an example that fails?
