### ISSUE TITLE
Detecting closed connections due to server restarts

### ISSUE THREAD

**Issue by varunsharmagit** [facebook/fbthrift#81]
We are using the CPP2 header channel against a CPP2 thrift server with two way pipelining. At times, we need to restart the server to deploy code etc. At this point the connection is closed and we would like to detect this. We tried using the good() call against the TAsyncSocket but it seems that it only returns false, if a request has been issued against the connection. Is there a way to detect this (preferably through a function call and not through callbacks) ?

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by djwatson** [comment]
I'm not sure the issue, good() should work?

For a callback, HeaderClientChannel::setCloseCallback() will give you async close callbacks
