### ISSUE TITLE
How to detect when threadmanager queue overloaded?

### ISSUE THREAD

**Issue by azgo14** [facebook/fbthrift#85]
In AsyncProcessor.h, when you call HandlerCallback's runFuncInQueue, it's possible for the thread manager's queue to be overloaded. In this code path, though, there doesn't seem to be a way to detect this overloaded case so that we can destroy the HandlerCallback. An example of such a case is as shown in the following psuedo code:

```
auto callback_ptr = callback.release();    // callback is an instance of HandlerCallback
callback_ptr->runFuncInQueue(
    [callback_ptr]() { callback_ptr->doneInThread(); });
```

In this case, if the queue is full, then the HandlerCallback never seems to be destroyed. Is this the case?

Also another semi-unrelated question: Is it possible to allow support for setting the timeout/exception for runFuncInQueue? Seems like currently the timeouts/exceptions are hardcoded to be 0.

**Comment by haijunz** [comment]
This seems like a real issue, I'll create a fix.

timeout is set for a request when it comes in. If timeout expires before the task starts running it won't be run. If it expires when the task is running it will run to the end and the result will be sent back. You can set a global task expire time, and you can also override it per task will RpcOptions.

**Comment by azgo14** [comment]
Cool thanks :)

also for my timeout question, one example use case for the timeout on runFuncInQueue is that if the task hasn't started and the hard timeout set for the request has elapsed already, it doesn't make sense to run that func later on if the response will not be sent, especially when there could be requests in the Queue that are still valid and should be run. Though setting a hard limit on the queue's size could help with this, it doesn't seem as clean as allowing timeouts for runFuncInQueue.

**Comment by haijunz** [comment]
Yep that's how it works. Basically the first thing the task does is to check if the request is still active and the timeout handler will set the request to inactive and send a timeout response back.

**Comment by haijunz** [comment]
This is fixed.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
