### ISSUE TITLE
how  to user async interface with cpp2

### ISSUE THREAD

**Issue by joan2015** [facebook/fbthrift#86]
I can't find any example ,need help
the test dir has no server code

**Comment by andrewcox** [comment]
One example is here:

https://github.com/facebook/fbthrift/blob/master/thrift/perf/cpp/AsyncClientWorker2.cpp

This example is our from our perf load generator. It generates a bunch of pipelined calls on a client up to N outstanding requests on that client, and keeps the pipe full.

It is not the greatest example, but it is something.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
