### ISSUE TITLE
Generation of <idl_types.h> should be the same for thrift1 and fbthrift

### ISSUE THREAD

**Issue by senior7515** [facebook/fbthrift#88]
I have to interact w/ apache thrift in some cpp code but use cpp2 generator for other internal services. 

Basically the generated types are exactly the same and your code ends up looking like this 

```
ApacheType t1 = apacheThriftService.call();
FBType *t2 = (FBType *) &t1;
```

For every single interaction between old thrift and fbthrift.

It seems unnecessary to namespace the types.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by djwatson** [comment]
Does 'compatibility' generator option work for you?  Its goal was to fix this exact issue.
