### ISSUE TITLE
Making reflection work for cpp2

### ISSUE THREAD

**Issue by varunsharmagit** [facebook/fbthrift#89]
For cpp2, it seems the reflection.h files are not being created. We need to use reflection on our thrift structures. Whats the best way to do this ?

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by djwatson** [comment]
cpp2 doesn't currently support reflection in the same way cpp did.
