### ISSUE TITLE
makefile bug

### ISSUE THREAD

**Issue by joan2015** [facebook/fbthrift#91]
There is a bug when make thrift1. Folly use boost::context, and the thrift/compiler/Makefile does not link the lib.The Makefile need add the boost context lib

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
