### ISSUE TITLE
Using latest folly libraries

### ISSUE THREAD

**Issue by eklavya1983** [facebook/fbthrift#92]
I am trying to use fbthrift with proxygen.  Both of them use folly, however, proxygen uses v0.37.0 and fbthrift is using v0.32.0.  It'd be nice if fbthrift can be upgraded to use latest folly libraries.

**Comment by andrewcox** [comment]
Yep, working on pushing this out.

**Comment by eklavya1983** [comment]
Thanks!!  Appreciate the help.

**Comment by arjenroodselaar** [comment]
Yesterday's push got folly to v0.47.
