### ISSUE TITLE
Problem about undefined reference

### ISSUE THREAD

**Issue by MediavGator** [facebook/fbthrift#97]
I've met this problem for several days, and didn't know how to solve it. Plz kindly help me~~

[1] undefined reference to `student_reflection_::reflectionInitializer_10102442120299088108(apache::thrift::reflection::Schema&)'
[2] similar undefined reference to TEventServerCreator

And the following is my demo thrift,
struct Student{           
  1: i32 sno,
  2: string sname,
  3: bool ssex,
  4: i16 sage,
}

service Serv{
  void put(1:Student s), 
}

Scenario:
[a] I compiled and installed the fbthrift just use fbthrift/thrift/deps.sh on my 3.13.0-52-generic #85-Ubuntu, and use generated thrift1 to get files in gen-cpp

/fbthrift/fbthrift/thrift# ldd /usr/local/bin/thrift1 
	linux-vdso.so.1 =>  (0x00007ffccd3d9000)
	libfolly.so.32 => /usr/local/lib/libfolly.so.32 (0x00007f6b79246000)
	...
[b] then I found this line in my Serv_server.skeleton.cpp
#include <thrift/lib/cpp/util/TEventServerCreator.h>

[c] but when I try to compile the skelenton file, I got undefined reference to TEventServerCreator
This is the makefile I used, is there anything wrong?

USR_DIR    =/usr/local
INCS_DIRS  =-I${USR_DIR}/include/thrift/lib/cpp  -I${USR_DIR}/include/thrift/lib/cpp2 -I${USR_DIR}/include/folly -I/home/fanwang/fbthrift/fbthrift

CPP_DEFS   =-D=HAVE_CONFIG_H
CPP_OPTS   =-Wall -O2 -std=c++11 -Wl,--no-as-needed

GEN_SRC    = ./gen-cpp/Serv.cpp  \
             ./gen-cpp/student_types.cpp   \   
             ./gen-cpp/student_constants.cpp 
GEN_INC    = -I./gen-cpp

default: server client

server:                                                               
  g++ ${CPP_OPTS} ${CPP_DEFS} ${GEN_INC} ${INCS_DIRS} ./gen-cpp/Serv_server.skeleton.cpp ${GEN_SRC} /home/fanwang/fbthrift/fbthrift/thrift/lib/cpp/.libs/libthrift.so /home/fanwang/fbthrift/fbthrift/thrift/lib/cpp2/.libs/libthriftcpp2.so /home/fanwang/fbthrift/fbthrift/thrift/folly/folly/.libs/libfolly.so -o CppServer

clean:
  $(RM) -r CppClient CppServer

**Comment by MediavGator** [comment]
add the missing code in Scenario [b] #include <thrift/lib/cpp/util/TEventServerCreator.h>

**Comment by MediavGator** [comment]
#include < thrift/lib/cpp/util/TEventServerCreator.h >

**Comment by arjenroodselaar** [comment]
It looks like the Makefile is missing TEventServerCreator.cpp. So while the header file is there the library is really missing the symbols. Unfortunately this has happened in more places. Would you mind applying the following diff to your fbthrift checkout, rebuilding the lib and retry linking your application? https://gist.github.com/arjenroodselaar/417afb03485b6432f4ee

**Comment by djwatson** [comment]
We're not trying to support cpp in fbthrift, only cpp2 - please use apache thrift if you only need cpp.
